### ISSUE TITLE
libicu package not found

### ISSUE THREAD

**Issue by denevin** [BC-SECURITY/Empire#118]
## Empire Version
3.1.0

## OS Information (Linux flavor, Python version)
Kali Linux Rolling

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

when running install.sh the 'libicu57_57.1-6+deb9u2_amd64.deb' file is no longer available from the following URL 'http://ftp.us.debian.org/debian/pool/main/i/icu/libicu57_57.1-6+deb9u2_amd64.deb'

The available filename is now 'libicu57_57.1-6+deb9u3_amd64.deb' at the following URL 'http://ftp.us.debian.org/debian/pool/main/i/icu/libicu57_57.1-6+deb9u3_amd64.deb'

It would be helpful to have the install script handle the condition where the minor package update is downloaded automatically. 

The empire install script also showed the message that the installation was successfull even though the download of this package failed. It would be nice to have an indicator that a package failed after the install script finishes.

## Screenshot of error, embedded text output, or Pastebin link to the error
None

## Any additional information
None

**Comment by vinnybod** [comment]
On the latest Kali, we can install Powershell using `apt update && apt -y install powershell`, so we can simplify that part of the script quite a bit.

This probably also impacts the Deb 10 instructions which points at specific file names as well.

Ref:
https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-7#kali
