### ISSUE TITLE
Update install.sh for seamless Debian 10.3 installation

### ISSUE THREAD

**Issue by RedBulletTooling** [BC-SECURITY/Empire#122]
Setup;
Using the latest Debian 10.3 (which includes Python 3.7.3)
Using the latest Empire version

Did some extensive testing and the install.sh script only finishes completely fine on a fresh clean install of Debian 10.3 when the following packages are installed before running the script;

apt install git python3-pip swig libssl-dev sudo

(git, python3-pip and sudo are quite self-evident, but aren't present in fresh Debian 10.3 and are also not installed or checked by the install.sh script so it just walks over it without a proper warning 
 causing even more confusion.)

This prevents all the very annoying library issues you would get otherwise. Could insert it on my own in the install.sh script, but thought since this is such a simple fix you guys probably know the best place for it in the script anyways.

If you don't care and want me to throw it into the install.sh script as I see fit, just say so and I'll create a pull req.

**Comment by RedBulletTooling** [comment]
First thoughts;

Check before sudo if sudo is present; if not use su => install sudo and return to normal user. Afterwards continue as normal and ask for sudo. (Probably should add some automatic code to add user to sudo file, otherwise user will get the error for sure.) 

Add check for Debian 10.x (or add to existing check if possible (some deps need to be installed first) and install
python3-pip (since this for some reason isn't catched by the code already included to make sure this is installed)
swig
libssl-dev

Done.

**Comment by adamczi** [comment]
I'd like to add that `apt-get install python3-pip swig libssl-dev` is necessary to run on a fresh Ubuntu 20.04 as well, before starting Empire setup. Any reason for not including it in the `./setup/install.sh` script?

Also since inclusion of Poetry, `sudo pip3 install poetry` is also needed beforhand, so this also could be added to the `requirements.txt`.

**Comment by vinnybod** [comment]
I have a fix for this going into the 4.0 release, which is targeted to go out in a couple of months (alpha build for sponsors and Kali in a couple weeks). Rewrote the whole install script and so far in testing it seems to work on a completely fresh container for Ubuntu 20.04 and Debian 10.
