### ISSUE TITLE
[BUG] RESTful API create listener UnboundLocalError when Name is not provided

### ISSUE THREAD

**Issue by RedBulletTooling** [BC-SECURITY/Empire#127]
**Empire Version**
- Empire 3.1.1 BC-Security Fork

**OS Information (Linux flavor, Python version)**
- OS: Debian 10.3
- Python: 3.7.3

**Describe the bug**
When creating a listener via the RESTful API and you do not provide a name for the listener, it will provide the following error;

{'error': 'UnboundLocalError("local variable \'listenerName\' referenced before assignment")'}

The listener is created just fine, which makes this response confusing (or at least not normal).

**To Reproduce**

Adjusted curl from documentation;
curl --insecure -i -H "Content-Type: application/json" https://localhost:1337/api/listeners/http?token=ks23jlvdki4fj1j23w39h0h0xcuwjrqilocxd6b5 -X POST -d '{"Host":"127.0.0.1:1234", "Port": "1234"}'

**Expected behavior**
{'success': 'listener http successfully started'}

**Screenshots**

**Additional context**

**Comment by Hubbl3** [comment]
@RedBulletTooling Thanks a lot for all the input. We recognize that the API is not really gracefully handling Empire  errors and some of the other errors. 

Are you okay with us closing your individual errors and creating a centralized error/thread for the API mishandling empire errors

**Comment by RedBulletTooling** [comment]
@Hubbl3 Sure! Will create more issues on that central thread if I stumble upon them.

**Comment by vinnybod** [comment]
This should no longer be the case in the new API https://bc-security.gitbook.io/empire-wiki/restful-api
