### ISSUE TITLE
[BUG] Incorrect API documentation

### ISSUE THREAD

**Issue by frosty1313** [BC-SECURITY/Empire#132]
**Empire Version**
- Empire 3.x

**OS Information (Linux flavor, Python version)**
- OS: N/A
- Python: N/A

**Describe the bug**
All four RESTful API end points listed at https://github.com/BC-SECURITY/Empire/wiki/RESTful-API#admin-functionality have incorrect handlers.  The handler should be: GET /api/admin/[endpoint].   

**To Reproduce**
1. Go to https://github.com/BC-SECURITY/Empire/wiki/RESTful-API
3. Scroll down to Admin Functionality

**Expected behavior**
Rewrite the Wiki page to correctly document the RESTful endpoint.  The curl example command is currently accurate.

**Screenshots**
N/A

**Additional context**
Sorry for not submitting a PR, couldn't figure out how to fork the Wiki git.

**Comment by Cx01N** [comment]
Thanks for the heads up. We ported the Wiki over from the original project and haven't had much time to update many of the pages. 

I am pretty sure that Github doesn't have a way to do PRs for the Wiki, but I can use this thread to track the API documentation updates. So, please feel free to let us know if you see any others.

**Comment by frosty1313** [comment]
@Cx01N no problem.  FWIW, I did a bit of Googling, it appears Github doesn't support PRs  on Wiki pages  https://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github.

I think the rest are correct and the examples all look correct.  Thanks for the quick response!

**Comment by frosty1313** [comment]
Spoke too soon.  For Create A Listener, a failure response is of the form:
{'error': 'failed to start listener [listener_name]'}.  

It's not documented for Generate Stager, but failure response is {'error': error message}

**Comment by Cx01N** [comment]
I'll get those fixed either later today or tomorrow. The feedback is extremely helpful, thank you!

**Comment by frosty1313** [comment]
@Cx01N - at some point I'll try and test every call, kind of just finding stuff as I implement a client and a project that uses it.
I think this will be for any endpoint that returns a dictionary of agent details like Get Agent By Name, sessionID should be session_id.  I encountered the error specifically in Get Current Agents.

**Comment by frosty1313** [comment]
There's several URIs in the below (found in the main empire file) that aren't on the Wiki.  I think I'll have time next week to write them up to save you the time.  (Also, there's a conspicuous TODO right above the banner.... more research)

#TODO: Update with new commads
####################################################################
#
# The Empire RESTful API.
#
# Adapted from http://blog.miguelgrinberg.com/post/designing-a-restful-api-with-python-and-flask
#   example code at https://gist.github.com/miguelgrinberg/5614326
#
#    Verb     URI                                                   Action
#    ----     ---                                                   ------
#    GET      http://localhost:1337/api/version                     return the current Empire version
#    GET      http://localhost:1337/api/map                         return list of all API routes
#    GET      http://localhost:1337/api/config                      return the current default config
#
#    GET      http://localhost:1337/api/stagers                     return all current stagers
#    GET      http://localhost:1337/api/stagers/X                   return the stager with name X
#    POST     http://localhost:1337/api/stagers                     generate a stager given supplied options (need to implement)
#
#    GET      http://localhost:1337/api/modules                     return all current modules
#    GET      http://localhost:1337/api/modules/<name>              return the module with the specified name
#    POST     http://localhost:1337/api/modules/<name>              execute the given module with the specified options
#    POST     http://localhost:1337/api/modules/search              searches modulesfor a passed term
#    POST     http://localhost:1337/api/modules/search/modulename   searches module names for a specific term
#    POST     http://localhost:1337/api/modules/search/description  searches module descriptions for a specific term
#    POST     http://localhost:1337/api/modules/search/comments     searches module comments for a specific term
#    POST     http://localhost:1337/api/modules/search/author       searches module authors for a specific term
#
#    GET      http://localhost:1337/api/listeners                   return all current listeners
#    GET      http://localhost:1337/api/listeners/Y                 return the listener with id Y
#    DELETE   http://localhost:1337/api/listeners/Y                 kills listener Y
#    GET      http://localhost:1337/api/listeners/types             returns a list of the loaded listeners that are available for use
#    GET      http://localhost:1337/api/listeners/options/Y         return listener options for Y
#    POST     http://localhost:1337/api/listeners/Y                 starts a new listener with the specified options
#
#    GET      http://localhost:1337/api/agents                      return all current agents
#    GET      http://localhost:1337/api/agents/stale                return all stale agents
#    DELETE   http://localhost:1337/api/agents/stale                removes stale agents from the database
#    DELETE   http://localhost:1337/api/agents/Y                    removes agent Y from the database
#    GET      http://localhost:1337/api/agents/Y                    return the agent with name Y
#    GET      http://localhost:1337/api/agents/Y/results            return tasking results for the agent with name Y
#    DELETE   http://localhost:1337/api/agents/Y/results            deletes the result buffer for agent Y
#    POST     http://localhost:1337/api/agents/Y/download           task agent Y to download a file
#    POST     http://localhost:1337/api/agents/Y/upload             task agent Y to upload a file
#    POST     http://localhost:1337/api/agents/Y/shell              task agent Y to execute a shell command
#    POST     http://localhost:1337/api/agents/Y/rename             rename agent Y
#    GET/POST http://localhost:1337/api/agents/Y/clear              clears the result buffer for agent Y
#    GET/POST http://localhost:1337/api/agents/Y/kill               kill agent Y
#
#    GET      http://localhost:1337/api/creds                       return stored credentials
#    POST     http://localhost:1337/api/creds                       add creds to the database
#
#    GET      http://localhost:1337/api/reporting                   return all logged events
#    GET      http://localhost:1337/api/reporting/agent/X           return all logged events for the given agent name X
#    GET      http://localhost:1337/api/reporting/type/Y            return all logged events of type Y (checkin, task, result, rename)
#    GET      http://localhost:1337/api/reporting/msg/Z             return all logged events matching message Z, wildcards accepted
#
#
#    POST     http://localhost:1337/api/admin/login                 retrieve the API token given the correct username and password
#    POST     http://localhost:1337/api/admin/logout                logout of current user account
#    GET      http://localhost:1337/api/admin/restart               restart the RESTful API
#    GET      http://localhost:1337/api/admin/shutdown              shutdown the RESTful API
#
#    GET      http://localhost:1337/api/users                       return all users from database
#    GET      http://localhost:1337/api/users/me                    return the user for the given token
#    POST     http://localhost:1337/api/users                       add a new user
#    PUT      http://localhost:1337/api/users/Y/disable             disable/enable user Y
#    PUT      http://localhost:1337/api/users/Y/updatepassword      update password for user Y
#
####################################################################

**Comment by Cx01N** [comment]
@frosty1313 I'm in the process of redoing the API wiki. It is really out-of-date since it was left mostly unchanged from the original project. I'll check back with you when it's complete and see if you would like to review it.

**Comment by mattaereal** [comment]
Hey @Cx01N, I'm currently working on documenting your API. I will be finishing it in a few days probably.

Feel free to reach out if you want to. A peer review from your side will be awesome.

**Comment by Cx01N** [comment]
@mattaereal That would be a huge help. I started updating the wiki, but got distracted with building some new Empire features. Thanks!

**Comment by mattaereal** [comment]
Is there a way where we can talk more synchronously? Maybe twitter? @mattaereal is mine, feel free to pm me over there!

**Comment by Cx01N** [comment]
@mattaereal sure, our discord would be the easiest way.
https://discord.com/invite/P8PZPyf

**Comment by mattaereal** [comment]
Done! will ping you over there!

**Comment by Cx01N** [comment]
@frosty1313 @mattaereal We updated the wiki to be editable through our GitHub and it will now auto-sync accepted merges to the wiki page. Here is a link to where they are located. https://github.com/BC-SECURITY/Empire/tree/master/wiki

**Comment by Cx01N** [comment]
All API documentation has been migrated to https://bc-security.gitbook.io/empire-wiki/
Pull requests for updates can be done through https://github.com/BC-SECURITY/empire-docs
