### ISSUE TITLE
[BUG] Pycrypto deprecation

### ISSUE THREAD

**Issue by blshkv** [BC-SECURITY/Empire#139]
**Empire Version**
 - Empire 3.1.1 (git)

**OS Information (Linux flavor, Python version)**
- OS:  Pentoo
- Python: Python3

**Describe the bug**
https://blog.sqreen.com/stop-using-pycrypto-use-pycryptodome/
pycrypto should not be used

**To Reproduce**
1. Go to '...' setup/
2. Inspect requirements*.txt
https://github.com/BC-SECURITY/Empire/blob/master/setup/requirements.txt#L18
4. See error the requirements

**Expected behavior**
do not use abandoned and vulnerable dependencies 

**Screenshots**
N/A

**Additional context**
N/A

**Comment by vinnybod** [comment]
As far as I can tell, we can just remove `pycrypto` from the requirements. I don't see it imported anywhere and there's an old message in the changelog about removing it.

https://github.com/BC-SECURITY/Empire/blob/e1e5c826f75dfc5be3a97b3160415898668cd5b4/changelog#L192

**Comment by vinnybod** [comment]
Looks like my previous comment was wrong, pycrypto does get used.

However, upon reading the [README for pycryptodome](https://github.com/Legrandin/pycryptodome):
>In this case, all modules are installed under the Crypto package.
One must avoid having both PyCrypto and PyCryptodome installed at the same time, as they will interfere with each other.
This option is therefore recommended only when you are sure that the whole application is deployed in a virtualenv

So this will get fixed in a future version of empire that is in the works which will encourage the use of a virtual environment

**Comment by blshkv** [comment]
no, that comment means that you should be able just to replace pycrypto with pycryptodome in most cases. FYI, I have done that and didn't encourage any obvious problems.

**Comment by vinnybod** [comment]
I'm not sure how you got that interpretation. The comment specifically says that you must AVOID having them both installed and that is is recommended to use only use the drop in replacement if you are in a virtual environment. So we will make the switch over after getting Empire instrumented with Pipenv.

**Comment by blshkv** [comment]
PyCryptodome is like a fork of PyCrypto, i.e. next version. That's why it has the same set of files (can't be installed in the same time) and the same API.

**Comment by blshkv** [comment]
https://pycryptodome.readthedocs.io/en/latest/src/vs_pycrypto.html

**Comment by vinnybod** [comment]
Yup, I read the blog post, which failed to outline the caveats, which is why I went to the README.  👍

**Comment by blshkv** [comment]
sorry, not an expert in python, just trying to help. And just found that "minor" issue too ;-) Shouldn't be very difficult to fix it

**Comment by vinnybod** [comment]
As I said before, this will get fixed. I'm working on a pretty big change that includes moving to Pipenv, so I'd rather not do the work twice.

**Comment by blshkv** [comment]
FYI, I'm porting your tool in Pentoo and virtual env is not an option. We install all packages as system-wide tools (as any other distro), and pycryto no longer available. Thus, this request ;-)
Thanks!

**Comment by vinnybod** [comment]
@blshkv I'll be sure to field your input as well as the Kali team before merging it in to make sure we are making things easier and not more difficult for you guys!

**Comment by Cx01N** [comment]
Dependency updated in 4.0
