### ISSUE TITLE
[FEATURE REQUEST] More obfuscation methods

### ISSUE THREAD

**Issue by Sa1riil** [BC-SECURITY/Empire#157]
**Is your feature request related to a problem? Please describe.**
It is really frunstranting when an AV is blocking an Empire module or a payload. I consider the below obfuscation methods will help us to use the scripts who are easily detected by AV's signatures based on strings.

**Describe the solution you'd like**
Hi, i was thinking that the currently available obfuscation methods in Empire are to few. Besides this, i was thining that will be really cool to have an option to create download obfuscated command.

**Describe alternatives you've considered**
 - For the obfuscation methods, i suggest to have available all methods with all suboptions from Invoke-Obfuscation script from https://github.com/danielbohannon/Invoke-Obfuscation. ( curently we have only encoding and token obfuscation, we lack obfuscation for powershell AST nodes, obfuscate the entire command as a string, converting the entire command to one-liner and Compress or the "Launcher technique" from invoke-obfuscation.
 - Besides the invoke-obfuscation, we can also implement Invoke-DOSfuscation (https://github.com/danielbohannon/Invoke-DOSfuscation) which " is a PowerShell v2.0+ compatible cmd.exe command obfuscation framework. (White paper: https://www.fireeye.com/blog/threat-research/2018/03/dosfuscation-exploring-obfuscation-and-detection-techniques.html)"
- I also consider that having an option to create automated obfuscated downloaders in memory/disk for our scripts, which can be pretty good automated via https://github.com/danielbohannon/Invoke-CradleCrafter.

**Additional context**

**Comment by Hubbl3** [comment]
> For the obfuscation methods, i suggest to have available all methods with all suboptions from Invoke-Obfuscation script from https://github.com/danielbohannon/Invoke-Obfuscation. ( curently we have only encoding and token obfuscation, we lack obfuscation for powershell AST nodes, obfuscate the entire command as a string, converting the entire command to one-liner and Compress or the "Launcher technique" from invoke-obfuscation.

I just double checked and you already have access to AST obfuscation via Invoke-Obfuscation. You just have to specify it like this `set ObfuscateCommand ast\all\1` if you want to use token obfuscation in addition you just have to comma separate it like this `set ObfuscateCommand ast\all\1,token\all\1`

As to adding in other projects for in terminal support that is not currently on our map. They already effectively work in conjunction with Empire and we have identified more pressing capability upgrades (such as the inclusion of Invoke-SocksProxy). If you would like to submit a PR to incorporate those projects we would be happy to include it after testing.

**Comment by Sa1riil** [comment]
Hey thank you for your response.
I will look forward for every new update of yours.
