### ISSUE TITLE
[BUG]Module is invalid

### ISSUE THREAD

**Issue by SYFLS** [BC-SECURITY/Empire#160]
**Empire Version**
- Empire 3.1.2

**OS Information (Linux flavor, Python version)**
- OS: KALI
- Python: 3.7

**Describe the bug**
The webcam module is invalid, the cmd module does not support Chinese,I hacked into a server in China, but due to language issues, I cannot download any files.

**To Reproduce**
1.usemodule collection/WebcamRecorder  execute
2.Unable to start the webcam, my webcam has no errors
3.No response
![1](https://user-images.githubusercontent.com/54468595/78872968-a621fc80-7a7c-11ea-9c2c-152406cbd314.PNG)
![2](https://user-images.githubusercontent.com/54468595/78872975-aa4e1a00-7a7c-11ea-8a37-b475c7f4fa10.PNG)

**Expected behavior**
I tried to rewrite the webcam module but it failed

**Screenshots**
N/A

**Additional context**
N/A.

**Comment by Hubbl3** [comment]
@SYFLS this appears to be a request supporting illegal activity which forces us to close the issue. 

Empire is only for research purposes and engagements in which the user has been given express permission for the activities being conducted.   

If this has been taken out of context please re-open the issue with clarification.
