### ISSUE TITLE
[BUG] apt install powershell-empire: 404 Not Found 

### ISSUE THREAD

**Issue by pawp81** [BC-SECURITY/Empire#162]
**Empire Version**
- Empire 3.1.4

**OS Information (Linux flavor, Python version)**
- OS: Kali Linux
- Python: 3.7.6

**Describe the bug**
I am getting following error when trying to install Empire with apt install powershell-empire.

Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
liblttng-ust-ctl4 liblttng-ust0 powershell python3-altgraph python3-dropbox python3-iptools python3-m2crypto python3-macholib python3-netifaces
python3-pydispatch python3-pyinstaller python3-pyminifier python3-xlutils python3-zlib-wrapper
Suggested packages:
python-altgraph-doc python-iptools-doc m2crypto-doc python-macholib-doc python-pydispatch-doc python-pyminifier-doc python-xlutils-doc
Recommended packages:
xar bomutils
The following NEW packages will be installed:
liblttng-ust-ctl4 liblttng-ust0 powershell powershell-empire python3-altgraph python3-dropbox python3-iptools python3-m2crypto python3-macholib
python3-netifaces python3-pydispatch python3-pyinstaller python3-pyminifier python3-xlutils python3-zlib-wrapper
0 upgraded, 15 newly installed, 0 to remove and 691 not upgraded.
Need to get 6,167 kB/66.7 MB of archives.
After this operation, 195 MB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Err:1 http://http.kali.org/kali kali-rolling/main amd64 powershell-empire all 3.1.2-0kali1
404 Not Found [IP: 192.99.200.113 80]
E: Failed to fetch http://http.kali.org/kali/pool/main/p/powershell-empire/powershell-empire_3.1.2-0kali1_all.deb 404 Not Found [IP: 192.99.200.113 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**To Reproduce**
run: "apt install powershell-empire"

**Expected behavior**
successful instalation of Empire on Kali Linux

**Screenshots**

**Additional context**
Kali Linux is running on Virtual Box VM.

**Comment by Cx01N** [comment]
@pawp81 It looks like you are trying to install 3.1.2. You didn't list which version of Kali you are working in so I will assume its 2020.1 since that is latest version. Try to run `sudo apt update` to get an updated repo and then `sudo apt install powershell-empire`. This should install Empire 3.1.4.
 
The latest version of Kali no long runs sudo by default so you'll have to run things with it for now on. Let me know if that works.

**Comment by pawp81** [comment]
Right. Thx. case closed.
