### ISSUE TITLE
[BUG] Mac install error

### ISSUE THREAD

**Issue by sh1va73** [BC-SECURITY/Empire#165]
**Empire Version**
Empire - 3.1.4 BC-Security Fork

**OS Information (Linux flavor, Python version)**
- OS: MacOSx Catalina
- Python: 3.7.7

**Describe the bug**
I installed Empire successfully on Mac.
When starting ./empire on Mac OSX I get an error: 

ModuleNotFoundError: No module named 'Crypto'

I did install pip3 install pycrypto successfully but the error stays.

**To Reproduce**
1. Go to Mac machine
2. open ./empire
3. See error

**Expected behavior**
error message 

**Screenshots**

**Additional context**

**Comment by sh1va73** [comment]
Temporary fix: in file /opt/Empire/lib/stagers/windows/backdoorLnkMacro.py
 I commented:
#from Crypto.Cipher import AES

Now Empire works on Mac, but did I break something with commenting this line?

**Comment by vinnybod** [comment]
We need to add a line to the readme to make this more explicit, but we are really only targeting Kali, Debian, and Ubuntu officially and those are the only ones we target in the install script. We provide the Docker builds as a convenience for if you want to run on a different OS. I personally use a Macbook Pro and run Empire in the Docker release builds. With that said, we will accept PRs that fix any OS specific bugs.

>Now Empire works on Mac, but did I break something with commenting this line?
You're breaking that specific stager, but that should be about it. If you pip install `pycrypto` or `pycryptodome`, I think you should be fixed.

**Comment by sh1va73** [comment]
Thanks for the feedback. I did try pip3 install pycrpyto and pycryptodome but the error was still there.  I will try a docker installion as well.

**Comment by vinnybod** [comment]
This is related to https://github.com/BC-SECURITY/Empire/issues/139 . If pycrypto is literally only used in this one stager, could it be that hard to replace the AES function its using with a different library? We already do AES in `encryption.py` using the cryptography library. @Cx01N

**Comment by Hubbl3** [comment]
@sh1va73  and @vinnybod  that suggested fix could work but I am closing the issue due to the fact that Mac is not one of our supported Operating Systems for installing Empire
