### ISSUE TITLE
[BUG] location of python  on Mac

### ISSUE THREAD

**Issue by sh1va73** [BC-SECURITY/Empire#166]
**Empire Version**
- Empire 3.1.4

**OS Information (Linux flavor, Python version)**
- OS: MacOSX Catalina
- Python: 3.7

**Describe the bug**
when generating a payload for Mac osx then the string has this location to python: /usr/bin/python3

But my Python3 on Mac is located at /usr/local/bin/python3, so I need to change this manually before executing.

**To Reproduce**
1. Go to MacOsX
2. start empire 
3. execute payload on target Mac
4. doesn't work because I need to change the location of Python3

**Expected behavior**
error because location of python3 is wrong in generated payload

**Screenshots**

**Additional context**

**Comment by Cx01N** [comment]
@sh1va73 Which stager and listener and you trying to use for this? Also, can you try to run this on Kali or Ubuntu so we can eliminate MacOS as a possible cause for your Empire server.

**Comment by sh1va73** [comment]
The stager was osx/applescript. I generated this on Mac and Kali to test.

**Comment by Cx01N** [comment]
@sh1va73 I am not able to reproduce the issue you described. Are you running your Empire server on Kali? And do you have Python 3 installed on your Mac? We currently don't support Python 2 launchers, so you will have to ensure your target has Python 3 installed.

Also, make sure you are running the AppleScript as a script and not as a bash command. I've made that mistake before.

![image](https://user-images.githubusercontent.com/20302208/79074800-393c7b80-7ca3-11ea-9084-f406d6dd8591.png)
![image](https://user-images.githubusercontent.com/20302208/79074791-304baa00-7ca3-11ea-86f9-237ec0827d15.png)

**Comment by sh1va73** [comment]
Yes I run it on Kali and I have python3 on my Mac. 
Seems your python3 on your Mac is located at /usr/bin.
Mine is located at /usr/local/bin.
Thats why I am having this issue. But I can change it manually.

**Comment by Cx01N** [comment]
Oh, that is really interesting.
@vinnybod where is yours located? You seem to run Mac the most out of all of us.

**Comment by vinnybod** [comment]
This is all going to depend on how python was installed by the user.
`/usr/bin` is where MacOS installs the python binaries. In Catalina, a binary for python3 was added here, but until the user installs the developer tools it is just a stub. My guess for why you would have it in `/usr/local/bin` is if you installed it via homebrew or some other method, which is completely valid. Does the generated stager need to reference it by its directory or can we just pipe to "python3" and hope for the best?

More info here:
https://apple.stackexchange.com/questions/376077/is-usr-bin-python3-provided-with-macos-catalina

**Comment by Cx01N** [comment]
@vinnybod I tried the pipe with just python3 and it seems to run fine. I will just have to run a few different test cases to make sure we aren't breaking functionality elsewhere.

@sh1va73 Does changing to `| python3 &` work on your setup?

**Comment by sh1va73** [comment]
> This is all going to depend on how python was installed by the user.
> `/usr/bin` is where MacOS installs the python binaries. In Catalina, a binary for python3 was added here, but until the user installs the developer tools it is just a stub. My guess for why you would have it in `/usr/local/bin` is if you installed it via homebrew or some other method, which is completely valid. Does the generated stager need to reference it by its directory or can we just pipe to "python3" and hope for the best?
> 
> More info here:
> https://apple.stackexchange.com/questions/376077/is-usr-bin-python3-provided-with-macos-catalina

Yes I have Python3 installed with Homebrew.

**Comment by sh1va73** [comment]
> @vinnybod I tried the pipe with just python3 and it seems to run fine. I will just have to run a few different test cases to make sure we aren't breaking functionality elsewhere.
> 
> @sh1va73 Does changing to `| python3 &` work on your setup?

On my side chasing to | python3 & did not help.

**Comment by Cx01N** [comment]
@sh1va73 I do not think there is going to be a sure way to fix this issue. However, I tested my updates on both the Xcode and Homebrew python 3 installs and was able to run without any issues.
Hopefully, this will be resolved once Mac has Python 3 as a default install.
