### ISSUE TITLE
[BUG] Random function name starts with a number is not supported on powershell 2

### ISSUE THREAD

**Issue by tyraniter** [BC-SECURITY/Empire#169]
**Empire Version**
- Empire 3.1

**OS Information (Linux flavor, Python version)**
- OS: ubuntu1904
- Python: 2/3

**Describe the bug**
Powershell version 2 does not support function name starts with number, so the random function name aliasing to Invoke-Empire & Mimikatz might cause an error when running on powershell 2.

**To Reproduce**
N/A

**Expected behavior**
Fix the first identifier of function name aliasing to Invoke-Empire & Mimikatz to letter during setup.

**Screenshots**
![image](https://user-images.githubusercontent.com/6822883/79104626-8868d600-7da1-11ea-983d-25dd216b9998.png)

**Additional context**
N/A

**Comment by Hubbl3** [comment]
@tyraniter submitted a pull request fixing the issue
