### ISSUE TITLE
Http_hop unexpected token in expression

### ISSUE THREAD

**Issue by roseaj** [BC-SECURITY/Empire#17]
## Empire Version
Empire 2.5
python3-hubble-1

## OS Information (Linux flavor, Python version)
2019.3
2018.4

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
`Http_hop` should establish a connection to the apache server and redirect to Empire to launch the stager. Instead, PowerShell is throwing an error that is preventing any connections. The error is an extra set of quotes: `$ser='$([TEXt.EnCODiNg]::UnIcODE.GetSTring([CoNVErt]::FRomBaSE64StRINg('aAB0AHQAcAA6AC8ALwAxADkAMgAuADEANgA4AC4AMQAzADkALgAxADIAOAA6ADgAMAA=')))';` 
which should be `$ser=$([TEXt.EnCODiNg]::UnIcODE.GetSTring([CoNVErt]::FRomBaSE64StRINg('aAB0AHQAcAA6AC8ALwAxADkAMgAuADEANgA4AC4AMQAzADkALgAxADIAOAA6ADgAMAA=')));`

An extra set of quotes and `b` prefix is included with the cookie.

## Screenshot of error, embedded text output, or Pastebin link to the error
Base64 error:
![Error](https://user-images.githubusercontent.com/20302208/68613763-57901800-0474-11ea-8d64-726959752061.PNG)

Base64 fix:
![Fix](https://user-images.githubusercontent.com/20302208/68613764-57901800-0474-11ea-8230-9adbf8e3ab27.PNG)

Prefix error:
![Error2](https://user-images.githubusercontent.com/20302208/68736056-7980bc00-0594-11ea-8a5a-38fd35f5a260.PNG)

Prefix fix:
![Fix 2](https://user-images.githubusercontent.com/20302208/68736059-7be31600-0594-11ea-9c7d-038afde44fee.PNG)

## Any additional information

**Comment by RedBulletTooling** [comment]
The exact same bug is present in the redirector listener. Having the same issue and the same fix applies. 

$ser='$([TeXT.EncODiNg]::UNiCoDE.GEtStRing([CONVerT]::FrOmBasE64StriNG('aAB0AHQAcAA6AC8ALwAxADAALgAwAC4AMwAuADUAOgA4ADAAOAAyAA==')))'
