### ISSUE TITLE
[BUG] full upgrade

### ISSUE THREAD

**Issue by sh1va73** [BC-SECURITY/Empire#175]
**Empire Version**
- Empire 3.1.5

**OS Information (Linux flavor, Python version)**
- OS: Kali 2020
- Python: 3.7

**Describe the bug**
Today I did **apt-get full-upgrade** on Kali and after that Empire was not working anymore.

**To Reproduce**
1. Go to Kali
2. apt-get update && apt-get full-upgrade
3. open ./empire

**Expected behavior**
before the upgrade all was working well, after upgrade I get error. 

**Screenshots**

**Additional context**
For now I reverted back to my previous installation.

**Comment by Cx01N** [comment]
@sh1va73 Please provide screenshots or paste in the error that you are receiving.

**Comment by sh1va73** [comment]
Already I reverted back, but it was mostly about missing dependencies. Tomorrow I will recreate the issue with a new apt-get full-upgrade and post all the errors here.

**Comment by sh1va73** [comment]
Today I did apt-get dist-upgrade. I got errors of missing dependencies , so i did ./install.sh
After that all missing dependencies got installed.
Then, I try to start Empire and I got this error:

Traceback (most recent call last):
  File "./empire", line 1533, in <module>
    main = empire.MainMenu(args=args)
  File "/opt/Empire/lib/common/empire.py", line 98, in __init__
    (self.isroot, self.installPath, self.ipWhiteList, self.ipBlackList, self.obfuscate, self.obfuscateCommand) = helpers.get_config('rootuser, install_path,ip_whitelist,ip_blacklist,obfuscate,obfuscate_command')
TypeError: cannot unpack non-iterable NoneType object

**Comment by sh1va73** [comment]
Fixed with running reset.sh.
All working fine now.
