### ISSUE TITLE
[BUG] Errors in install.sh

### ISSUE THREAD

**Issue by x1n5h3n** [BC-SECURITY/Empire#177]
**Empire Version**
- Empire 3.1.5
**OS Information (Linux flavor, Python version)**
- OS: Debian sid
- Python: 3.8.2

**Describe the bug**
Errors in  /setup/install.sh

**To Reproduce**
`sudo ./setup/install.sh`

**Expected behavior**
It should install empire without any errors

**Screenshots**
![image](https://user-images.githubusercontent.com/17899389/79623965-5a232780-810e-11ea-8672-fe5ecc2bb1b0.png)

**Additional context**
I manage to resolve errors by modifying the script.

**Comment by Cx01N** [comment]
@x1n5h3n Can you please post what error messages you received when running the install script?

**Comment by x1n5h3n** [comment]
[...]

Package python-m2crypto is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python-m2crypto' has no installation candidate
E: Unable to locate package python-pip

[...]

sudo: pip: command not found
Traceback (most recent call last):
  File "./setup_database.py", line 4, in <module>
    from builtins import input
ImportError: No module named builtins

**Comment by Cx01N** [comment]
@x1n5h3n The new build should address this issue but please let us know if you are still having issues.
