### ISSUE TITLE
[BUG] orphaned agent

### ISSUE THREAD

**Issue by sh1va73** [BC-SECURITY/Empire#179]
**Empire Version**
- Empire 3.1.7

**OS Information (Linux flavor, Python version)**
- OS: Kali 2020
- Python: 3.7

**Describe the bug**
After updating Kali and reinstalling Empire I get this error : 
(Empire: agents) > [!] Error from agents.handle_agent_data() for login/process.php from 10.0.2.15: b'ERROR: sessionID R\x1c\xc2\x98\xc3\xa7\x0c&+\xc3\x83 not in cache!'
[*] Orphaned agent from 10.0.2.15, signaling restaging

What does this error mean?

**To Reproduce**
1. Upgrade Kali and then Go to ./empire
2. open backdoor on target
3. orphaned agents error in Empire

**Expected behavior**
I expected the agent to run

**Screenshots**

**Additional context**

**Comment by sh1va73** [comment]
I fixed by recreating a new listener, new stager. Now it works. Still want to know what the error was.

**Comment by Hubbl3** [comment]
@sh1va73 that error is indicating that there was an agent attempting to connect to the server that wasn't recognized by Empire. So one of your VMs likely had an old agent running still from a previous install.
