### ISSUE TITLE
[FEATURE REQUEST] Allow unprivileged users to run Mimikatz commands

### ISSUE THREAD

**Issue by shelladdection** [BC-SECURITY/Empire#193]
**Is your feature request related to a problem? Please describe.**
in mimikatz.exe you can run things without admin user like: dpapi::masterkey
but in mimikatz module in Empire non privilege users can't run mimikatz commands

**Describe the solution you'd like**
please allow unprivileged users to use "/credentials/mimikatz/command" in order to use dpapi::masterkey

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by Cx01N** [comment]
We will look into this. Thank you.
FYI for the future, please provide a title for your feature requests or bug issues.
