### ISSUE TITLE
[FEATURE REQUEST] Create stager totaly in CLI

### ISSUE THREAD

**Issue by w1ld3r** [BC-SECURITY/Empire#199]
**Is your feature request related to a problem? Please describe.**
Unable to create stager without using the Empire shell.
It can be intersting for automated generation of payloads to don't have to use the Empire shell to create a stager.

**Describe the solution you'd like**
Be able to create listener in CLI or be able to create a stager in CLI with listener options.

**Describe alternatives you've considered**
For know to create a stager, we have to previously create a listener using the Empire shell

**Additional context**
None

**Comment by b4b857f6ee** [comment]
Yes, even with that i can succeed to export in /tmp/ the payload 
https://github.com/BC-SECURITY/Empire/wiki/Stagers#generate-stager

**Comment by Hubbl3** [comment]
@w1ld3r  This should be available now. It was fixed as part of this issue

https://github.com/BC-SECURITY/Empire/issues/198

if you want to do it. It would look like this `sudo ./empire -s multi/launcher -o Listener=http OutFile=launcher.txt` if you leave of the OutFile argument it will dump it to the CLI
