### ISSUE TITLE
[BUG] Onedrive listener fails to execute 

### ISSUE THREAD

**Issue by pawp81** [BC-SECURITY/Empire#201]
**Empire Version**
- Empire 3.2

**OS Information (Linux flavor, Python version)**
- OS: Kali Linux 2020.2
- Python: python 3.8.2

**Describe the bug**
After setting AuthCode and executing the listener, I receive following error:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/Empire/lib/common/helpers.py", line 993, in __run
    self.__run_backup()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/Empire//lib/listeners/onedrive.py", line 645, in start_server
    setup_folders()
  File "/opt/Empire//lib/listeners/onedrive.py", line 561, in setup_folders
    item_object = s.post("%s/drive/items/%s/children" % (base_url, base_object.json()['id']),
KeyError: 'id'
[!] Listener failed to start!
```

**To Reproduce**
1. Create an Azure AD as described here: https://www.bc-security.org/post/using-the-onedrive-listener-in-empire-3-1-3/
2. Set ClientID and ClientSecret
3. execute
4. Open in the webbrowser generated URL: "https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=.....
5. Copy the authorization code from the URL:
https://login.live.com/oauth20_desktop.srf?code=<copy this>&session_state
6 set AuthCode <copied authorization code>
7. execute

**Expected behavior**
Listener should start correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/47076035/81374931-a86d8a00-9100-11ea-9c88-c9aa295aa19a.png)

**Additional context**
My authorization code format seems to be different then the one you received when writting the instruction https://www.bc-security.org/post/using-the-onedrive-listener-in-empire-3-1-3/

**Comment by Cx01N** [comment]
@pawp81 It looks like Microsoft added a third account type into the mix. If you select `Accounts in my organizational structure directory (Any Azure AD directory and personal Microsoft accounts` it should fix the problem.

I just tested it and those changes should do the trick. Did it work for you?

![image](https://user-images.githubusercontent.com/20302208/81457738-302cb600-914c-11ea-9e21-c8a43b585942.png)

![image](https://user-images.githubusercontent.com/20302208/81457751-3cb10e80-914c-11ea-99c7-94385e8811e7.png)

**Comment by Cx01N** [comment]
@pawp81 Also, I just noticed that your Authcode is a bit too long. Make sure you are pulling only the short code that is found in our blog.
https://www.bc-security.org/post/using-the-onedrive-listener-in-empire-3-1-3/

**Comment by pawp81** [comment]
I selected the option "Accounts in any organization directory (Any Azure AD directory - Multitenant) and persona Microsoft accounts (e.q. Skype, Xbox) when provisioning the app.
Regarding AuthCode being too long. This is the AuthCode I am receiving back from Azure AD. :-)

Btw how the listener and stager should work? When listener is started shall it do anything with OneDrive of the user, which the AuthCode was generated for? How is the stager interacting with the listener and why is an AAD app needed?

**Comment by Cx01N** [comment]
@pawp81 From all the times I have tested the listener, I have never seen an Auth code like that. But I won't complain if it works.

As for how it works. It leverages the your onedrive account and places the files in there for the target machine to call back to which then is relayed to your Empire server. You can find the files in the Empire folder on your onedrive account. The information is encoded so it won't mean much unless you decode them first.

**Comment by pawp81** [comment]
Have you used Azure AD used by Office 365 tenant at the same time?

**Comment by Cx01N** [comment]
@pawp81 I'm going to close this issue, but feel free to reach out to us on the [Bloodhoundgang slack](https://bloodhoundgang.herokuapp.com/) in the psempire channel. We are happy to answer any questions there about implementation or troubleshooting.

**Comment by mashaGC** [comment]
@Cx01N Hi, same issue here. Code of different pattern, and the listener wont start
![empireOD](https://user-images.githubusercontent.com/20282505/137273671-2f37b757-8a55-46c5-8066-34bfecc76770.PNG)
:
