### ISSUE TITLE
[BUG] Keylogger

### ISSUE THREAD

**Issue by b4b857f6ee** [BC-SECURITY/Empire#217]
**Empire Version**
- Empire 3.2.2

**OS Information (Linux flavor, Python version)**
- OS: Kali
- Python: Python3

**Describe the bug**
Hello, yes the file keystrokes.txt now working in 3.2.2(he is create) but even before i only get maybe 1/200 stroke i can see on the file... is there is a specific configuration needed?
listener : http
Agents : windows/launcher_bat
module collection/keylogger

**To Reproduce**
1. create a listeners http
2. generate windows/launcher_bat
3. Drop it into Windows 7  or Windows 10
4. interact with the agent and usemodule collection/keylogger
5. run or execute this module and fin the result in keystrokes.txt

**Expected behavior**
Find all keystrokes used by the client

**Screenshots**
![image](https://user-images.githubusercontent.com/36012515/82883947-67200b80-9f43-11ea-81c2-77e7e44584ee.png)
![image](https://user-images.githubusercontent.com/36012515/82883979-6be4bf80-9f43-11ea-88af-9fa0a35f9b2e.png)

**Additional context**
N/A

**Comment by b4b857f6ee** [comment]
Sorry for my answer, i'm going to test it with the new release as soon as i can maybe next week.
I'm on the Empire v3.2.3 Ubuntu 18.04 i have python 3.8,3.7, 3.6,2.7 on the VM. 4CPU and 8G RAM.
All VM of course :).

**Comment by b4b857f6ee** [comment]
I test it one more time and same things :/.
![image](https://user-images.githubusercontent.com/36012515/85282090-6b304200-b48b-11ea-8d7d-c2a0ef5f69b5.png)

And i get only this : 

![image](https://user-images.githubusercontent.com/36012515/85282112-74b9aa00-b48b-11ea-89a3-9a7cf112dccf.png)


nb : my system doesn't have Internet access.

**Comment by Cx01N** [comment]
@b4b857f6ee I thought I fixed the issue in the last update where the keylogger was printing to the screen to the Empire CLI instead of the agents folder. Is there a file under downloads as well?

**Comment by b4b857f6ee** [comment]
@Cx01N Yes : 
![image](https://user-images.githubusercontent.com/36012515/85400584-ed3a6c80-b558-11ea-938c-62aba8248422.png)

But same.

**Comment by Cx01N** [comment]
@b4b857f6ee Sorry, I am having issues recreating the problem. Can you run --reset and respawn your agent in Empire 3.2.3?
I just want to rule out that the agent isn't running old code from another version. The agent should only write the keystrokes to the keystrokes.txt file as of version 3.2.2.

**Comment by b4b857f6ee** [comment]
Now i have nothing when i launch the keylogger module.

**Comment by Hubbl3** [comment]
@b4b857f6ee are you running this as a docker container? I just tested again and your screen shot is showing output from a version prior to 3.2.2. If you are using a docker volume it's a little tricky to upgrade. Also if you are using apt to install Empire then make sure you run `sudo apt update` prior to reinstalling

**Comment by b4b857f6ee** [comment]
No docker. Ok i will try to force update :)

**Comment by Cx01N** [comment]
@b4b857f6ee Were you able to fix the problem?

**Comment by Invoke-Mimikatz** [comment]
I still have problems with the keylogger missing some keystrokes:

![image](https://user-images.githubusercontent.com/57604669/87216549-6a5e3380-c306-11ea-8d6a-9de5b85a36c5.png)

**Comment by Cx01N** [comment]
@b4b857f6ee I was finally able to reproduce the issue. Apparently, it does not manifest itself on my VMs the same way it does on actual hardware. But, we made a change to the module which should fix some of the issues. You can also now choose the delay between key polls but it may come at the cost of CPU usage on the target.
