### ISSUE TITLE
[BUG] Lateral movement proxy agent

### ISSUE THREAD

**Issue by b4b857f6ee** [BC-SECURITY/Empire#231]
**Empire Version**
- Empire 3.2.3

**OS Information (Linux flavor, Python version)**
- OS: Kali
- Python: Python3

**Describe the bug**
Looking if we already have a module to do a lateral movement by using th 1 infected workstation as a proxy for the others workstation who don't have an internet access.

**To Reproduce**
Proxy agent connexion

**Expected behavior**
Control Workstation with an agent passing throught a redirection from another infected computer.

**Screenshots**

**Additional context**
N/A

**Comment by Hubbl3** [comment]
Yes we do have a redirector agent that allows for this. However, we don't currently have an SMB listener
