### ISSUE TITLE
[BUG] not create output when execute use listener http_foreign

### ISSUE THREAD

**Issue by ricko2991** [BC-SECURITY/Empire#250]
**Empire Version**
- Empire 3.2.3

**OS Information (Linux flavor, Python version)**
- OS: kali linux 2019.4
- Python: 3.8.3

**Describe the bug**
Hi, can you help me.
Well, i run empire listener use http_foreign
I use ngrok for listener. And 1 other listener use http which bind to my static
ip address.
When i execute the usestager windows/launcher_bat, the payload is not execute and give me message like this :
[!] Exception: name 'bypasses' is not defined

**To Reproduce**
[!] Exception: name 'bypasses' is not defined

**Expected behavior**
Create two listener. One for ngrok tunnel and one for forwaded to my ip address

**Screenshots**
![Screenshot (30)](https://user-images.githubusercontent.com/67855001/87217480-41788580-c37c-11ea-9292-496da3cbeade.png)

**Additional context**
N/A

**Comment by Cx01N** [comment]
@ricko2991 We recently pushed out an update that should fix the missing bypass dependency. We also added the option to choose your AMSI Bypass for your launcher. FYI, you will need to run `--reset` after updating to 3.3.0. Let us know if you keep seeing issues after updating.

**Comment by ricko2991** [comment]
Thank you.
