### ISSUE TITLE
[BUG] [!] facivon.ico requested by 127.0.0.1 with no routing packet

### ISSUE THREAD

**Issue by ricko2991** [BC-SECURITY/Empire#251]
**Empire Version**
- Empire 3.3.0

**OS Information (Linux flavor, Python version)**
- OS: kali
- Python: 3.8.3

**Describe the bug**
Well, when i create listener http_foreign for stager windows/launcher_bat. Then, give me alert like this when i open the link.
[!] facivon.ico requested by 127.0.0.1 with no routing packet

**To Reproduce**
[facivon.ico requested by 127.0.0.1 with no routing packet

**Expected behavior**
open the download link for backdoor when the backdoor is already done.

**Screenshots**
![Screenshot (31)](https://user-images.githubusercontent.com/67855001/87237648-80194900-c42b-11ea-9159-d4ab0dd9ac7f.png)

**Additional context**
N/A

**Comment by Hubbl3** [comment]
@ricko2991 can you provide the a screen shot with the options you are using for the foreign listener. Also are you getting this error on the Empire server you are building the payload on or the target Empire server that the stager should be calling back too?

**Comment by ricko2991** [comment]
This is my http_foreign options
![Screenshot (32)](https://user-images.githubusercontent.com/67855001/87239943-4c4c1c80-c447-11ea-94fb-d62c22a39b95.png)

I create 2 listeners. 1 for ngrok server and 1 for calling back to my localhost
![Screenshot (33)](https://user-images.githubusercontent.com/67855001/87239966-8a494080-c447-11ea-9b57-895a1c664591.png)

But then when i open ngrok server. Nothing on the screen. Unless the icon like this:
![Screenshot (34)](https://user-images.githubusercontent.com/67855001/87240001-edd36e00-c447-11ea-8452-c5ba4fe5de73.png)

**Comment by Hubbl3** [comment]
@ricko2991 That IIS7 image is what is supposed to come up when you access an agent without the proper authentication. The most likely issue is that your server key is mismatched to the listener you are trying to connect to. I will try and get a test set up in the next few days to see if I can reproduce the issue.

**Comment by ricko2991** [comment]
@Hubbl3 I try different way to use port forwading. But  always fail. I'm using meterpreter listener but fail and other different options didon't work in my case. How can i use port forwading and work with this?

**Comment by Cx01N** [comment]
@ricko2991 It will be easier for us to walk through your setup on [discord](https://discord.com/invite/P8PZPyf). We aren't seeing an issue at the moment, but that may be because of different configurations. Please jump on and we can walk through the issue you are having, just message myself or @Hubbl3.
Thanks!
