### ISSUE TITLE
[BUG] The agent arrives and immediately "dies"

### ISSUE THREAD

**Issue by metasploitmsf** [BC-SECURITY/Empire#258]
**Empire Version**
- Empire 3.3

**OS Information (Linux flavor, Python version)**
- OS: Ubuntu 18.04 ; 20.04
- Python: Python3.8.2

**Describe the bug**
1) pip3 --version
pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)
2) Listener http(port 443)
3) Stager multi/launcher
The agent arrives and immediately "dies", but the powershell process continues to run on the target machine.

**To Reproduce**

**Expected behavior**

**Screenshots**
<img width="856" alt="Screenshot empire" src="https://user-images.githubusercontent.com/56875699/87318278-fb870300-c4dc-11ea-8e69-2c24f6ce9dbc.png">

<img width="988" alt="Screenshot target machine" src="https://user-images.githubusercontent.com/56875699/87318329-09d51f00-c4dd-11ea-923e-99eca9b01571.png">

**Additional context**
Target machine win7 without AV

**Comment by Hubbl3** [comment]
@metasploitmsf is it fully staging? or just stage 0 checking in? If it's not fully staging then try running ```cert.sh``` from ```./Empire/setup```.

Otherwise try running with all AV disabled on the target machine and see if it works then. Your AV might be killing the agent

**Comment by metasploitmsf** [comment]
if I use Empire on Kali on a VPS (different hosters), then the error is...
<img width="591" alt="bug from kali on vps" src="https://user-images.githubusercontent.com/56875699/89102673-60d56200-d3c0-11ea-9e41-3e5c1ec0026b.png">

if I use Empire  Ubuntu 18.04,20.04 (different hosters), then the agent comes and immediately "dies"..
<img width="388" alt="bug from ubuntu(18 04,20 04) on vps" src="https://user-images.githubusercontent.com/56875699/89102689-76e32280-d3c0-11ea-87bf-63962846b448.png">

But if I use Empire on  Kali on my personal computer, then the empire works fine, the agents live.
  why is Empire  not working on VPS?
p.s i'am tested diffrent ports for multi/launcher stager.

**Comment by Cx01N** [comment]
@metasploitmsf It looks like your database is out-of-date since the functions table was added in a recent update. Try to run ```sudo ./empire --reset``` to reset it.
