### ISSUE TITLE
[BUG]Error generating launcher: generate_launcher() got an unexpected keyword argument 'ETWBypass'

### ISSUE THREAD

**Issue by J0knK3ats** [BC-SECURITY/Empire#272]
**Empire Version**
- Empire 3.3.2

**OS Information (Linux flavor, Python version)**
- OS: kali 2020.3
- Python: python3.8.5

**Describe the bug**
cann't launcher a stager 

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/46599554/89514776-ddc16b00-d808-11ea-903f-c75c4adf1f5e.png)
![image](https://user-images.githubusercontent.com/46599554/89515263-70620a00-d809-11ea-9f12-95169eac9a85.png)
after execute ,it will go back to 
![image](https://user-images.githubusercontent.com/46599554/89515345-8ec80580-d809-11ea-904b-2a07e44c30f7.png)

**Additional context**

**Comment by Cx01N** [comment]
@J0knK3ats Thanks for catching this! If you want to check it out, I pushed a PR to fix this issue.
