### ISSUE TITLE
[BUG] Discord Invite invalid

### ISSUE THREAD

**Issue by jeffmcjunkin** [BC-SECURITY/Empire#276]
**Empire Version**
- Empire 3.5

**OS Information (Linux flavor, Python version)**
- OS: Any
- Python: Any

**Describe the bug**
The Discord link added in 1390587 is no longer valid.

**To Reproduce**

1. Click on the Discord invite link from the above commit.
2. See 1390587#commitcomment-41346820

**Expected behavior**
Working invite to BC-SECURITY's Discord.

# Screenshots
Screenshot in my commit comment above.

**Additional context**
This section apparently has to be here for the bug not to be auto-closed.

**Comment by Cx01N** [comment]
@jeffmcjunkin You are correct the old discord link in v3.3.0 is no longer valid. It was updated a few patches ago in the [readme](https://github.com/BC-SECURITY/Empire/blob/master/README.md) and should still work. If you are having issues this [discord link](https://discord.com/invite/P8PZPyf) should work also.
