### ISSUE TITLE
[FEATURE REQUEST] Saving Empire powershell module output to a file

### ISSUE THREAD

**Issue by pawp81** [BC-SECURITY/Empire#289]
**Is your feature request related to a problem? Please describe.**
When running PowerShell module such as: privesc/powerup/allchecks I would like to save output to a file on attackers machine (or victims then I will download it) to review it offline.

**Describe the solution you'd like**
I would like export option of the output of privesc/powerup/allchecks to the .txt file either on attackers machine, or at least on victims machine.

**Describe alternatives you've considered**
Right now I need to review long output of the module in the terminal session

**Additional context**
I am using Empire 3.3.4

**Comment by Cx01N** [comment]
@pawp81 Have you tried looking at the logs in the download folder? The commands and outputs are saved for each agent and this seems to mostly meet the goal you want at least. If not, we could see about dropping a file to disk, but we try to avoid that at all costs obviously.

**Comment by Cx01N** [comment]
@pawp81 I forgot to add, that [Starkiller ](https://github.com/BC-SECURITY/Starkiller) has a reporting tab that displays all of the commands and responses as well.

**Comment by pawp81** [comment]
OK. I didn't know about downloads/agent_name/agent.log log file. Thank you.
