### ISSUE TITLE
[BUG] privesc/ms16-032 does not launch a new agent

### ISSUE THREAD

**Issue by znre** [BC-SECURITY/Empire#291]
**Empire Version**
- Empire 3.3.4

**OS Information (Linux flavor, Python version)**
- OS: Kali GNU/Linux Rolling x86_64
- Python: Python 3.8.5

**Describe the bug**
When executing the "privesc/ms16-032" module (in my case, the target is hackthebox Optimum), the response is that it is successful and a SYSTEM shell has spawned, but nothing happening. There are no new agents that have spawned that has SYSTEM privileges.

**To Reproduce**
Steps to reproduce the behavior on an instance where you have a low-privileged agent:

1. usemodule privesc/ms16-032
2. execute
3. See behavior on the screenshots below

**Expected behavior**
A new agent will spawn after the successful execution of the privesc module.

**Screenshots**
![image](https://user-images.githubusercontent.com/70197545/91667182-23860080-eb35-11ea-94be-e5a5431fd093.png)

**Additional context**
None

**Comment by Cx01N** [comment]
I fixed the issue, check out https://github.com/BC-SECURITY/Empire/pull/292 and just confirm that it works on your machine too.

**Comment by znre** [comment]
It worked. Thank you so much!
