### ISSUE TITLE
[BUG] Steal_token crashes agent

### ISSUE THREAD

**Issue by n8tr0n** [BC-SECURITY/Empire#297]
**Empire Version**
- Empire 3.3.4

**OS Information (Linux flavor, Python version)**
- OS: Kali Linux
- Python: 3.8.5

**Describe the bug**
After using credentials\mimikatz\pth and then steal_token, the agent dies.

**To Reproduce**
1. Dump SAM
2. usemodule credentials\mimikatz\pth
3. steal_token
4. Agent dies
5. Expected behavior
6. I expect to be able to utilize the token to access targets that they stolen token has access to

**A clear and concise description of what you expected to happen.**
I expect to be able to access targets in the context of the stolen token

**Screenshots**

**Additional context**

**Comment by Cx01N** [comment]
Steal_token (or Invoke-TokenManipulation) is having issues overall with newer Win 10 systems. It works on older builds, but I'm guessing that there will have to be some changes since it is crashing processes.

**Comment by mlgualtieri** [comment]
Also ran in to this today running an agent on a Windows Server 2016 VM, so it seems like this might not be limited to Win10.

**Comment by mpgn** [comment]
Ran also on this issue with a Windows 10

**Comment by Hubbl3** [comment]
There is now a pull request in that fixes this issue. There was a buffer size issue in the powershell code.

**Comment by mpgn** [comment]
@Hubbl3 just tested your PR, can confirm it's working perfectly 💯
