### ISSUE TITLE
Exception Error

### ISSUE THREAD

**Issue by rossiV1** [BC-SECURITY/Empire#30]
## Empire Version
[Version] 3.0 BC-Security Fork

## OS Information (Linux flavor, Python version)
Ubuntu 18.04, Python 3.6.9

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
`usestager windows/macro` when execute should output a macro file

but when execute above, it shows error `Exception: module 'string' has no attribute 'letters' ` and return to main empire page

## Screenshot of error, embedded text output, or Pastebin link to the error
![empire1](https://user-images.githubusercontent.com/37831634/71395712-16357f80-2652-11ea-8220-62b80796f27f.png)
![Screenshot from 2019-12-24 13-15-09](https://user-images.githubusercontent.com/37831634/71395724-2e0d0380-2652-11ea-9445-21657b99e994.png)

## Any additional information
I just updated empire from the previous version to this new version. the previous version works well when using the macro stager module.

**Comment by rossiV1** [comment]
i found error when uploading a file using to agent that is connected when using the command`upload`

Error is: `[!] Exception: 'utf-8' codec can't decode byte 0x90 in position 2: invalid start byte
`

**Comment by Cx01N** [comment]
We added the updates to [3.0-bug-fixes](https://github.com/BC-SECURITY/Empire/tree/3.0-bug-fixes) for testing before rolling it out. We aren't seeing the issues anymore, so let us know if it still present.

**Comment by Invoke-Mimikatz** [comment]
I'm not sure if this belongs in a new issue or not, but it seems similar enough to the ones above.  The theme seems to be a difference between string and byte array[] and how Empire handles them.

<img width="925" alt="str_byte" src="https://user-images.githubusercontent.com/57604669/71433077-80761080-26a2-11ea-909f-aa672a988d72.png">

**Comment by rossiV1** [comment]
hi again. i tried the new update with a fresh install server. cannot load empire due to this error

> root@server:/opt/Empire# ./empire 
Traceback (most recent call last):
  File "./empire", line 1424, in <module>
    main = empire.MainMenu(args=args)
  File "/opt/Empire/lib/common/empire.py", line 97, in __init__
    (self.isroot, self.installPath, self.ipWhiteList, self.ipBlackList, self.obfuscate, self.obfuscateCommand) = helpers.get_config('rootuser, install_path,ip_whitelist,ip_blacklist,obfuscate,obfuscate_command')
  File "/opt/Empire/lib/common/helpers.py", line 606, in get_config
    cur.execute("ALTER TABLE config ADD COLUMN %s BLOB" % (field))
sqlite3.OperationalError: no such table: config
root@server:/opt/Empire# 

detail of server is:
fresh install ubuntu 18.04
python version: 3.6.9 and 2.7.17

i tried both `./empire` and `python2 ./empire` but got the error as above

**Comment by rossiV1** [comment]
> hi again. i tried the new update with a fresh install server. cannot load empire due to this error
> 
> > root@server:/opt/Empire# ./empire
> > Traceback (most recent call last):
> > File "./empire", line 1424, in 
> > main = empire.MainMenu(args=args)
> > File "/opt/Empire/lib/common/empire.py", line 97, in **init**
> > (self.isroot, self.installPath, self.ipWhiteList, self.ipBlackList, self.obfuscate, self.obfuscateCommand) = helpers.get_config('rootuser, install_path,ip_whitelist,ip_blacklist,obfuscate,obfuscate_command')
> > File "/opt/Empire/lib/common/helpers.py", line 606, in get_config
> > cur.execute("ALTER TABLE config ADD COLUMN %s BLOB" % (field))
> > sqlite3.OperationalError: no such table: config
> > root@server:/opt/Empire#
> 
> detail of server is:
> fresh install ubuntu 18.04
> python version: 3.6.9 and 2.7.17
> 
> i tried both `./empire` and `python2 ./empire` but got the error as above

sorry, i fixed this by using the command `./setup/reset.sh` and install all the other dependencies.

**Comment by rossiV1** [comment]
> We added the updates to [3.0-bug-fixes](https://github.com/BC-SECURITY/Empire/tree/3.0-bug-fixes) for testing before rolling it out. We aren't seeing the issues anymore, so let us know if it still present.

hello. i am still seing the bug when using the windows/macro. 

currently using fresh install ubuntu 18.04

**Comment by rossiV1** [comment]
and the error when upload file is still there.

**Comment by Cx01N** [comment]
> and the error when upload file is still there.

You may still be on the 3.0 branch instead of the hotfixes branch. If you run the following commands from the Empire folder.
```
git checkout 3.0-bug-fixes
git pull
./setup/reset.sh
```

Which version does it say you are running?

**Comment by rossiV1** [comment]
> ./setup/reset.sh

ahhh sorry. i did not pull the correct branch. thank you for the info above

**Comment by rossiV1** [comment]
> i found error when uploading a file using to agent that is connected when using the command`upload`
> 
> Error is: `[!] Exception: 'utf-8' codec can't decode byte 0x90 in position 2: invalid start byte `

i realised the error will come when trying to upload a file that is bigger in size. when i upload a normal txt file, it can manage to upload. 
but when i try to upload a exe file, it will show this error `[!] Exception: 'utf-8' codec can't decode byte 0x90 in position 2: invalid start byte`

**Comment by Cx01N** [comment]
> > i found error when uploading a file using to agent that is connected when using the command`upload`
> > Error is: `[!] Exception: 'utf-8' codec can't decode byte 0x90 in position 2: invalid start byte `
> 
> i realised the error will come when trying to upload a file that is bigger in size. when i upload a normal txt file, it can manage to upload.
> but when i try to upload a exe file, it will show this error `[!] Exception: 'utf-8' codec can't decode byte 0x90 in position 2: invalid start byte`

The check for file sizes larger than 1 MB should now work on the 3.0-bug-fixes branch and you will receive this message when trying to upload large files.
`[!] File size is too large. Upload limit is 1MB.`

Thank you for working through this issue with us.
