### ISSUE TITLE
Unable to print creds saved by mimikatz

### ISSUE THREAD

**Issue by bsrinivasguptha** [BC-SECURITY/Empire#31]
## Empire Version
3.0

## OS Information (Linux flavor, Python version)
Linux kali 5.3.0-kali2-amd64 #1 SMP Debian 5.3.9-3kali1 (2019-11-20) x86_64 GNU/Linux
Python 3.7.5

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
Below are the series of commands executed:
```
listeners
uselistener http
set Port 80
execute
launcher powershell http
interact <AGENT-1>
bypassuac http
interact <AGENT-2>
mimikatz
creds
```

## Screenshot of error, embedded text output, or Pastebin link to the error
```
(Empire: agents) > creds
Credentials:
  CredID  CredType   Domain                   UserName         Host             Password
[!] Exception: unsupported format string passed to bytes.__format__
```

## Any additional information
None

**Comment by Hubbl3** [comment]
@srinivasguptha we will address this shortly but this is a bug caused by the 2.7 to 3.x conversion. If you run it in 2.7 the error should go away as temporary work around

**Comment by Invoke-Mimikatz** [comment]
Running Empire 3.0.1 (bugfix branch) in python2 fails with the error below:

<img width="917" alt="image" src="https://user-images.githubusercontent.com/57604669/71450426-371bd480-2727-11ea-9cb5-f85d90a92d2e.png">

Running Python version 2.7.17

**Comment by Hubbl3** [comment]
@Invoke-Mimikatz  you need to run reset.sh when switching between versions. The pickle protocol doesn't seem to be version agnostic

**Comment by Cx01N** [comment]
> Running Empire 3.0.1 (bugfix branch) in python2 fails with the error below:
> 
> <img alt="image" width="917" src="https://user-images.githubusercontent.com/57604669/71450426-371bd480-2727-11ea-9cb5-f85d90a92d2e.png">
> 
> Running Python version 2.7.17

You will have to run reset.sh if you switch between python 2 and 3. We currently don't have a way to switch without clearing the database first.

**Comment by Hubbl3** [comment]
@bsrinivasguptha  and @Invoke-Mimikatz . I just pushed a commit to the 3.0-bug-fixes branch that fixes the issue
