### ISSUE TITLE
[BUG] PowerShell process appears when i run a macro for word ( office 2019)

### ISSUE THREAD

**Issue by y1n07** [BC-SECURITY/Empire#317]
## Empire Version

- Empire 3.3.4

## OS Information (Linux flavor, Python version)

- OS: parrot os
- Python: 3.8.5

## Describe the bug

a PowerShell process is shown when running the VBA for a few seconds while i execute a macro for windows ( in this case) 

## To Reproduce

1. i created the macro for windows ( with the options of amsi bypass 1 & 2 , obfuscate and base64 encoding) 
2.  i put the macro on a document of word of my virtual machine who has w10 ( i'm using office 2019) 
3. once i executed the macro i saw a ps process when running VBA for a 1-2 seconds then it disappear when i open & close the doc..
4. finally i receive the connection back to my vm of parrot ( and everything related to the agent works perfectly) 
i can execute commands and it works well ... 

## Expected behavior

i would like to know if there's the possibility to hide this ps process when i'm playing around with this tool on my vms 

## Additional context

by the way another tool called macro_pack has the same '''problem''

" Also, I'm sure you've noticed that a PowerShell process is shown when running the VBA for a few seconds. You can use something like this to hide it better.

lxgbestnqlalihesfm.Run Full_Command, 2

The lxgbestnqlalihesfm variable is the obfuscated variable name for the WScript Shell Object. If yours still says Shell.
Run, then copy the variable "Dim” (variable name) As Object. It should be obvious what the variable should be when you look at the obfuscated code. The 2 in the command above minimizes the PowerShell process when it starts.

Let's give it a try by running the VBA from the macro builder inside Word and then try again using the "Enable Content" button. Hold on, it's working when I run the macro manually. But it doesn't work when I "Enable Content". Well, if you look at the code, AutoOpen is a Private Sub. Get rid of Private, and you're good to go! "

PS: i will add the macro used in my tests with the vms 
PS2:  what command i have to use in this case? i have WScript shell object but it's not obfuscated and i don't have the variable Dim..

thanks 
[macro_test.txt](https://github.com/BC-SECURITY/Empire/files/5252293/macro_test.txt)

**Comment by y1n07** [comment]
halp ;_;

**Comment by Cx01N** [comment]
Please do not delete section headers in the future. I added the screenshot section back in and reopened the issue.

**Comment by Hubbl3** [comment]
@y1n07 this is not a bug. It's a condition of the launcher. There are stealthier options out there but we don't provide obfuscation support. It's simply just too often for any one method to work. If you have found a method that you like and would like help on where you could modify the Empire code to implement it please join the discord and ask there.

As this is not actually a bug I am closing the issue
