### ISSUE TITLE
[BUG] Error processing result packet from 'agent ID' : a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by jtheanalytica** [BC-SECURITY/Empire#331]
__Note:__ Please fill out all sections (if applicable) and do not delete the below section headers, otherwise the bot will close the issue.

## Empire Version
- Empire 3.4.0

## OS Information (Linux flavor, Python version)
- OS: 
**Oracle VM Virtual Box
Host: Windows 10 pro
VM1: Kali 2020.3
VM2: macOS Catalina Version 10.15.5**

- Python: 
**Kali:**
python3 -V
Python 3.8.6

python -V
Python 2.7.18

**macOS:** 
pyhton3 -V
3.8.2

python -V
2.7.16

## Describe the bug
When I use the Empire module: usemodule collection/osx/prompt 

I get the following error:
[!] Error processing result packet from PWS7R0PW : a bytes-like object is required, not 'str'

## To Reproduce

1. On Kali:
root@kali:~# cd /opt/Empire/
root@kali:/opt/Empire# ./empire 

2. To create stager:
(Empire) > usestager  osx/applescript
(Empire: stager/osx/applescript) > execute

3. Go to the macOS and copy the script and compile into executable. Then save it to disk and then double click the executable file.

4. Go back to Empire on Kali. You'll see a new agent was created (see snapshot) 

(Empire) > 
[*] Sending PYTHON stager (stage 1) to 10.0.2.15
[*] Agent PWS7R0PW from 10.0.2.15 posted valid Python PUB key
[*] New agent PWS7R0PW checked in
[+] Initial agent PWS7R0PW from 10.0.2.15 now active (Slack)
[*] Sending agent (stage 2) to PWS7R0PW at 10.0.2.15
[!] strip_python_comments is deprecated and should not be used

5. (Empire) > agents

[*] Active agents:

 Name     La Internal IP     Machine Name      Username                Process            PID    Delay    Last Seen            Listener
 ----     -- -----------     ------------      --------                -------            ---    -----    ---------            ----------------
 PWS7R0PW py 10.0.2.15
      iamrichs-iMac.loc iamrich                 /Library/Developer 575    5/0.0    2020-10-08 11:44:24  httpAll         

(Empire: agents) > interact PWS7R0PW
(Empire: PWS7R0PW) > sysinfo
[*] Tasked PWS7R0PW to run TASK_SYSINFO
[*] Agent PWS7R0PW tasked with task ID 1
(Empire: PWS7R0PW) > 
Listener:         http://10.0.2.47:8080
Internal IP:      10.0.2.15

Username:         \iamrich
Hostname:         iamrichs-iMac.local
OS:               Darwin,iamrichs-iMac.local,19.5.0,Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64,x86_64
High Integrity:   0
Process Name:     /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/Resources/Python.app/Contents/MacOS/Python
Process ID:       575
Language:         python
Language Version: 3.8

6.
(Empire: PWS7R0PW) > usemodule collection/osx/prompt 
(Empire: python/collection/osx/prompt) > 

(Empire: python/collection/osx/prompt) > execute
[>] Module is not opsec safe, run? [y/N] y
[*] Tasked PWS7R0PW to run TASK_CMD_WAIT
[*] Agent PWS7R0PW tasked with task ID 2
[*] Tasked agent PWS7R0PW to run module python/collection/osx/prompt

7.
Go to macOS VM and you'll see a pop window prompting for App store password (see snapshot)

8. I provide the password and click ok.

9. Go to Empire on Kali and I get the following error:
(Empire: python/collection/osx/prompt) > [!] Error processing result packet from PWS7R0PW : a bytes-like object is required, not 'str'

## Expected behavior
I should get the password - I provided in the App store prompt windows - in plain text.

## Screenshots
![Empire Git 01](https://user-images.githubusercontent.com/57214362/95483937-82426380-0998-11eb-8f52-c57ef783d2a7.png)
![Empire Git 02](https://user-images.githubusercontent.com/57214362/95483963-8a020800-0998-11eb-96fc-373465fcae68.png)
![Empire Git 03](https://user-images.githubusercontent.com/57214362/95484027-a140f580-0998-11eb-8b94-1cfa38d25263.png)

**Comment by jtheanalytica** [comment]
Hi.
Any one could help please?

**Comment by Cx01N** [comment]
This PR should fix it, can you test it out and make sure it works on your end too?
https://github.com/BC-SECURITY/Empire/pull/396

**Comment by jtheanalytica** [comment]
Hi @Cx01N .
Thank you.
But I still am getting the same issue:
(Empire: python/collection/osx/prompt) > [!] Error processing result packet from 73O2V67F : a bytes-like object is required, not 'str'

I installed empire using:
apt install powershell-empire

And the version now is:
3.6.0

![Empire3 6 0](https://user-images.githubusercontent.com/57214362/99147137-1fbf4000-2687-11eb-833d-a944a53f7aa8.png)

Ciao

**Comment by Cx01N** [comment]
You’ll have to install Empire through git clone and checkout the branch to test it. This change isn’t pushed to the Kali repo yet.

**Comment by jtheanalytica** [comment]
Thank you @Anthony.

Just to be on the same page, I'll be using the following commands:
```
git clone https://github.com/BC-SECURITY/Empire.git
cd Empire
./setup/install.sh
```

Please confirm, or suggest otherwise.

Also please explain how to **checkout the branch to test it.**

Thanks.

**Comment by Cx01N** [comment]
You'll want to run:

```
git clone https://github.com/BC-SECURITY/Empire.git
cd Empire
git checkout python_prompt_fix
./setup/install.sh
sudo ./empire --reset
sudo ./empire
```

FYI, I'm @Cx01N so the notifications go to the right person next time ;)

**Comment by jtheanalytica** [comment]
Thank you, @Cx01N
Surething! Lemme try that and will get back with the results.

Ciao

**Comment by jtheanalytica** [comment]
Hey @Cx01N 
Works like a charm.
Thanks

Anything you'd like me to do on my end before closing this?
Ciao

**Comment by Cx01N** [comment]
Should be good to go, thanks.
I'll get it added to the new release.
