### ISSUE TITLE
ModuleNotFoundError: No module named 'pydispatch' (and more)

### ISSUE THREAD

**Issue by CoffeeNData** [BC-SECURITY/Empire#34]
## Empire Version
3.0

## OS Information (Linux flavor, Python version)
Kali Linux, Python 3.7.5 and Python 2.7.17

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

I've just installed Empire, which gave me a few errors in the installation script. I runt it again and prompted no problems. The thing comes when I try to execute `empire`. I have tried to execute `./empire`,  `python empire`, `python2 empire` and `python3 empire`

## Screenshot of error, embedded text output, or Pastebin link to the error
`./empire`
`Traceback (most recent call last):
  File "./empire", line 14, in <module>
    from lib.common import empire, helpers
  File "/root/Empire/lib/common/empire.py", line 19, in <module>
    from pydispatch import dispatcher
ModuleNotFoundError: No module named 'pydispatch'`

`python empire`
`Traceback (most recent call last):
  File "empire", line 1424, in <module>
    main = empire.MainMenu(args=args)
  File "/root/Empire/lib/common/empire.py", line 97, in __init__
    (self.isroot, self.installPath, self.ipWhiteList, self.ipBlackList, self.obfuscate, self.obfuscateCommand) = helpers.get_config('rootuser, install_path,ip_whitelist,ip_blacklist,obfuscate,obfuscate_command')
TypeError: 'NoneType' object is not iterable`
#### (`python2 empire` prompted the same issue, so I just omitted it.)

`python3 empire`
`Traceback (most recent call last):
  File "empire", line 14, in <module>
    from lib.common import empire, helpers
  File "/root/Empire/lib/common/empire.py", line 19, in <module>
    from pydispatch import dispatcher
ModuleNotFoundError: No module named 'pydispatch'`
## Any additional information
I've searched on Google just to ensure it was not Python's problem and I've seen some other issues on the previous versions.

**Comment by Hubbl3** [comment]
From `./Empire/setup` try running `pip3 install -r requirements.txt`

**Comment by CoffeeNData** [comment]
> From `./Empire/setup` try running `pip3 install -r requirements.txt`

Thanks. It prompted another error (which I can't remember), but it solved running `./Empire/setup/reset.sh`
