### ISSUE TITLE
[BUG] Preobfuscating not working [!] Exception: [Errno 2] No such file or directory: '/empire//data/misc/Obfuscated.ps1'

### ISSUE THREAD

**Issue by AlphaBaller** [BC-SECURITY/Empire#345]
__Note:__ Please fill out all sections (if applicable) and do not delete the below section headers, otherwise the bot will close the issue.

## Empire Version
- Empire 3.5

## OS Information (Linux flavor, Python version)
- OS: Ubuntu 20.04 LTS
- Python: Docker Image

## Describe the bug
Command Preobfuscating Error [!] Exception: [Errno 2] No such file or directory: '/empire//data/misc/Obfuscated.ps1'

## To Reproduce
Jump in Empire Container (docker run -it -v /empire:/chain  -p 443:443 --rm bcsecurity/empire /bin/bash)
Start Preobfuscate
Error: [!] Exception: [Errno 2] No such file or directory: '/empire//data/misc/Obfuscated.ps1'

## Expected behavior
Obfuscated powershell

**Comment by Cx01N** [comment]
At initial glance, it looks like the [obfuscated_module_directory](https://github.com/BC-SECURITY/Empire/tree/master/data/obfuscated_module_source) is being committed from the apt install in kali and the docker. I will look into it more tonight and see if we can come up with a quick solution.

**Comment by HackProAIT** [comment]
still getting same issue after Fix and Update

**Comment by Cx01N** [comment]
@HackProAIT Thank you for the heads up, I opened an issue on the Kali repo since their formatting is slightly different and that appears to be the root cause. All other builds appear to be working fine, so give the docker or poetry ones a shot.
https://gitlab.com/kalilinux/packages/powershell-empire/-/issues/4
