### ISSUE TITLE
Can not display creds after build golden ticket

### ISSUE THREAD

**Issue by dickens88** [BC-SECURITY/Empire#35]
## Empire Version
3.0

## OS Information (Linux flavor, Python version)
latest docker image

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
Hi ,

I follow [this vedio](https://youtu.be/ns7M6zjWDrs) to test in my testing env, i can get krbtgt and make golden ticket like this,

![image](https://user-images.githubusercontent.com/8390209/71462644-e66fae80-27ee-11ea-9d93-7b4bcb7c6354.png)
 the feedback is just like the result i use mimikatz directly, as i understand, the ticket should be store in somewhere in my memory. but when i try to display the creds, the result is nothing
![image](https://user-images.githubusercontent.com/8390209/71462815-87f70000-27ef-11ea-9fa6-8a748e8d6369.png)

 Did i miss anything ?

**Comment by Cx01N** [comment]
Duplicate issue with #31. 
Creds should now properly be printed in the [3.0-bug-fixes](https://github.com/BC-SECURITY/Empire/tree/3.0-bug-fixes) branch.
