### ISSUE TITLE
Agent crash using Dropbox listener

### ISSUE THREAD

**Issue by eaglefn** [BC-SECURITY/Empire#353]
__Note:__ Please fill out all sections (if applicable) and do not delete the below section headers, otherwise the bot will close the issue.

## Empire Version
- Empire 3.x

## OS Information (Linux flavor, Python version)
- OS: 
- Python:

**Comment by Cx01N** [comment]
Closing since this looks like this is a duplicate of https://github.com/BC-SECURITY/Empire/issues/354and is missing information
