### ISSUE TITLE
[BUG] Mimikatz module does not start or never output anything

### ISSUE THREAD

**Issue by mpgn** [BC-SECURITY/Empire#356]
## Empire Version
- Empire 3.5.1

## OS Information (Linux flavor, Python version)
- OS: linux
- Python: 3.8

## Describe the bug
Mimikatz does not start when launching mimikatz module in elevated context

## To Reproduce
1. run mimikatz in elevate context

## Expected behavior
The module doesn't seem to launch

## Screenshots
![image](https://user-images.githubusercontent.com/5891788/96306327-c3252280-0fff-11eb-8751-a0ff789fc32a.png)

## Additional context
same for all the mimikatz module

**Comment by Cx01N** [comment]
@mpgn what system are you targeting? Depending on the machine there may be something blocking it.

**Comment by mpgn** [comment]
Windows 10 - 1908

![image](https://user-images.githubusercontent.com/5891788/96307224-8eb26600-1001-11eb-8779-238980146215.png)

Defender disabled, all options to disable

![image](https://user-images.githubusercontent.com/5891788/96307160-704c6a80-1001-11eb-9090-216af7c1c66e.png)

**Comment by mpgn** [comment]
Running Invoke-Mimikatz.ps1 directly is working, so it's related to Empire 

![image](https://user-images.githubusercontent.com/5891788/96307727-60815600-1002-11eb-9a66-599bf66d658a.png)

**Comment by mpgn** [comment]
Ohhh big pardon, it's just taking a lot of time, like 20 min to get the output.

I rerun a new agents and it's working fast. My bad 👍

**Comment by Cx01N** [comment]
@mpgn Can you share what listener, stager, and settings you are running. We are really are going to need some more info filled out in the ticket. Also, I am not sure if it's an Empire issue since I just tested it on a similar build.

![image](https://user-images.githubusercontent.com/20302208/96307906-35bde000-0fb7-11eb-9413-a62f740377ab.png)
