### ISSUE TITLE
[BUG] Invoke-PSRemoting block current agent

### ISSUE THREAD

**Issue by mpgn** [BC-SECURITY/Empire#359]
## Empire Version
- Empire 3.5.1

## OS Information (Linux flavor, Python version)
- OS: linux
- Python: 3.8

## Describe the bug
Maybe not a bug, maybe yes.
When running Invoke-PSRemoting, a new agent pop and it's working fine. But the current agent is blocked and cannot be used unless the new agent is killed.
Is there any workaround for this so the first agent is not blocked waiting for the Invoke-PSRemoting to finish ?

## To Reproduce
From agent 1 run Invoke-PSRemoting

## Expected behavior
Agent should not be blocked, maybe the Invoke-PSRemoting should be run as a job.

**Comment by Cx01N** [comment]
You need to be running empire in Python 3.
Also, can you please provide more information (Empire version, Listener, Stager, what lateral settings and target info)?

**Comment by mpgn** [comment]
- http listener
- hta stagers

The agent is running on a windows 10 latest version. The module does work, but the inital agent is no responding after that.

The log show this when running the module

![image](https://user-images.githubusercontent.com/5891788/96346397-ec938c00-109b-11eb-9cde-110c17553258.png)

**Comment by mpgn** [comment]
I think I understand why. 

- I had one agent (agent 1) and wanted to pop another agent so I did in the console `Start-Job { powershell xxxx }`
- From the new agent (agent 2) I run the Invoke-PSRemoting and maybe this is why it failed

Maybe there is a better to pop an agent from an initial agent, any idea ?
