### ISSUE TITLE
[BUG] Unable to retrieve dependencies in add-Netuser

### ISSUE THREAD

**Issue by mikesimone** [BC-SECURITY/Empire#367]
__Note:__ Please fill out all sections (if applicable) and do not delete the below section headers, otherwise the bot will close the issue.

## Empire Version
- Empire 3.4.0 BC Security Fork

## OS Information (Linux flavor, Python version)
- OS: Debian 5.8.10-1kali1
- Python: Python 3.8.6

## Describe the bug
Receive the following errors:
[!] Error in retrieving dependencies for function Add-NetUser !
[!] Key error with function Add-NetUser !

## To Reproduce
1. Connect agent
2. usemodule powershell/persistence/misc/add_netuser
3. set Agent
4. set UserName
5. set Password
6. execute

## Expected behavior
I expected it not to throw an error.

## Screenshots
![image](https://user-images.githubusercontent.com/35898917/96903914-481e9a80-144b-11eb-8b14-d197e77fe8d1.png)

**Comment by Cx01N** [comment]
Seems like it was removed a while back and I am not sure why. I'm going to re-add it and hope it doesn't break something elsewhere. Let us know if this works and we will get it fixed in the next build. https://github.com/BC-SECURITY/Empire/pull/381
