### ISSUE TITLE
Powershell missing in docker - Debian 10 Buster 

### ISSUE THREAD

**Issue by LaZyDK** [BC-SECURITY/Empire#37]
## Empire Version
[Version] 3.0 BC-Security Fork

## OS Information (Linux flavor, Python version)
Debian 10 Buster
Python 3.7.5
from Docker image: python:3.7.5-buster

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
`uselistener http`
`set Name httptest`
`set Host http://c2.example.com:443`
`set BindIP 0.0.0.0`
`set Port 3000`
`execute`

`usestager multi/launcher`
`set Obfuscate true`
`set SafeChecks false`
`set Listener httptest`
`execute`
**[!] PowerShell is not installed and is required to use obfuscation, please install it first.**

## Screenshot of error, embedded text output, or Pastebin link to the error
<img width="756" alt="Skærmbillede 2019-12-26 kl  22 56 53" src="https://user-images.githubusercontent.com/9623973/71491972-36bd2f80-2834-11ea-9460-701df62f287c.png">

## Any additional information
Debian 10 Buster is not referenced in the [install.sh](https://github.com/BC-SECURITY/Empire/blob/master/setup/install.sh) script.

**Comment by LaZyDK** [comment]
This will install powershell from Debian 9 Stretch on Debian 10 Buster:
```
sudo apt-get install -y apt-transport-https curl
curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-debian-stretch-prod stretch main" > /etc/apt/sources.list.d/microsoft.list'

mkdir /tmp/pwshtmp
cd /tmp/pwshtmp
wget http://http.us.debian.org/debian/pool/main/i/icu/libicu57_57.1-6+deb9u3_amd64.deb
wget http://http.us.debian.org/debian/pool/main/u/ust/liblttng-ust0_2.9.0-2+deb9u1_amd64.deb
wget http://http.us.debian.org/debian/pool/main/libu/liburcu/liburcu4_0.9.3-1_amd64.deb
wget http://http.us.debian.org/debian/pool/main/u/ust/liblttng-ust-ctl2_2.9.0-2+deb9u1_amd64.deb
wget http://security.debian.org/debian-security/pool/updates/main/o/openssl1.0/libssl1.0.2_1.0.2t-1~deb9u1_amd64.deb
sudo dpkg -i *.deb
cd
rm -rf /tmp/pwshtmp

sudo apt-get update 
sudo apt-get install -y powershell 
```

**Comment by vinnybod** [comment]
Thanks for your contribution. Got this corrected in https://github.com/BC-SECURITY/Empire/pull/38

Keeping this issue open however, because using your steps, I am having issues with the obfuscation command within the docker container.

**Comment by vinnybod** [comment]
The fix is merged in. You should be able to run these commands using the the `:latest` container.
