### ISSUE TITLE
Unabel to download files 

### ISSUE THREAD

**Issue by gmargarida1979** [BC-SECURITY/Empire#372]
Hi! Installed Empire 3.0.1 without any error and everything seems to work perfectly; but, when I try do download any file from target system it shows the error as screenshot here; When downloading, I m on the same directory where the file is located;
Can you please give me some advice on this?
Thanks!
![Captura de ecrã de 2020-10-26 16-10-56](https://user-images.githubusercontent.com/73487930/97197695-d9707280-17a5-11eb-8a5b-9d7f5cc2a458.png)

**Comment by mpgn** [comment]
run "Shell pwd" and check the path or use "download full_path"
