### ISSUE TITLE
[FEATURE REQUEST] Create listener totaly in CLI

### ISSUE THREAD

**Issue by w1ld3r** [BC-SECURITY/Empire#373]
**Is your feature request related to a problem? Please describe.**
Unable to create listener without using the Empire shell.
It can be intersting for automated generation of payloads to don't have to use the Empire shell to create a listener.

**Describe the solution you'd like**
Be able to create listener in CLI.

**Describe alternatives you've considered**
For know to create a listener we have to interact with the Empire shell.

**Additional context**
None

**Comment by Cx01N** [comment]
@w1ld3r Is this different from the last issue https://github.com/BC-SECURITY/Empire/issues/199? 
We fixed the issue a while back and it should be working. If there is a bug then please submit an issue for that.

**Comment by RRohi** [comment]
I have resolved this problem like this:

Create a text file with the following contents (resources.txt):

```vim
uselistener http
set Name http-listener
set Port 80
execute
```

And then run PSEmpire like this:
```bash
python3 empire --resource resources.txt --rest --password ThisIsAPassword
```
Remove `--rest` if you have no need for API.

`resource` parameter will execute whatever you put in the resource file. Empire specific stuff, obviously.
I'm creating initial listener and stager that way atm.

**Comment by w1ld3r** [comment]
Ok, thanks @RRohi !

**Comment by RRohi** [comment]
My previously provided example is incorrect due to non-existent documentation regarding resource file usage and can end in the disk filling up with errors real quick and CPU being used 100%. Through trial and error I managed to get a working solution.

Correct would be:
```vim
uselistener http
set Name http-listener
set Port 80
execute
exit
Y
```

Another example, with two different actions being executed:
```vim
uselistener http
set Name http1
set Port 80
execute

main
usestager multi/launcher http1
set OutFile /empire/download/multi-payload.ps1
execute
exit
Y
```

Mind the exit and confirmation in the end of the file.

**Comment by Cx01N** [comment]
The resourcefile option for the client should allow basic scripting, otherwise, you can build your own interface to the API and go crazy with it. https://bc-security.gitbook.io/empire-wiki/quickstart/configuration#client
