### ISSUE TITLE
[BUG] Unable to create more than 1 'redirector' listener

### ISSUE THREAD

**Issue by flannel-guy** [BC-SECURITY/Empire#386]
__Note:__ Please fill out all sections (if applicable) and do not delete the below section headers, otherwise the bot will close the issue.

## Empire Version
- Empire 3.5.1

## OS Information (Linux flavor, Python version)
- OS: Kali 2020.3
- Python: 3.8.6

## Describe the bug
I am unable to start more than one 'redirector' listener at one time. Prevents pivoting through more than a single end-target. When attempting to make an additional 'redirector' listener, I'm not given a menu option for where to execute it, nor does any filled in options matter. It will fail to initialize with the following error message: [!] Error starting listener: 'Listener'

## To Reproduce
1. Get an agent on a machine
2. Setup a 'redirector' listener
3. PSexec to another target, calling back to your 'redirector' listener
4. Attempt to setup another 'redirector' listener on your new target box
5. Error / failure condition should trigger when attempting to setup the new 'redirector' listener

## Expected behavior
I should be able to set up additional 'redirector' listeners on subsequent targets to pivot more than 1 target deep in a network.

## Screenshots
![image](https://user-images.githubusercontent.com/73953013/98136123-95a8f780-1e8e-11eb-9b9b-927c484a25d6.png)

## Additional context
N/A

**Comment by Cx01N** [comment]
@flannel-guy The issue should be fixed, could you give it a try and let me know if it works for you too?

**Comment by flannel-guy** [comment]
> @flannel-guy The issue should be fixed, could you give it a try and let me know if it works for you too?

Works for me now, thanks for the quick turnaround.
