### ISSUE TITLE
[BUG] Malleable C2 / incorrect URIs

### ISSUE THREAD

**Issue by flannel-guy** [BC-SECURITY/Empire#392]
__Note:__ Please fill out all sections (if applicable) and do not delete the below section headers, otherwise the bot will close the issue.

## Empire Version
- Empire 3.6.0

## OS Information (Linux flavor, Python version)
- OS: Kali 2020.3
- Python: 3.8.6

## Describe the bug
Generating a Malleable listener with an appropriately populated C2 profile works successfully, but any agent generated from them is not passed the correct URIs. Seems that it is defaulting to '/'.

## To Reproduce
1. Populate a C2 profile
2. Create a malleable listener using that profile
3. Generate a stager for that listener
4. Execute an agent on target machine
5. Monitor the HTTP comms via wireshark

## Expected behavior
Generated agents should be configured to call out with the specified HTTP GET/POST URIs as specified in the supplied C2 profile.

## Screenshots
![image](https://user-images.githubusercontent.com/73953013/98590447-d5138180-229c-11eb-9815-111a76173272.png)

![image](https://user-images.githubusercontent.com/73953013/98590569-07bd7a00-229d-11eb-9953-819bd0a5c1bc.png)

## Additional context
I tried putting trailing '/'s in the C2 profile, but that caused the same issue of the agent just reaching out for '/' as the GET URI.

**Comment by Cx01N** [comment]
I think the options clearing that we implemented in the last release messed with the malleable listener. Could you give this branch a shot and let me know if it fixes your issue?
https://github.com/BC-SECURITY/Empire/tree/malleable_fix

I tested the havex profile from our repo and it seems to be working. Which one were you using? Just so I can make sure it's not a broken profile (some have issues, unfortunately).
https://github.com/BC-SECURITY/Malleable-C2-Profiles/tree/master/APT

![image](https://user-images.githubusercontent.com/20302208/98625601-ba550300-22c4-11eb-826d-c8d23d201ad6.png)

**Comment by flannel-guy** [comment]
That branch seemed to fix the issue.

I was using the amazon.profile originally, but the havex.profile in your repository is working fine for me now.

**Comment by Cx01N** [comment]
I'll roll out a patch this week. Thanks for finding this!
