### ISSUE TITLE
Empire spams log with some sort of syntax error with stager/multi/launcher

### ISSUE THREAD

**Issue by RRohi** [BC-SECURITY/Empire#394]
__Note:__ Please fill out all sections (if applicable) and do not delete the below section headers, otherwise the bot will close the issue.

## Empire Version
- Empire 3.5.0

## OS Information (Linux flavor, Python version)
- OS: Ubuntu 18.04
- Python: 3.7.5
- Docker: CE 19.03.13

## Describe the bug
Resource file contents
```vim
uselistener http
set Name http-listener
set Port 80
execute

main
usestager multi/launcher http-listener
set OutFile /empire/multi-payload.ps1
execute
```

When running Empire like this:
```bash
python3 empire --resource resource.txt --rest --password ThisIsAPassword
```
the listener gets created and the stager as well, but in the logs I see this:
```vim
{"log":"\u001b[1;34m[*] Stager output written out to: /empire/multi-payload.ps1\n","stream":"stdout","time":"2020-11-10T09:56:46.070997099Z"}
{"log":"\u001b[0m\n","stream":"stdout","time":"2020-11-10T09:56:46.071000799Z"}
{"log":"(Empire: \u001b[1;34mstager/multi/launcher\u001b[0m) \u003e *** Unknown syntax: EOF\n","stream":"stdout","time":"2020-11-10T09:56:46.071125402Z"}
{"log":"(Empire: \u001b[1;34mstager/multi/launcher\u001b[0m) \u003e *** Unknown syntax: EOF\n","stream":"stdout","time":"2020-11-10T09:56:46.071197005Z"}
{"log":"(Empire: \u001b[1;34mstager/multi/launcher\u001b[0m) \u003e *** Unknown syntax: EOF\n","stream":"stdout","time":"2020-11-10T09:56:46.071206405Z"}
{"log":"(Empire: \u001b[1;34mstager/multi/launcher\u001b[0m) \u003e *** Unknown syntax: EOF\n","stream":"stdout","time":"2020-11-10T09:56:46.071210405Z"}
{"log":"(Empire: \u001b[1;34mstager/multi/launcher\u001b[0m) \u003e *** Unknown syntax: EOF\n","stream":"stdout","time":"2020-11-10T09:56:46.071287807Z"}
{"log":"(Empire: \u001b[1;34mstager/multi/launcher\u001b[0m) \u003e *** Unknown syntax: EOF\n","stream":"stdout","time":"2020-11-10T09:56:46.071347009Z"}
{"log":"(Empire: \u001b[1;34mstager/multi/launcher\u001b[0m) \u003e *** Unknown syntax: EOF\n","stream":"stdout","time":"2020-11-10T09:56:46.071355309Z"}
{"log":"(Empire: \u001b[1;34mstager/multi/launcher\u001b[0m) \u003e *** Unknown syntax: EOF\n","stream":"stdout","time":"2020-11-10T09:56:46.071429012Z"}
{"log":"(Empire: \u001b[1;34mstager/multi/launcher\u001b[0m) \u003e *** Unknown syntax: EOF\n","stream":"stdout","time":"2020-11-10T09:56:46.071485113Z"}
```
These Unknown syntax errors are getting spammed so heavily that the container it's in, gets full in about half an hour (30GB).
First Unknown syntax error is at row 122, the last is at row 4478473. Disk run out of space at that point.

## To Reproduce
1. Create a volume for persistence (volume name for this example will be empire-data)
2. Build Empire container
2.1 Copy resource file from host to /empire/resource.txt in Dockerfile
2.1.1 Copy the contents from the example above
2.2 Set CMD like so: `CMD ["python3", "empire", "--resource", "/empire/resource.txt", "--rest", "--password", "ThisIsAPassword"]`
3. Run container
3.1 Set Network Mode to host (`--network host`)
3.2 Run in detached mode (`--detach`)
3.3 Publish all ports (`--publish-all`)
3.4 Set Restart Policy to always (`--restart always`)
3.5 Mount persistence volume (`--volume empire-data`)
4. If the container run successfully, check if multi-payload.ps1 is in /empire/ that host is listening on port 80
5. If listener and payload are present, just wait about 10 minutes.
6. Log, in the container, is in here: /var/lib/docker/containers/<container id>/<container id>-json.log

## Expected behavior
Without this issue, the log wouldn't grow rapidly to fill out the entire disk.

## Screenshots
![Screenshot 2020-11-10 163938](https://user-images.githubusercontent.com/20452819/98688305-5fc6b000-2373-11eb-8672-6dce3896b1d0.png)

## Additional context
My workaround for this at the moment is configuring the container to limit log file to 5GB, but this is just to avoid filling up the disk. The log itself at this point is useless, since this error is all it has.

**Comment by RRohi** [comment]
I have an idea what is causing this spam. When Empire reads the resource file, it goes through all the lines I have in that file, but the process doesn't end with the last execution.

I think Python might be spamming EOF to Empire, since it reached the end of the file, but the file is not closed and Empire is reading the EOF input continuously.

I could add **exit** command to the last line, but then a prompt appears that expects an interactive **Y**. I once tried adding **exit** and **y** at the end of the file. **exit** went through, but nothing happened with **Y**, so the file remained open.

Taking the resource file example, I removed the listener creation part and then I got:
```bash
(Empire: listeners/http) > *** Unknown syntax: EOF
(Empire: listeners/http) > *** Unknown syntax: EOF
(Empire: listeners/http) > *** Unknown syntax: EOF
(Empire: listeners/http) > *** Unknown syntax: EOF
(Empire: listeners/http) > *** Unknown syntax: EOF
(Empire: listeners/http) > *** Unknown syntax: EOF
(Empire: listeners/http) > *** Unknown syntax: EOF
(Empire: listeners/http) > *** Unknown syntax: EOF
(Empire: listeners/http) > *** Unknown syntax: EOF
(Empire: listeners/http) > *** Unknown syntax: EOF
```

Which indicates that the problem is not with the multi/launcher stager, but with the resource file ingestion function.

**Comment by RRohi** [comment]
Strange.. I was pretty sure that by adding **exit** and **Y** to the end of the resource file didn't work last time, but it actually did now when I tested it.

No spamming anymore.

So it probably isn't a bug, but an improperly formatted resource file.

If you have the resources, you could add a check that makes sure the supplied resource file exits properly. And the launch would fail, if not.

**Comment by RRohi** [comment]
Leaving the correct resource file structure sample:
```vim
uselistener http
set Name http-listener
set Port 80
execute

main
usestager multi/launcher http-listener
set OutFile /empire/multi-payload.ps1
execute
exit
Y
```

**Comment by Cx01N** [comment]
@RRohi We have been entertaining the idea of a better version of resource files. Any feedback on things you would like to see to make your workflows better?

**Comment by RRohi** [comment]
I've only used REST, but haven't actually build one.

Instead of providing a resource file during Empire startup, would it be possible to POST a resource file via API?

That way the initial resource file, provided at startup at the moment, wouldn't be static. I could possibly provide entire attack cycle via resource file, by interfacing the API.

I know most, if not everything, can already be done via API calls, but using resource file vs. playing with separate API calls is a big difference.

**Comment by Cx01N** [comment]
The new CLI will be 100% through the API, so going in that direction would be good. Having something similar to this project would be awesome. But I wasn't able to get it working, and it would be a bit more complicated. The next step forward, I expect us to incorporate it into the yaml since we are already using that for configuration.

https://github.com/jymcheong/AutoTTP
