### ISSUE TITLE
[BUG] Powershell windows is showing for stager windows/macro. I have tried in many laptop and for all powershell window is coming up after running the macro. Please fix it because it's very suspicious.

### ISSUE THREAD

**Issue by RohanAgarwal12** [BC-SECURITY/Empire#397]
__Note:__ Please fill out all sections (if applicable) and do not delete the below section headers, otherwise the bot will close the issue.

## Empire Version
- Empire 3.x

## OS Information (Linux flavor, Python version)
- OS: 
- Python:

**Comment by Cx01N** [comment]
__Note:__ Please fill out all sections (if applicable) and do not delete the below section headers, otherwise the bot will close the issue.
