### ISSUE TITLE
[FEATURE REQUEST] A new option for specifying where to display event message.

### ISSUE THREAD

**Issue by CykuTW** [BC-SECURITY/Empire#405]
__Note:__ Please fill out all sections (if applicable) and do not delete the below section headers, otherwise the bot will close the issue.

## Is your feature request related to a problem? Please describe.
No, it's a whole new feature request maybe about user experience with Empire shell.

Sometimes, the agent event message popups when I'm typing in Empire shell, the message breaks the display of my input because the message is wrote to stdout too. 
Although my input is not really affected but it's a little annoying.

Mixed message example:
![](https://user-images.githubusercontent.com/22723799/99621173-2a504f80-2a62-11eb-98e3-cff36a33f14f.png)

## Describe the solution you'd like
Maybe add a new option specifying where to display event message, something like '--pipe-agent-event' option to make Empire write to somewhere instead of stdout, such as named pipe.
Then the user can choose any tools they like to read the event message. For example: tmux.

## Describe alternatives you've considered
Also maybe can save the event message to database. Then can read it from other script.

## Additional context
None

**Comment by Cx01N** [comment]
@CykuTW We have been working on a new CLI for a while, which will fix this issue. It's been something that has always annoyed us too. We are in closed beta right now but should have something for public testing in a few weeks.

**Comment by CykuTW** [comment]
@Cx01N 
Thanks for your great work, I'm looking forward to the public testing!

**Comment by Cx01N** [comment]
@CykuTW We released it for public testing. Let us know what you think!
https://github.com/BC-SECURITY/Empire-Cli
