### ISSUE TITLE
[BUG]RunAs / SpawnAs / Credential Use failure

### ISSUE THREAD

**Issue by flannel-guy** [BC-SECURITY/Empire#409]
__Note:__ Please fill out all sections (if applicable) and do not delete the below section headers, otherwise the bot will close the issue.

## Empire Version
- Empire 3.5.1

## OS Information (Linux flavor, Python version)
- OS: Kali 2020.3
- Python: 3.8.6

## Describe the bug
Suspected that ALL credential modules are truncating any passwords with a '$' in them. Confirmed to be an issue with runas/spawnas, but I suspect its for all credential use.

## To Reproduce
1. Get an agent on a machine
2. Attempt to use the 'runas' or 'spawnas' module with credentials that has a '$' in it
3. Cred use will fail

## Expected behavior
Credentials should be able to be used successfully if a user has any special characters, specifically a $ sign in the password.

## Screenshots
In addition to issues using special characters in a password as described above, I am getting constant errors during a RunAs / SpawnAs for "Calling Start with 1 argument(s): Access Denied", when attempting to execute RunAs/SpawnAs from a DomainAdmin, to spawn processes as normal users, as seen in the screenshot below.

![image](https://user-images.githubusercontent.com/73953013/100919551-f33d5d80-34a7-11eb-924d-fa3aec7f66ae.png)

**Comment by Cx01N** [comment]
Fix added in 4.0
