### ISSUE TITLE
[BUG] Dumped creds / hashes are not being added to the credential store

### ISSUE THREAD

**Issue by flannel-guy** [BC-SECURITY/Empire#413]
__Note:__ Please fill out all sections (if applicable) and do not delete the below section headers, otherwise the bot will close the issue.

## Empire Version
- Empire 3.6.2

## OS Information (Linux flavor, Python version)
- OS: Kali 2020.3
- Python: 3.8.6

## Describe the bug
Dumped creds / hashes from mimikatz modules are not being added to the credential store all the time. Logonpasswords seemed to work, but other modules from mimikatz, like lsadump, don't output to the credential store.
## To Reproduce
1. Get an Empire agent on a target
2. Execute mimikatz modules (lsadump / logonpasswords)
3. When module finishes execution, check the credential store
4. See error condition, logonpassword output should be present, but not lsadump/other mimikatz module passwords/hashes.

## Expected behavior
Any dumped password/hashes from any mimikatz modules in Empire should send their output to the credential store.

## Screenshots
![creds](https://user-images.githubusercontent.com/73953013/100748392-4385c400-33b1-11eb-9b65-42895d880fc5.png)

**Comment by Cx01N** [comment]
@flannel-guy I think this should fix it, I definitely want to go back and redo this entire piece of code at some point.
Let me know if this PR works and we can get it into a patch. https://github.com/BC-SECURITY/Empire/pull/423
