### ISSUE TITLE
[BUG] Powershell Stage2 gets caught when using redirector

### ISSUE THREAD

**Issue by Braddymon** [BC-SECURITY/Empire#417]
__Note:__ Please fill out all sections (if applicable) and do not delete the below section headers, otherwise the bot will close the issue.

## Empire Version
- Empire 3.6.1

## OS Information (Linux flavor, Python version)
- OS: Debian Buster
- Python 3.7.3

## Describe the bug

When trying to use domain fronting (apache redirector using mod_rewrite), the second stage gets caught, normally with an exception.

## To Reproduce
1. Set up everything as normal with Host filled in as the domain name/ IP hosting the redirector (Used fresh install with default profile)
2. Send powershell stager to client
3. Wait for exception to be raised / no second stage being sent

Mod_Rewrite Rules:
RewriteEngine On
RewriteCond %{REQUEST_URI} ^/(admin/get.php|news.asp|login/process.jsp)/?$
RewriteCond %{HTTP_USER_AGENT} ^Mozilla/5\.0\ \(Windows\ NT\ 6\.1;\ WOW64;\ Trident/7\.0;\ rv:11\.0\)\ like\ Gecko?$
RewriteRule ^.*$ https://yourdomainoriphere:443%{REQUEST_URI} [P]
RewriteRule ^.*$ https://www.someotherdomainhere;).com/? [L,R=302]

## Expected behavior

The stager to function as normal

## Additional context

Thanks for looking into this !

**Comment by Cx01N** [comment]
Unfortunately, we aren't able to provide obfuscation help. But we will need more information about the error and setup to assist further with the issue. Also, our discord has some pretty knowledgeable individuals who may be able to provide help. https://discord.com/invite/P8PZPyf
