### ISSUE TITLE
[FEATURE REQUEST] Allow modules to output results in JSON for programmatic parsing through the API

### ISSUE THREAD

**Issue by byt3bl33d3r** [BC-SECURITY/Empire#420]
## Is your feature request related to a problem? Please describe.
It would be *amazing* if all modules had an option to output JSON as supposed to "stringified" Posh Objects. The main use case for this would be allowing programmatic parsing of module output when interacting with Empire through the Rest API. As of right now, you have to do some nasty string parsing in order to extract the meaningful data out of every module's output and in some cases it's almost impossible to account for all the edge-cases. (e.g. the `tasklist` command)

## Describe the solution you'd like
If there was a global setting to enable all modules to output JSON or something that would be ideal. 

From a PoSH perspective, there's the [CovertTo-JSON](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/convertto-json?view=powershell-7.1) cmdlet which does exactly what you'd expect. So it would be a matter of adding an option globally and checking for it in every module and appending `| ConvertTo-Json` as supposed to `<posh-command> | Out-String`.

## Describe alternatives you've considered
See above.

## Additional context
N/A

**Comment by vinnybod** [comment]
This feature is now available in `v4.0.0-beta.1` . Select powershell modules now have an option called `OutputFunction` which defaults to `Out-String`.

**Comment by byt3bl33d3r** [comment]
Awesome!
