### ISSUE TITLE
[Feature Request] Redirector chaining for multiple agents (Peer-to-Peer)

### ISSUE THREAD

**Issue by flannel-guy** [BC-SECURITY/Empire#421]
__Note:__ Please fill out all sections (if applicable) and do not delete the below section headers, otherwise the bot will close the issue.

## Empire Version
- Empire 3.6.2

## OS Information (Linux flavor, Python version)
- OS: Kali 2020.3
- Python: 3.8.6

## Describe the bug
Unable to use Empire Agents past 2-targets deep. 

Example Target Path:
|->  Agent1 - redirector Listener (points to HTTP listener)
|--> Agent2 - redirector listener (point to Agent1 redirector listener)
|---> Agent3

When using a redirector listener, pointing to a target with a http listener (2-hops deep), the furthest Empire Agent in cannot do actions like spawning new Agents / using lateral movement modules. 

Using my example target path above, from Agent2, I cannot psexec/lateral move to Agent3.
I CAN psexec from Agent1 to Agent3 and have it call back to the redirector listener on Agent2, but this workaround shouldn't be necessary, and won't be feasible for all situations.

## To Reproduce
1. Execute Agent on target calling out to a http listener
2. Setup redirector listener pointing to egress http listener
3. Execute Agent on different target, calling out to redirector listener configured in step-2
4. Setup redirector listener pointing to previous redirector listener
5. From this Agent, attempt to gain access to a follow-on target calling back to its own redirector listener you set up.

## Expected behavior
I should be able to use redirector listeners any amount of hops deep into a network and have successful comms through them, not be limited to 2 targets deep.

**Comment by Cx01N** [comment]
Great idea, I was hoping the simple fix was going to be enough for chained agent support, but it looks like we will need to do a bit more work. I'll update this issue to be a feature request instead of a bug. That way, you or anyone else can give some other functionality ideas that this should include.

Thanks!

**Comment by Cx01N** [comment]
https://github.com/BC-SECURITY/Empire-Sponsors/pull/142
