### ISSUE TITLE
Internal Monologue runs only once for each agent

### ISSUE THREAD

**Issue by Invoke-Mimikatz** [BC-SECURITY/Empire#43]
## Empire Version
3.0 Bug Fixes

## OS Information (Linux flavor, Python version)
Kali 2019.2, Python 3.7.5

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
Expected behaviour: invoke_internal_monologue module dumps the same NetNTLMv1 hashes every time, once for each run of the module.

Observed behaviour: invoke_internal_monologue module dumps NetNTLMv1 hashes only ONCE on the first run of the module for that agent, and never again after that (for that agent only). The agent stays alive, and commands can be run on the agent after, but invoke_internal_monologue will return no v1's again.

## Screenshot of error, embedded text output, or Pastebin link to the error
<img width="1034" alt="image" src="https://user-images.githubusercontent.com/57604669/71561607-44460580-2a3e-11ea-83f4-1f2de8cc78b7.png">

## Any additional information
Running agent on Windows 10 (1809), PSVersion 5.1

**Comment by Cx01N** [comment]
@Invoke-Mimikatz I added a check to clear the table if the module has been run before. It is not the most graceful fix, but it fixes the issue. Could you test out the PR and see if it fixed the issue for your setup?

**Comment by Invoke-Mimikatz** [comment]
Nice fix. Seems to work as expected on my systems

<img width="1077" alt="image" src="https://user-images.githubusercontent.com/57604669/78301857-57fe7d80-74ff-11ea-8e90-080fa4aca537.png">
