### ISSUE TITLE
 [BUG] Removing Stale Agents or All Agents fails and Tab complete does not work

### ISSUE THREAD

**Issue by Braddymon** [BC-SECURITY/Empire#441]
__Note:__ Please fill out all sections (if applicable) and do not delete the below section headers, otherwise the bot will close the issue.

## Empire Version
- Empire 3.7.2

## OS Information (Linux flavor, Python version)
 OS: Debian 10
    Python: 3.8

## Describe the bug

When trying to clear agents using 'remove all' or 'remove stale', it says it is completed but the agents are still there. Manually removing 1 by 1 works.

Using tab complete with 'interact ' works but does not work when using 'set Agent '

## To Reproduce
1.) go to agents
2.) try to remove stale

1.) go to usemodule powerhell/somemodule
2.) set Agent

## Expected behavior

All stale agents/all agents to be removed from agents list

Tab complete to work when using set Agent

## Screenshots

N/A

## Additional context

N/A

**Comment by janit0rjoe** [comment]
The different behavior of the different remove arguments was "introduced" with c4fbe4930fd02a2982c2de804a9d1699fc9209d8

`remove all` and `remove id/name` use the Agents.remove_agent_db() function to remove the agents from cache and from db.
`remove stale` and `<int>` removes them from the db without using Agents.remove_agent_db().

But the actual bug regarding `remove all` not working is located in Agents.remove_agent_db(). After the commit the there is no logical path to any action on the db in the `remove all` case.

`remove stale` btw workes fines.

I'll add a pull request to fix the `remove all` bug.
But the maintainers should decide whether they use the direct removal from db or Agents.remove_agent_db() function with cache clearing.
