### ISSUE TITLE
lsb_release -d to detect OS version is unreliable

### ISSUE THREAD

**Issue by NonVictus** [BC-SECURITY/Empire#448]
## Empire Version
- Empire 3.7.2

## OS Information (Linux flavor, Python version)
- OS: Slingshot Linux
- Python: 3.7

## Describe the bug
Using `/opt/empire3/setup# lsb_release -d 2>/dev/null` in install.sh to determine the distro type is breaking installation in Slingshot Linux. The output from `lsb-release -d` is `Description:	SEC501-Slingshot (2021.03.09, build 6070ead)`. Many Linux distros change the contents of `Description`, including Kali. `lsb_release -i` would give better results.

## To Reproduce
1. Run `install.sh` on Slingshot
2. Script exits (0, which it should exit with a non-zero code) and prints "Unsupported OS. Exiting."

## Expected behavior
Script properly detects Slingshot Linux as Ubuntu-based and finishes setup.

## Screenshots
N/A

## Additional context
N/A

**Comment by vinnybod** [comment]
We may scrap `lsb_release` all together. We should be able to use a combination of `/etc/debian_version` and`/etc/os-release` to get what we need. Just tested on Slingshot and `/etc/os-release` gives a name of Ubuntu and version of 18.04, so it would get the same install treatment as an Ubuntu 18.04 install with this change.

**Comment by vinnybod** [comment]
I have a fix for this going into the 4.0 release, which is targeted to go out in a couple of months. If you need this resolved before that, let me know and we can work it out. I could backport the changes into 3.x.

**Comment by NonVictus** [comment]
Nice. I think /etc/os-release is a better option for determining underlying OS. I can wait for 4.0. Thanks!
