### ISSUE TITLE
root@domino:~/Empire# ./empire --debug Traceback (most recent call last):   File "/root/Empire/./empire", line 14, in <module>     import ssl   File "/usr/local/lib/python3.9/ssl.py", line 98, in <module>     import _ssl             # if we can't import it, let the error propagate ModuleNotFoundError: No module named '_ssl'

### ISSUE THREAD

**Issue by Mrsherlock2232243** [BC-SECURITY/Empire#449]
root@domino:~/Empire# ./empire --debug
Traceback (most recent call last):
  File "/root/Empire/./empire", line 14, in <module>
    import ssl
  File "/usr/local/lib/python3.9/ssl.py", line 98, in <module>
    import _ssl             # if we can't import it, let the error propagate
ModuleNotFoundError: No module named '_ssl'
he problem here.

**Comment by Cx01N** [comment]
This issue is closed because it does not meet our issue template. Please resubmit with the correct template.
