### ISSUE TITLE
[BUG] Exception error when creating stager for http_hop listener

### ISSUE THREAD

**Issue by Gloompirate** [BC-SECURITY/Empire#451]
__Note:__ Please fill out all sections (if applicable) and do not delete the below section headers, otherwise the bot will close the issue.

## Empire Version
- Empire 3.8.2

## OS Information (Linux flavor, Python version)
- OS: Kali 2021.1
- Python: 3.9.2

## Describe the bug
Attempting to create a multi/bash stager with a http_hop listener causes an error and returns back to the main menu

## To Reproduce
1 Create a http listener
2 Create a http_hop listener with the http listener as the RedirectListener
3 Create a multi/bash stager with the Listener set to the http_hop listener
4 Execute the stager
5 Error message [!]Exception: a bytes-like object is required, not 'str'

## Expected behavior
A stager for the http_hop listener should be created.

## Additional context
Error message generated:
`[!]Exception: a bytes-like object is required, not 'str'`

**Comment by Cx01N** [comment]
@Gloompirate Only tested the windows launchers for this one...v3.8.3 incoming. These database changes caused more issues than I expected.

**Comment by Cx01N** [comment]
I'll try to get a patch pushed out this weekend but until then, you can modify this line to `                    launchEncoded = base64.b64encode(launcherBase.encode("UTF-8")).decode("UTF-8")
` and it should work.
https://github.com/BC-SECURITY/Empire/blob/1bf3d51ec35075288d85830f08a7a272164e0f68/lib/listeners/http_hop.py#L299
