### ISSUE TITLE
[BUG] Can't change listener values #2

### ISSUE THREAD

**Issue by m33s33ks** [BC-SECURITY/Empire#458]
__Note:__ Please fill out all sections (if applicable) and do not delete the below section headers, otherwise the bot will close the issue.

## Empire Version
- Empire 3.8.2
- 
## OS Information (Linux flavor, Python version)
- OS: Linux kali 5.10.0-kali8-amd64 
- Python: 3.9.2 

## Describe the bug
This is a follow up to an older issue that was fixed.
https://githubmemory.com/repo/BC-SECURITY/Empire/issues/454
https://github.com/janit0rjoe/Empire/pull/1/commits/f4d650a304cf7e374ba91e67013775c996b96888

But I get the same error as in the older issue.
I have confirmed that the applied fix is present in my /listeners/http.py file.

When I try to disable the listener, I get this error:

(Empire: listeners) > disable DeathStar
[!] Exception: 'NoneType' object has no attribute 'enabled'

## To Reproduce
1. listeners DeathStar info 
2. edit DeathStar Host xxx.xxx.xxx.xx 
3. disable DeathStar 

## Expected behavior
that the host info for the listener is changed

**Comment by janit0rjoe** [comment]
Last update of 3.8.2 in kali repositories dates 29th of March. So the fix should not yet been there. Have you tried cloning dev-branch from github? 

I won't be able to have a look at this again within the next two weeks.

**Comment by janit0rjoe** [comment]
As said before, the 3.8.2 cloned from this repo works.
Kali now is shipping 4.0.1. There listener options don't get changed any more. You got to create a new listener.

So that should solve the issue.

**Comment by Cx01N** [comment]
We have a fix that we are working which should hopefully add this functionality into the API in 4.1.

**Comment by Cx01N** [comment]
Added menu options to cli to update listener settings with https://github.com/BC-SECURITY/Empire-Sponsors/pull/189

How to:
```
listeners
editlistener http
disable
set Cookie newcookiethatdoesn'tlooksuspicious
enable
```
