### ISSUE TITLE
[BUG] Docker Run Error: no such table: config

### ISSUE THREAD

**Issue by d0n601** [BC-SECURITY/Empire#465]
## Empire Version
- Empire 4.0.1

## OS Information (Linux flavor, Python version)
- OS: Ubuntu 20.04.2 LTS
- Docker version 20.10.2, build 20.10.2-0ubuntu1~20.04.3
- Python:  3.9.4 (in container), 3.8.10 (on host)

## Describe the bug
Following the [QuckStart](https://bc-security.gitbook.io/empire-wiki/quickstart/installation) installation section for Docker on a fresh Ubuntu VM the `docker run` commands return an error that the `config` table does not exist.

## To Reproduce
1. On a fresh machine, pull the latest docker image `docker pull bcsecurity/empire:latest`.
2. Run the Docker image with any of the commands on the Quickstart page, such as `docker run -it -p 1337:1337 -p 5000:5000 bcsecurity/empire:latest`. 
3. See error

## Expected behavior
In past versions this has successful started run the Docker container and started the Empire server. 

## Screenshots
![error_empire](https://user-images.githubusercontent.com/8961705/127212705-426162bc-88ae-4d96-a528-638684648bcd.png)

## Additional context
Here is the console output containing the error message.  

```
root@empire:~# docker run -it -p 1337:1337 -p 5000:5000 bcsecurity/empire:latest
Skipping virtualenv creation, as specified in config file.
[*] Loading default config
[*] Setting up database.
[*] Adding default user.
[*] Adding database config.
[*] Generating random staging key
[*] Adding default bypasses.
[*] Adding default keyword obfuscation functions.
[*] Fresh start in docker, running reset.sh for you
[*] Certificate not found. Generating...
[*] Certificate written to ../empire/server/data/empire-chain.pem
[*] Private key written to ../empire/server/data/empire-priv.key
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1770, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: config

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/empire/empire.py", line 12, in <module>
    server.run(args)
  File "/empire/empire/server/server.py", line 2257, in run
    main = empire.MainMenu(args=args)
  File "/empire/empire/server/common/empire.py", line 75, in __init__
    self.obfuscateCommand) = data_util.get_config(
  File "/empire/empire/server/utils/data_util.py", line 26, in get_config
    config = Session().query(models.Config).first()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2750, in first
    return self.limit(1)._iter().first()
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2834, in _iter
    result = self.session.execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1677, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1582, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 329, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1451, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1813, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1994, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1770, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: config
[SQL: SELECT config.staging_key AS config_staging_key, config.install_path AS config_install_path, config.ip_whitelist AS config_ip_whitelist, config.ip_blacklist AS config_ip_blacklist, config.autorun_command AS config_autorun_command, config.autorun_data AS config_autorun_data, config.rootuser AS config_rootuser, config.obfuscate AS config_obfuscate, config.obfuscate_command AS config_obfuscate_command 
FROM config
 LIMIT ? OFFSET ?]
[parameters: (1, 0)]
(Background on this error at: http://sqlalche.me/e/14/e3q8)

```

**Comment by fplazar** [comment]
If anybody encounters the same issue, here you have a temporary solution.

Changing the following line to `if not os.path.exists('empire/server/data/empire.db'):` seems to be working for me.

https://github.com/BC-SECURITY/Empire/blob/886e5131d51b082325f57dc0a5c8eeb39fb04fe1/empire/server/server.py#L70

**Comment by RitamDey** [comment]
> If anybody encounters the same issue, here you have a temporary solution.
> 
> Changing the following line to `if not os.path.exists('empire/server/data/empire.db'):` seems to be working for me.
> 
> https://github.com/BC-SECURITY/Empire/blob/886e5131d51b082325f57dc0a5c8eeb39fb04fe1/empire/server/server.py#L70

This fix doesn't work! The latest and dev docker images are still broken and so are the manually built ones. Same error

**Comment by fplazar** [comment]
> 
> 
> > If anybody encounters the same issue, here you have a temporary solution.
> > Changing the following line to `if not os.path.exists('empire/server/data/empire.db'):` seems to be working for me.
> > https://github.com/BC-SECURITY/Empire/blob/886e5131d51b082325f57dc0a5c8eeb39fb04fe1/empire/server/server.py#L70
> 
> This fix doesn't work! The latest and dev docker images are still broken and so are the manually built ones. Same error.
> 
> I'm running this on a Manjaro system with Docker 20.10.7

Sorry if I explained it wrong, what I mean is that you can manually change that line to make Empire work in docker.
It is not applied in the code, just a temporary fix if you need it to work.
You must change it manually before building the image or mounting the code as a volume in the latest docker image with -v path/to/code:/empire .

**Comment by kuba00739** [comment]
> If anybody encounters the same issue, here you have a temporary solution.
> 
> Changing the following line to `if not os.path.exists('empire/server/data/empire.db'):` seems to be working for me.
> 
> https://github.com/BC-SECURITY/Empire/blob/886e5131d51b082325f57dc0a5c8eeb39fb04fe1/empire/server/server.py#L70

Works for me too, great job!

**Comment by vinnybod** [comment]
I will have a fix going out for this in the next release. Either 4.1 or 4.0.3. Turns out we don't really need the `database_check_docker()` function at all anymore. It used to be the case (pre 3.0) that calling reset.sh was necessary because it would initialize the database tables. Now Empire generates the tables on startup if no db is found. Until that goes out, the fix mentioned here will get you unstuck.

**Comment by vinnybod** [comment]
We've got working docker builds now starting with v4.1.3
