### ISSUE TITLE
[BUG] Add Redirector to C# Agent

### ISSUE THREAD

**Issue by nightwatchman6455** [BC-SECURITY/Empire#469]
__Note:__ Please fill out all sections (if applicable) and do not delete the below section headers, otherwise the bot will close the issue.

## Empire Version
- Empire 4.0

## OS Information (Linux flavor, Python version)
- OS: Windows
- Python: 

## Describe the bug
When trying to use the redirector listener with the csharp executables, I get the following error on the server log: Unable to determine language of the agent

## To Reproduce
1. Deploy a csharp executable calling back
2. Create a redirector listener using the csharp agent as an internal pivot point.
3. Try to start the listener.
4. Go to the server log and see error

## Expected behavior
Be able to use the csharp agent as a pivot point for the internal redirector.

**Comment by Cx01N** [comment]
Thanks for the reminder. We weren't able to get the redirector functionality added before 4.0 but will work to get that in soon.

**Comment by Cx01N** [comment]
Reviewing the code now and it should be included in 4.3
https://github.com/BC-SECURITY/Empire-Sponsors/pull/255

**Comment by Cx01N** [comment]
Added to 4.3 and released publicly
