### ISSUE TITLE
pip3 vs pip

### ISSUE THREAD

**Issue by Z6543** [BC-SECURITY/Empire#47]
## Empire Version
3.0

## OS Information (Linux flavor, Python version)
Kali Rolling

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
The setup does not install the necessary python3 packages. On my system, pip links to pip2 and not pip3. 

## Screenshot of error, embedded text output, or Pastebin link to the error
Many python3 packages were still missing after running setup.py successfully.

## Any additional information
Running pip3 install -r setup/requirements.txt solved the issue.

**Comment by Hubbl3** [comment]
@Z6543 we are aware of the issue and are working to resolve

**Comment by Hubbl3** [comment]
@Z6543 we are aware of the issue and are working to resolve

**Comment by barrett092** [comment]
even when installed, I get a "TypeError: cannot unpack non-iterable NoneType object"

**Comment by Hubbl3** [comment]
@Z6543 I have pushed a new install.sh to the bug fixes branch that resolves this issue
