### ISSUE TITLE
[BUG] Install break on Ubuntu 20.04.2 LTS

### ISSUE THREAD

**Issue by graylordo** [BC-SECURITY/Empire#470]
__Note:__ Please fill out all sections (if applicable) and do not delete the below section headers, otherwise the bot will close the issue.

## Empire Version
- Empire 4.0.2

## OS Information (Linux flavor, Python version)
- OS: Ubuntu 20.04.2 LTS
- Python: 3.8

## Describe the bug
Tested installation filed on a clear of distro - Ubuntu 20.04.2 LTS 

## To Reproduce

`sudo ./install.sh
Сущ:1 http://ru.archive.ubuntu.com/ubuntu focal InRelease
Пол:2 http://ru.archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Сущ:3 http://archive.canonical.com/ubuntu focal InRelease                                           
Пол:4 http://ru.archive.ubuntu.com/ubuntu focal-backports InRelease [101 kB]
Пол:5 http://ru.archive.ubuntu.com/ubuntu focal-updates/main amd64 DEP-11 Metadata [282 kB]
Пол:6 http://ru.archive.ubuntu.com/ubuntu focal-updates/universe amd64 DEP-11 Metadata [351 kB]                                     
Сущ:7 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu focal InRelease                                                           
Пол:8 http://ru.archive.ubuntu.com/ubuntu focal-updates/multiverse amd64 DEP-11 Metadata [940 B]
Пол:9 http://ru.archive.ubuntu.com/ubuntu focal-backports/universe amd64 DEP-11 Metadata [10,3 kB]
Пол:10 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]                    
Получено 973 kB за 3с (375 kB/s)          
Чтение списков пакетов… Готово
Чтение списков пакетов… Готово
Построение дерева зависимостей       
Чтение информации о состоянии… Готово
Уже установлен пакет wget самой новой версии (1.20.3-1ubuntu1).
Уже установлен пакет sudo самой новой версии (1.8.31-1ubuntu1.2).
sudo помечен как установленный вручную.
Обновлено 0 пакетов, установлено 0 новых пакетов, для удаления отмечено 0 пакетов, и 0 пакетов не обновлено.
NAME="Ubuntu"
[*] Detected Ubuntu 20.04
Сущ:1 http://ru.archive.ubuntu.com/ubuntu focal InRelease
Сущ:2 http://ru.archive.ubuntu.com/ubuntu focal-updates InRelease                                                                          
Сущ:3 http://ru.archive.ubuntu.com/ubuntu focal-backports InRelease                                                                        
Сущ:4 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu focal InRelease                                                                 
Сущ:5 http://archive.canonical.com/ubuntu focal InRelease                                                                                  
Пол:6 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]         
Получено 114 kB за 1с (101 kB/s)          
Чтение списков пакетов… Готово
Чтение списков пакетов… Готово
Построение дерева зависимостей       
Чтение информации о состоянии… Готово
Будут установлены следующие дополнительные пакеты:
  libexpat1-dev libpython3-dev libpython3.8-dev python-pip-whl python3-distutils python3-lib2to3 python3-setuptools python3-wheel
  python3.8-dev zlib1g-dev
Предлагаемые пакеты:
  python-setuptools-doc
Следующие НОВЫЕ пакеты будут установлены:
  libexpat1-dev libpython3-dev libpython3.8-dev python-pip-whl python3-dev python3-distutils python3-lib2to3 python3-pip
  python3-setuptools python3-wheel python3.8-dev zlib1g-dev
Обновлено 0 пакетов, установлено 12 новых пакетов, для удаления отмечено 0 пакетов, и 0 пакетов не обновлено.
Необходимо скачать 7 340 kB архивов.
После данной операции объём занятого дискового пространства возрастёт на 29,1 MB.
Пол:1 http://ru.archive.ubuntu.com/ubuntu focal/main amd64 libexpat1-dev amd64 2.2.9-1build1 [116 kB]
Пол:2 http://ru.archive.ubuntu.com/ubuntu focal-updates/main amd64 libpython3.8-dev amd64 3.8.10-0ubuntu1~20.04 [3 943 kB]
Пол:3 http://ru.archive.ubuntu.com/ubuntu focal/main amd64 libpython3-dev amd64 3.8.2-0ubuntu2 [7 236 B]
Пол:4 http://ru.archive.ubuntu.com/ubuntu focal-updates/universe amd64 python-pip-whl all 20.0.2-5ubuntu1.6 [1 805 kB]
Пол:5 http://ru.archive.ubuntu.com/ubuntu focal-updates/main amd64 zlib1g-dev amd64 1:1.2.11.dfsg-2ubuntu1.2 [155 kB]
Пол:6 http://ru.archive.ubuntu.com/ubuntu focal-updates/main amd64 python3.8-dev amd64 3.8.10-0ubuntu1~20.04 [510 kB]
Пол:7 http://ru.archive.ubuntu.com/ubuntu focal-updates/main amd64 python3-lib2to3 all 3.8.10-0ubuntu1~20.04 [76,3 kB]
Пол:8 http://ru.archive.ubuntu.com/ubuntu focal-updates/main amd64 python3-distutils all 3.8.10-0ubuntu1~20.04 [141 kB]
Пол:9 http://ru.archive.ubuntu.com/ubuntu focal/main amd64 python3-dev amd64 3.8.2-0ubuntu2 [1 212 B]
Пол:10 http://ru.archive.ubuntu.com/ubuntu focal/main amd64 python3-setuptools all 45.2.0-1 [330 kB]
Пол:11 http://ru.archive.ubuntu.com/ubuntu focal/universe amd64 python3-wheel all 0.34.2-1 [23,8 kB]
Пол:12 http://ru.archive.ubuntu.com/ubuntu focal-updates/universe amd64 python3-pip all 20.0.2-5ubuntu1.6 [231 kB]
Получено 7 340 kB за 2с (3 901 kB/s)
Выбор ранее не выбранного пакета libexpat1-dev:amd64.
(Чтение базы данных … на данный момент установлено 169730 файлов и каталогов.)
Подготовка к распаковке …/00-libexpat1-dev_2.2.9-1build1_amd64.deb …
Распаковывается libexpat1-dev:amd64 (2.2.9-1build1) …
Выбор ранее не выбранного пакета libpython3.8-dev:amd64.
Подготовка к распаковке …/01-libpython3.8-dev_3.8.10-0ubuntu1~20.04_amd64.deb …
Распаковывается libpython3.8-dev:amd64 (3.8.10-0ubuntu1~20.04) …
Выбор ранее не выбранного пакета libpython3-dev:amd64.
Подготовка к распаковке …/02-libpython3-dev_3.8.2-0ubuntu2_amd64.deb …
Распаковывается libpython3-dev:amd64 (3.8.2-0ubuntu2) …
Выбор ранее не выбранного пакета python-pip-whl.
Подготовка к распаковке …/03-python-pip-whl_20.0.2-5ubuntu1.6_all.deb …
Распаковывается python-pip-whl (20.0.2-5ubuntu1.6) …
Выбор ранее не выбранного пакета zlib1g-dev:amd64.
Подготовка к распаковке …/04-zlib1g-dev_1%3a1.2.11.dfsg-2ubuntu1.2_amd64.deb …
Распаковывается zlib1g-dev:amd64 (1:1.2.11.dfsg-2ubuntu1.2) …
Выбор ранее не выбранного пакета python3.8-dev.
Подготовка к распаковке …/05-python3.8-dev_3.8.10-0ubuntu1~20.04_amd64.deb …
Распаковывается python3.8-dev (3.8.10-0ubuntu1~20.04) …
Выбор ранее не выбранного пакета python3-lib2to3.
Подготовка к распаковке …/06-python3-lib2to3_3.8.10-0ubuntu1~20.04_all.deb …
Распаковывается python3-lib2to3 (3.8.10-0ubuntu1~20.04) …
Выбор ранее не выбранного пакета python3-distutils.
Подготовка к распаковке …/07-python3-distutils_3.8.10-0ubuntu1~20.04_all.deb …
Распаковывается python3-distutils (3.8.10-0ubuntu1~20.04) …
Выбор ранее не выбранного пакета python3-dev.
Подготовка к распаковке …/08-python3-dev_3.8.2-0ubuntu2_amd64.deb …
Распаковывается python3-dev (3.8.2-0ubuntu2) …
Выбор ранее не выбранного пакета python3-setuptools.
Подготовка к распаковке …/09-python3-setuptools_45.2.0-1_all.deb …
Распаковывается python3-setuptools (45.2.0-1) …
Выбор ранее не выбранного пакета python3-wheel.
Подготовка к распаковке …/10-python3-wheel_0.34.2-1_all.deb …
Распаковывается python3-wheel (0.34.2-1) …
Выбор ранее не выбранного пакета python3-pip.
Подготовка к распаковке …/11-python3-pip_20.0.2-5ubuntu1.6_all.deb …
Распаковывается python3-pip (20.0.2-5ubuntu1.6) …
Настраивается пакет python3-wheel (0.34.2-1) …
Настраивается пакет libexpat1-dev:amd64 (2.2.9-1build1) …
Настраивается пакет libpython3.8-dev:amd64 (3.8.10-0ubuntu1~20.04) …
Настраивается пакет zlib1g-dev:amd64 (1:1.2.11.dfsg-2ubuntu1.2) …
Настраивается пакет python-pip-whl (20.0.2-5ubuntu1.6) …
Настраивается пакет python3-lib2to3 (3.8.10-0ubuntu1~20.04) …
Настраивается пакет python3-distutils (3.8.10-0ubuntu1~20.04) …
Настраивается пакет libpython3-dev:amd64 (3.8.2-0ubuntu2) …
Настраивается пакет python3-setuptools (45.2.0-1) …
Настраивается пакет python3-pip (20.0.2-5ubuntu1.6) …
Настраивается пакет python3.8-dev (3.8.10-0ubuntu1~20.04) …
Настраивается пакет python3-dev (3.8.2-0ubuntu2) …
Обрабатываются триггеры для man-db (2.9.1-1) …
[*] Installing Powershell
Сущ:1 http://ru.archive.ubuntu.com/ubuntu focal InRelease
Сущ:2 http://ru.archive.ubuntu.com/ubuntu focal-updates InRelease                                                                          
Сущ:3 http://ru.archive.ubuntu.com/ubuntu focal-backports InRelease                                                                        
Сущ:4 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu focal InRelease                                                                 
Сущ:5 http://archive.canonical.com/ubuntu focal InRelease                                                                                  
Пол:6 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]                              
Получено 114 kB за 1с (102 kB/s)          
Чтение списков пакетов… Готово
Чтение списков пакетов… Готово
Построение дерева зависимостей       
Чтение информации о состоянии… Готово
Уже установлен пакет wget самой новой версии (1.20.3-1ubuntu1).
Уже установлен пакет software-properties-common самой новой версии (0.98.9.5).
software-properties-common помечен как установленный вручную.
Следующие НОВЫЕ пакеты будут установлены:
  apt-transport-https
Обновлено 0 пакетов, установлено 1 новых пакетов, для удаления отмечено 0 пакетов, и 0 пакетов не обновлено.
Необходимо скачать 4 680 B архивов.
После данной операции объём занятого дискового пространства возрастёт на 162 kB.
Пол:1 http://ru.archive.ubuntu.com/ubuntu focal-updates/universe amd64 apt-transport-https all 2.0.6 [4 680 B]
Получено 4 680 B за 0с (62,6 kB/s)                  
Выбор ранее не выбранного пакета apt-transport-https.
(Чтение базы данных … на данный момент установлено 170595 файлов и каталогов.)
Подготовка к распаковке …/apt-transport-https_2.0.6_all.deb …
Распаковывается apt-transport-https (2.0.6) …
Настраивается пакет apt-transport-https (2.0.6) …
Выбор ранее не выбранного пакета packages-microsoft-prod.
(Чтение базы данных … на данный момент установлено 170599 файлов и каталогов.)
Подготовка к распаковке packages-microsoft-prod.deb …
Распаковывается packages-microsoft-prod (1.0-ubuntu20.04.1) …
Настраивается пакет packages-microsoft-prod (1.0-ubuntu20.04.1) …
Сущ:1 http://ru.archive.ubuntu.com/ubuntu focal InRelease
Сущ:2 http://ru.archive.ubuntu.com/ubuntu focal-updates InRelease                                                                          
Сущ:3 http://ru.archive.ubuntu.com/ubuntu focal-backports InRelease                                                                        
Сущ:4 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu focal InRelease                                                                 
Сущ:5 http://archive.canonical.com/ubuntu focal InRelease                                                                                  
Пол:6 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]                              
Пол:7 https://packages.microsoft.com/ubuntu/20.04/prod focal InRelease [10,5 kB]                      
Пол:8 https://packages.microsoft.com/ubuntu/20.04/prod focal/main amd64 Packages [91,7 kB]
Получено 216 kB за 2с (128 kB/s)    
Чтение списков пакетов… Готово
Компонент выпуска 'universe' уже включен для всех источников.
Чтение списков пакетов… Готово
Построение дерева зависимостей       
Чтение информации о состоянии… Готово
Будут установлены следующие дополнительные пакеты:
  liblttng-ust-ctl4 liblttng-ust0 liburcu6
Следующие НОВЫЕ пакеты будут установлены:
  liblttng-ust-ctl4 liblttng-ust0 liburcu6 powershell
Обновлено 0 пакетов, установлено 4 новых пакетов, для удаления отмечено 0 пакетов, и 0 пакетов не обновлено.
Необходимо скачать 68,6 MB архивов.
После данной операции объём занятого дискового пространства возрастёт на 180 MB.
Пол:1 http://ru.archive.ubuntu.com/ubuntu focal/main amd64 liblttng-ust-ctl4 amd64 2.11.0-1 [80,9 kB]
Пол:2 http://ru.archive.ubuntu.com/ubuntu focal/main amd64 liburcu6 amd64 0.11.1-2 [54,2 kB]                     
Пол:3 http://ru.archive.ubuntu.com/ubuntu focal/main amd64 liblttng-ust0 amd64 2.11.0-1 [160 kB]    
Пол:4 https://packages.microsoft.com/ubuntu/20.04/prod focal/main amd64 powershell amd64 7.1.4-1.ubuntu.20.04 [68,3 MB]
Получено 68,6 MB за 30с (2 291 kB/s)                                                                                                       
Выбор ранее не выбранного пакета liblttng-ust-ctl4:amd64.
(Чтение базы данных … на данный момент установлено 170607 файлов и каталогов.)
Подготовка к распаковке …/liblttng-ust-ctl4_2.11.0-1_amd64.deb …
Распаковывается liblttng-ust-ctl4:amd64 (2.11.0-1) …
Выбор ранее не выбранного пакета liburcu6:amd64.
Подготовка к распаковке …/liburcu6_0.11.1-2_amd64.deb …
Распаковывается liburcu6:amd64 (0.11.1-2) …
Выбор ранее не выбранного пакета liblttng-ust0:amd64.
Подготовка к распаковке …/liblttng-ust0_2.11.0-1_amd64.deb …
Распаковывается liblttng-ust0:amd64 (2.11.0-1) …
Выбор ранее не выбранного пакета powershell.
Подготовка к распаковке …/powershell_7.1.4-1.ubuntu.20.04_amd64.deb …
Распаковывается powershell (7.1.4-1.ubuntu.20.04) …
Настраивается пакет liblttng-ust-ctl4:amd64 (2.11.0-1) …
Настраивается пакет liburcu6:amd64 (0.11.1-2) …
Настраивается пакет liblttng-ust0:amd64 (2.11.0-1) …
Настраивается пакет powershell (7.1.4-1.ubuntu.20.04) …
Обрабатываются триггеры для man-db (2.9.1-1) …
Обрабатываются триггеры для libc-bin (2.31-0ubuntu9.2) …
cp: не удалось выполнить stat для './empire/server/powershell/Invoke-Obfuscation': Нет такого файла или каталога
`

## Expected behavior
See - Additional context

## Additional context
cp: не удалось выполнить stat для './empire/server/powershell/Invoke-Obfuscation': Нет такого файла или каталога

pls fix it

**Comment by vinnybod** [comment]
I have a fix for this coming in the next release. At the moment, that line of the script expects the current working directory to be the root empire directory. So if you are `cd`'d into the setup directory, go up one level and run it like `setup/install.sh`

**Comment by vinnybod** [comment]
Fixed in the latest release
