### ISSUE TITLE
[BUG] Error: <urllib3.connection.HTTPSConnection object at 0x7f0944475c40>

### ISSUE THREAD

**Issue by graylordo** [BC-SECURITY/Empire#472]
__Note:__ Please fill out all sections (if applicable) and do not delete the below section headers, otherwise the bot will close the issue.

## Empire Version
- Empire 4.0.2

## OS Information (Linux flavor, Python version)
- OS: Ubuntu 20.04.2 LTS
- Python: 3.8

## Describe the bug
```
Use the 'connect' command to connect to your Empire server.
'connect -c localhost' will connect to a local empire instance with all the defaults
including the default username and password.
[*] Attempting to connect to server: localhost
[!] Error: <urllib3.connection.HTTPSConnection object at 0x7f0944475c40>: Failed to establish a new connection: [Errno 111] Connection refused
(Empire) >

```

## To Reproduce

```
sudo poetry run python empire.py server
sudo poetry run python empire.py client
```
and i have this:

`Error: <urllib3.connection.HTTPSConnection object at 0x7f0944475c40>: Failed to establish a new connection: [Errno 111] Connection refused`

**Comment by Azteq-Sudo** [comment]
iam facing the same problem 2.

**Comment by vinnybod** [comment]
Closing this out for now, as we haven't been able to reproduce the issue. This error is thrown when the client cannot connect to the server, so please make sure that you have started the server properly. The "autoconnect" setting uses the default username and password, so if you have changed those, you'll need to connect using the `connect` command (type help for the exact parameters) or by [updating the config.yaml](https://bc-security.gitbook.io/empire-wiki/quickstart/configuration#client).
