### ISSUE TITLE
[BUG] TypeError in powershell/management/spawnas module.

### ISSUE THREAD

**Issue by 001SPARTaN** [BC-SECURITY/Empire#480]
## Empire Version
- Empire 4.0.2

## OS Information (Linux flavor, Python version)
- OS: Debian 11
- Python: Python 3.8.10

## Describe the bug
Attempting to use the spawnas module to spawn a new Empire agent with a username and password results in an error message instead of the expected result.

## To Reproduce
1. `usemodule powershell/management/spawnas`
2. Set the correct username, domain name, password, and listener.
3. `execute`
4. See error.

## Screenshots
N/A.

## Additional context
Example output:
```
(Empire: usemodule/powershell/management/spawnas) > set UserName DOMAINUSER
[*] Set UserName to DOMAINUSER
(Empire: usemodule/powershell/management/spawnas) > set Domain DOMAIN.LOCAL
[*] Set Domain to DOMAIN.LOCAL
(Empire: usemodule/powershell/management/spawnas) > set Password myPassword1!
[*] Set Password to myPassword1!
(Empire: usemodule/powershell/management/spawnas) > set Listener http
[*] Set Listener to http
(Empire: usemodule/powershell/management/spawnas) > execute
[!] Error: TypeError("'str' object does not support item assignment")
```

**Comment by Cx01N** [comment]
@001SPARTaN Are you able to provide more detail? I'm testing it right now and unable to reproduce the error.

**Comment by janit0rjoe** [comment]
The setup.sh script does not support Debian 11. So did you install all dependencies manually or did you tweak the script?

**Comment by C-Sto** [comment]
I was seeing this error too, and then eventually managed to crash the CLI with the following error:
```
(Empire: usemodule/powershell/management/runas) > usestager windows/launcher_bat
Traceback (most recent call last):
  File "/Empire/empire.py", line 16, in <module>
    client.start()
  File "/Empire/empire/client/client.py", line 347, in start
    empire.main()
  File "/Empire/empire/client/client.py", line 201, in main
    self.parse_command_line(text, cmd_line)
  File "/Empire/empire/client/client.py", line 252, in parse_command_line
    menu_state.push(self.menus['UseStagerMenu'], selected=cmd_line[1])
  File "/Empire/empire/client/src/MenuState.py", line 22, in push
    if menu.on_enter(**kwargs):
  File "/Empire/empire/client/src/menus/UseStagerMenu.py", line 34, in on_enter
    self.use(kwargs['selected'])
  File "/Empire/empire/client/src/menus/UseStagerMenu.py", line 52, in use
    values = list(map(lambda x: '\n'.join(textwrap.wrap(str(x), width=35)), value.values()))
AttributeError: 'str' object has no attribute 'values'
```
Prior to the crash, I was receiving the same TypeError in the same module, and then started getting that error in the launcher_bat module when running 'execute'
