### ISSUE TITLE
[BUG] Invoke-Obfuscation Missing

### ISSUE THREAD

**Issue by rafnexjm1234** [BC-SECURITY/Empire#489]
__Note:__ Please fill out all sections (if applicable) and do not delete the below section headers, otherwise the bot will close the issue.

## Empire Version
- Empire 4.0.2

## OS Information (Linux flavor, Python version)
- OS: Kali 2021.3
- Python: 2.7.18
- Python3: 3.9.7

## Describe the bug
while waiting to finish the install i saw a bug within the installing session
here i've seen "cp: cannot stat './empire/server/powershell/Invoke-Obfuscation': No such file or directory"

## To Reproduce
I just install the ./install.sh

## Expected behavior
i was expecting not showing that Invoke-Obfuscation while installing ongoing and no bug occured.

## Screenshots
i cant provide due to already done installing and already clear the logs.

## Additional context
i just wonder how did this happen and i copy all the repo then that just happen.

**Comment by Cx01N** [comment]
@rafnexjm1234 I believe we corrected this in 4.1 and should be good. The release will be coming out to the public repo later this week, so let us know if this problem is resolved. I'll keep this issue open just to make sure. Thanks!

**Comment by rafnexjm1234** [comment]
@Cx01N sir i already downloaded the latest and perfectly done without error like missing file. Thank you very much to support!
