### ISSUE TITLE
[BUG] set Outfile results in "name 'file' is not defined"

### ISSUE THREAD

**Issue by Strong-IT-IBK** [BC-SECURITY/Empire#490]
## Empire Version
- Empire 4.1.2 BC Security Fork

## OS Information (Linux flavor, Python version)
- OS: Kali 2021.3, full-upgrade
- Python: 
python --version
Python 2.7.18
python3 --version
Python 3.9.7

## Describe the bug
generating a launcher results in error when "set OutFile" is used

## To Reproduce
usestager multi/launcher
set Listener http
set OutFile /tmp/Launcher.ps1
generate

--> name 'file' is not defined

unset OutFile
generate

--> launcher is created on screen ok

## Expected behavior
launcher file should be created

## Screenshots
-

## Additional context
-

**Comment by Cx01N** [comment]
The issue should be fixed on the Kali/sponsor repo and will hit the public repo this week.
https://github.com/BC-SECURITY/Empire-Sponsors/pull/233
