### ISSUE TITLE
[BUG] powershell/credentials/mimikatz/silver_ticket > Module not accepting 'CredID' value from store

### ISSUE THREAD

**Issue by spookymonkey2020** [BC-SECURITY/Empire#492]
__Note:__ Please fill out all sections (if applicable) and do not delete the below section headers, otherwise the bot will close the issue.

## Empire Version
- Empire 4.1.2

## OS Information (Linux flavor, Python version)
- OS: kali
- Python: 3.9

## Describe the bug
The 'powershell/credentials/mimikatz/silver_ticket' module is not accepting the 'CredID' value from store, therefore the module cannot execute. The error message is "[!] please specify a machine account credential"

## To Reproduce
1. extract domain credentials from Target using 'powershell/credentials/mimikatz/logonpasswords' module into creds store
2. load 'powershell/credentials/mimikatz/silver_ticket' module and set the required parameters including the numeric id value for 'CredID'
3. execute

## Expected behavior
Module should execute without an error.

## Screenshots
![image](https://user-images.githubusercontent.com/88156271/135559608-32a23c25-965a-4211-8fe2-1e7fa9f5d06b.png)

![image](https://user-images.githubusercontent.com/88156271/135559619-38b65321-0745-47bb-883a-d06adee9b5c4.png)

## Additional context
N/A

**Comment by Cx01N** [comment]
@spookymonkey2020 did you try to use 2 or 3? Cred 1 is not a machine account which is what the error is reporting to you.
