### ISSUE TITLE
[BUG] Docker missing Malleable Profiles

### ISSUE THREAD

**Issue by ott0sec** [BC-SECURITY/Empire#497]
__Note:__ Please fill out all sections (if applicable) and do not delete the below section headers, otherwise the bot will close the issue.

## Empire Version
- Empire 4.1.3

## OS Information (Linux flavor, Python version)
Iam launching on docker on ubuntu with docker build <path of empire>

## Describe the bug
 I load correctly the profiles in the server profile path server/data/profiles/ (i know i am launching in docker and i am connecting volumes so its the good folder )and launch the server, I think everything is okay. But on the client side, when i connect to the server and want to use http malleable listener, it gives me the error in the screenshot.

## To Reproduce
once the client is connected to the server:
uselistener http_malleable
set Profile amazon.profile
execute
<python error stderr>

## Expected behavior
I excepted the listener to get up

## Screenshots
![Screenshot from 2021-10-08 01-26-05](https://user-images.githubusercontent.com/46642145/136503390-548b90f9-91e5-446d-8dd1-a7fc00601142.png)

**Comment by vinnybod** [comment]
I tested this with the v4.1.3 container and I'm unable to recreate it. The profiles showed up in both Starkiller and the client and I was able to start a malleable listener.

Can you elaborate on your reproduction instructions? With 4.1.3 you shouldn't need to manually load the profiles, they should already exist in the container.

**Comment by ott0sec** [comment]
Did you put the profile files directly in the folder 'server/data/profiles/' or you put them in a folder in that folder. And did you put them before building the image or after building it? For exemple I want to use amazon.profile from your directory. I literally just 1. git clone your empire repository, 2. extracting the profiles in your repository to server/data/profiles/ folder, 3. building the image with 'sudo docker build Empire/' ,4. sudo docker run -it empire server --username xxx --password xxx,5. connecting to the server 'sudo docker run -it empire client',6. 'connect https://ip_of_docker --username=xxx --password=xxx', 7. 'uselistener http_malleable', 8. 'set Profile amazon.profile', 9.'execute' and then it sows me 'AttributeError("'NoneType' object has no attribute 'data'")'. That pisses me really off because i want to analyze the packet communication with my own crafted profile. Thx
