### ISSUE TITLE
Cannot run ./empire

### ISSUE THREAD

**Issue by dllaboss** [BC-SECURITY/Empire#50]
## Empire Version
3.0.1 (from 'cat VERSION' via Terminal')

## OS Information (Linux flavor, Python version)
Kali-rolling v2019.4
Python 2.7.17 and/or Python 3.7.5

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
When running "./empire" I receive the following error:
Traceback (most recent call last):
  File "./empire", line 14, in <module>
    from lib.common import empire, helpers
  File "/root/Desktop/Empire/lib/common/__init__.py", line 10, in <module>
    from . import helpers
  File "/root/Desktop/Empire/lib/common/helpers.py", line 58, in <module>
    import iptools
ModuleNotFoundError: No module named 'iptools'

According to Kali and "apt install iptools" this module doesn't exist. I can't find python-pip or python3-pip to further try to install "iptools". 

## Screenshot of error, embedded text output, or Pastebin link to the error
![image](https://user-images.githubusercontent.com/18423888/71596862-fd741080-2b0e-11ea-814b-0b846059f040.png)

**Comment by corabrickdog** [comment]
Try running pip3 install -r setup/requirements.txt after ./install.sh as @Z6543 said in #47 :)

**Comment by Hubbl3** [comment]
As @corabrickdog said this is the same issue as #47. I have pushed an update to the bug fixes branch that addresses this and am closing the issue
