### ISSUE TITLE
[BUG] Bat file is not generating

### ISSUE THREAD

**Issue by pranshushakya123** [BC-SECURITY/Empire#509]
__Note:__ Please fill out all sections (if applicable) and do not delete the below section headers, otherwise the bot will close the issue.

## Empire Version
- Empire 3.x

## OS Information (Linux flavor, Python version)
- OS:  kali linux
- Python: 

## Describe the bug
Its  launcher.bat written to /usr/share/powershell-empire/launcher.bat
 But actually it is generated there
![empire error](https://user-images.githubusercontent.com/92092121/139537460-e484be9e-d6a2-4fd4-b646-4d6ed45bcb67.PNG)

**Comment by Cx01N** [comment]
Thank you, a fix will be rolling out in 4.2. The print out isn't showing the full directory, but the file is being generated properly.
https://github.com/BC-SECURITY/Empire-Sponsors/pull/241

**Comment by pranshushakya123** [comment]
Where the file is generated ?
I think It not generated

**Comment by Cx01N** [comment]
The directories should look something like this since Kali had to split where things are saved. 
![Uploading A2885845-C6BF-4AC5-A3FE-2AD6191A9501.png…]()

**Comment by pranshushakya123** [comment]
Where the backdorr will be stored

**Comment by pentest1337** [comment]
you will find stagers in "empire/client/generated-stagers/"
if not exist in this path run this command from empire path 'find ./ -name launcher.bat'

**Comment by nyukers** [comment]
It's true. I can change OutFile to anything but PE tell me that stager written to /home/kali/Desktop/launcher.bat.
And file doesn't exist there.((

**Comment by Biepa** [comment]
I found the file in this directory:
/usr/share/powershell-empire/empire/client/generated-stagers
