### ISSUE TITLE
Error creating linux python payload

### ISSUE THREAD

**Issue by h0nus** [BC-SECURITY/Empire#51]
## Empire Version
3.0.1 BC-Security Fork

## OS Information (Linux flavor, Python version)
Python 3.7.5 ( with python2 i got the default behaviour)
Ubuntu 19.10 x86_64

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
I was expecting the usual base64 encoded python stager launched from bash.
Like: `echo "base64payload" | /usr/bin/python &`
Instead i got an error.

## Screenshot of error, embedded text output, or Pastebin link to the error
**Python3 Error Screenshots**
![img](https://imgur.com/XdDospI.png)
![img](https://imgur.com/bbpZYl6.png)

## Any additional information
Did i used the wrong branch? Or is this a bug?

**Comment by Cx01N** [comment]
@h0nus It appears that the old python launchers will not be compatible with how Python 3 is being implemented. We are working through the issue now, but it may require a major overhaul on how Empire handles python agents.

**Comment by h0nus** [comment]
Yeah, i needed to fix the launcher, but also the connection have errors in handling the staging process.
