### ISSUE TITLE
[BUG] output of Shell CLI wrongly formatted

### ISSUE THREAD

**Issue by danymello** [BC-SECURITY/Empire#510]
__Note:__ Please fill out all sections (if applicable) and do not delete the below section headers, otherwise the bot will close the issue.

## Empire Version
- Empire 4.1.3

## OS Information (Linux flavor, Python version)
- OS: Kali 2021.3
- Python: python 3.9.7 

## Describe the bug
When executing a shell CLI towards an agent, the output is shown in one block of text versus keeping the original output format. This make the output very difficult to read. 

## To Reproduce
1. Interact with an agent
2. Run for example: shell 'wmic qfe get Caption,Description,HotFixID,InstalledOn'
3. look at the output format

## Expected behavior
The is the output in a cmd shell:

`C:\WINDOWS\system32>wmic qfe get Caption,Description,HotFixID,InstalledOn
Caption                                     Description      HotFixID   InstalledOn
http://support.microsoft.com/?kbid=5005539  Update           KB5005539  10/14/2021
https://support.microsoft.com/help/4562830  Update           KB4562830  1/30/2021
http://support.microsoft.com/?kbid=4570334  Security Update  KB4570334  11/18/2020
https://support.microsoft.com/help/4580325  Security Update  KB4580325  11/19/2020
https://support.microsoft.com/help/4586864  Security Update  KB4586864  11/19/2020
https://support.microsoft.com/help/4598481  Security Update  KB4598481  1/30/2021
https://support.microsoft.com/help/5006670  Security Update  KB5006670  10/14/2021
                                            Security Update  KB5005699  9/14/2021`

## Screenshots
This is current ouput for same CLI in empire:
![image](https://user-images.githubusercontent.com/9723812/139747957-9ebcc52c-bc91-4367-a130-c6e0d897187c.png)

## Additional context
This used to be formatted correctly some previous version.

**Comment by Cx01N** [comment]
@danymello thanks for letting us know. I'm going to combine this bug with https://github.com/BC-SECURITY/Empire/issues/491 since they have the same core problem. For now, you can add `|convertto-json` to get a formatted response that should be readable in Empire. Hopefully, we can get a permanent solution in place in the future.
