### ISSUE TITLE
Guide in using tool

### ISSUE THREAD

**Issue by ymgh96** [BC-SECURITY/Empire#511]
Hi
I don't want to report a bug or request a feature!
I have problem in running tool!
I install tool with powershell-empire and from this github. After installing I run the bellow command:
./ps-empire server
and get the bellow terminal
Server >
How can I get the menu?😑
Can anyone guide me?

**Comment by vinnybod** [comment]
@ymgh96 https://bc-security.gitbook.io/empire-wiki/quickstart

**Comment by ymgh96** [comment]
> @ymgh96 https://bc-security.gitbook.io/empire-wiki/quickstart

Thank you for your answering. I read this link before now but I couldn't solve the problem...
The main menu doesn't hit!
