### ISSUE TITLE
[BUG] cant use privesc module.

### ISSUE THREAD

**Issue by ott0sec** [BC-SECURITY/Empire#513]
__Note:__ Please fill out all sections (if applicable) and do not delete the below section headers, otherwise the bot will close the issue.

## Empire Version
- Empire latest that pulls in docker by this date

## OS Information (Linux flavor, Python version)
- ubuntu
default python that comes with the docker image

## Describe the bug
Everything is in the screenshot
## To Reproduce
screenshot

## Additional context
Add any other context about the problem here
![Screenshot from 2021-11-07 23-50-00](https://user-images.githubusercontent.com/46642145/140686109-9eb59495-a3d5-4abb-9a72-e5f7b6f83ea5.png)
.

**Comment by ott0sec** [comment]
Does this error means I need to correct myself the python module so it works with the empire version? If yes, in the server side or client side?

**Comment by Cx01N** [comment]
@ott0sec Can you please be more descriptive and provide the details for the required fields?

**Comment by ott0sec** [comment]
You use the same module on a windows agent and its done.

**Comment by Cx01N** [comment]
This module doesn't work on windows.
Please fill out the form above if you require any more assistance.
