### ISSUE TITLE
[BUG] Error: module needs to run in an elevated context.

### ISSUE THREAD

**Issue by nyukers** [BC-SECURITY/Empire#516]
__Note:__ Please fill out all sections (if applicable) and do not delete the below section headers, otherwise the bot will close the issue.

## Empire Version
- Empire 4.3.1

## OS Information (Linux flavor, Python version)
- OS: Debian 5.10.13
- Python: 2.7.18
- Python3:  3.9.7

## Describe the bug
Using module **Disable_rdp** or **Enable_rdp** I have msg "Error: module needs to run in an **elevated context**." by "execute".

## Expected behavior
How can I take such elevation with Empire client?

**Comment by Cx01N** [comment]
@nyukers That message is intentional, you will need to migrate to a high integrity process.
