### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by scapegoat314** [BC-SECURITY/Empire#517]
__Note:__ Please fill out all sections (if applicable) and do not delete the below section headers, otherwise the bot will close the issue.

## Empire Version
- Empire 4.2

## OS Information (Linux flavor, Python version)
- OS: Kali Linux 
- Python: Python 3.9.8

## Describe the bug
I have installed Empire 4.2 but there is an Error when I run it. I encountered the following error

[!] Error: <urllib3.connection.HTTPSConnection object at 0x7fa62dd20640>: Failed to establish a new connection: [Errno 111] Connection refused

I searched everything. What is the problem? python3-urllib3 is installed. I don't understand. You can check the attached pic. I can't connect local host. I googled everything and nothing works. If you support me, i appreciate 

## To Reproduce

After installation, I run "powershell-empire client". However, it gives the following error
Use the 'connect' command to connect to your Empire server.
'connect -c localhost' will connect to a local empire instance with all the defaults
including the default username and password.
[*] Attempting to connect to server: localhost
[!] Error: <urllib3.connection.HTTPSConnection object at 0x7f4d626a55b0>: Failed to establish a new connection: [Errno 111] Connection refused
(Empire) >

## Expected behavior
I just expect it running

## Screenshots
![Screenshot_2021-11-24_21-41-03](https://user-images.githubusercontent.com/16303851/143489136-4617ee29-061f-4a1d-9cec-46c67eb2122f.png)

**Comment by vinnybod** [comment]
Discussed over discord: Need to run the server before trying to run the client
