### ISSUE TITLE
[BUG] Displays wrong location for saved stager

### ISSUE THREAD

**Issue by bishop527** [BC-SECURITY/Empire#518]
__Note:__ Please fill out all sections (if applicable) and do not delete the below section headers, otherwise the bot will close the issue.

## Empire Version
- Empire 4.1.3

## OS Information (Linux flavor, Python version)
- OS: Kali Linux
- Python: 2.7.18

## Describe the bug
When I created windows/launcher_bat stager the message showing where the stager was saved is wrong.
It says "[*] launcher.bat written to /opt/Empire/launcher.bat"
It was actually saved to /opt/Empire/empire/client/generated-stagers

## To Reproduce
1. From within empire client type 'usestager windows/launcher.bat'
2. Set the listener value
3. execute
4. Message displays the wrong value.

## Expected behavior
After execute the message should show the correct location for where the stager was saved

## Screenshots
![image](https://user-images.githubusercontent.com/1160292/143619222-6b44bb67-7685-47fd-8af9-05d6d657e403.png)

**Comment by Cx01N** [comment]
This should be fixed in 4.2 which is currently available to Kali/Sponsors and will go public in about a week.
