### ISSUE TITLE
500 on Client handling and Payload incorrect

### ISSUE THREAD

**Issue by h0nus** [BC-SECURITY/Empire#52]
## Empire Version
3.0.1 BC-Security Fork

## OS Information (Linux flavor, Python version)
Ubuntu 19.10 x86_64
Python 2.7.17 (because using Python3 results in failing to generate payload for *nix)

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
It should handle the connection, but instead gives a 500 error and fails to send second stager.
Also the payload generate had some lines at wrong position, and to make it work i needed to fix the code under base64 encoding. (Not an issue at all, but this shouldn't happen)

## Screenshot of error, embedded text output, or Pastebin link to the error
![img](https://imgur.com/gMSAGWY.png)
![img](https://imgur.com/4tOKfC3.png)

## Any additional information
I don't know, to be honest.

**Comment by Hubbl3** [comment]
@h0nus can you provide a little more information? Which nix payload were you trying generate? Also it looks like you sent an exit command in the middle of a negotiation

**Comment by Cx01N** [comment]
Same issue as #51.
