### ISSUE TITLE
[BUG] powershell-empire server does not start

### ISSUE THREAD

**Issue by zero13ro** [BC-SECURITY/Empire#524]
__Note:__ Please fill out all sections (if applicable) and do not delete the below section headers, otherwise the bot will close the issue.

## Empire Version
- Empire 4.2  

## OS Information (Linux flavor, Python version)
- OS:  Kali 2021.4a bare metal ISO
- Python: 3.9.9

## Describe the bug

sudo powershell-empire server generate errors, all the requirements are installed and kali is up to date (apt update & upgrade)

## To Reproduce
powershell-empire server
powershell-empire client

## Expected behavior
tool should start without any errors

## Screenshots

![empire](https://user-images.githubusercontent.com/4076539/147566294-c28d6359-e4e3-49f6-8872-23daab698e36.png)

**Comment by BuildAndDestroy** [comment]
It looks like the issue is found here on line 667, we are calling a function in the Class:
```
/usr/lib/python3/dist-packages/aiohttp/helpers.py

class CeilTimeout(async_timeout.timeout):            <--- This guy
    def __enter__(self) -> async_timeout.timeout:
        if self._timeout is not None:
            self._task = current_task(loop=self._loop)
            if self._task is None:
                raise RuntimeError(
                    "Timeout context manager should be used inside a task"
                )
            now = self._loop.time()
            delay = self._timeout
            when = now + delay
            if delay > 5:
                when = ceil(when)
            self._cancel_handler = self._loop.call_at(when, self._cancel_task)
        return self
```

Since we are not using this function anywhere else outside of the Class, I just removed it. PowerShell-Empire starts as expected.
```
class CeilTimeout():
    def __enter__(self) -> async_timeout.timeout:
        if self._timeout is not None:
            self._task = current_task(loop=self._loop)
            if self._task is None:
                raise RuntimeError(
                    "Timeout context manager should be used inside a task"
                )
            now = self._loop.time()
            delay = self._timeout
            when = now + delay
            if delay > 5:
                when = ceil(when)
            self._cancel_handler = self._loop.call_at(when, self._cancel_task)
        return self

```

I did test on a clean build of Kali as well as upgrades, all are hitting the same error. Hopefully this helps until a fix is approved.

**Comment by zero13ro** [comment]
yup, that the annoying guy :) tested and working. many thanks @BuildAndDestroy
