### ISSUE TITLE
[BUG] powershell-empire client no connect to powershell-empire server

### ISSUE THREAD

**Issue by k4n4n** [BC-SECURITY/Empire#531]
__Note:__ Please fill out all sections (if applicable) and do not delete the below section headers, otherwise the bot will close the issue.

## Empire Version
- Empire 4

## OS Information (Linux flavor, Python version)
- OS: Kali Linux 2021.4a
- Python: 3

## Describe the bug
Powershell-empire client no connect to Powershell-empire server.

## To Reproduce
1. Go to 'sudo powershell-empire server --user empireadmin --pass Password123!'
2. Click on 'sudo powershell-empire client '
3. Scroll down to in powershell-empire client console

## Expected behavior
powershell-empire client connect correctly to powershell-empire server API REST.

## Screenshots
![Captura](https://user-images.githubusercontent.com/43685859/148214182-c49f9734-1f77-433c-b2e4-ff7218297cf8.PNG)

## Additional context
The version of Kali Linux and python, and the binaries of powershell-empire are correctly updated at last version.

**Comment by Cx01N** [comment]
@k4n4n actually, your command updates the login info, so you’ll need to change the login info for the client to match. Otherwise, if you remove the username and password, it should auto connect.

**Comment by Cx01N** [comment]
@k4n4n were you able to get Empire running? If not, let us know and we can reopen the issue.
