### ISSUE TITLE
[Bug] Docker-compose.yml not working

### ISSUE THREAD

**Issue by chb1828** [BC-SECURITY/Empire#536]
__Note:__ Please fill out all sections (if applicable) and do not delete the below section headers, otherwise the bot will close the issue.

## Empire Version
- Empire 4.33

## OS Information (Linux flavor, Python version)
- OS: Windows
- Python: 

## Describe the bug
I ran the docker command below as per that documentation.
`docker run -it -p 1337:1337 -p 5000:5000 bcsecurity/empire:latest`
The above command works fine. However, if I change the above command to the form of docker-compose.yml as below, it does not work.
```
version: '3.3'
services:
  server:
    image: bcsecurity/empire:latest
    ports:
      - "1337:1337"
      - "5000:5000"
```

## To Reproduce
1. Install docker.
2. Create a docker-compose.yml file with the same contents as above in the folder.
3. Execute the 'docker-compose up' command and check the log.

## Expected behavior
I am getting an error like the screenshot below.

## Screenshots
![image](https://user-images.githubusercontent.com/55731606/151476356-a7c8854b-16bd-48be-acc9-f3b4e785a1d3.png)
![image](https://user-images.githubusercontent.com/55731606/151476402-2629960d-d508-4afb-b9f8-725060228571.png)

## Additional context
Additionally, I want to run the server and the client at the same time through docker-compose.
```
docker run -it -p 1337:1337 -p 5000:5000 bcsecurity/empire:latest
docker run -it -p 1337:1337 -p 5000:5000 bcsecurity/empire:latest client
```
How can I open the above two images through docker-compose?
I don't know where to put the last 'client' in line 2 in docker-compose.yml.

Any help would be appreciated.

**Comment by vinnybod** [comment]
`python-prompt-toolkit` is the cause of the operation not permitted error. In the future, I think we should add a `--non-interactive` flag that turns it off on the server. This should be simple enough to get it into the next release.

For now, if you add these to your docker-compose file in the `server` block, the server should start up properly.
```
    stdin_open: true
    tty: true
```

As for running the client from docker-compose, I'm not sure that it is possible to get it to work properly.
You can however run
`docker ps` to get the running container's id and then run `docker exec -it {container_id} ./ps-empire client` to run the client off the same container.

**Comment by chb1828** [comment]
@vinnybod 
It works fine. Thanks for your help.
It would be nice to have this information documented so that others can know.

**Comment by vinnybod** [comment]
docker-compose should work fine now. There's an example at https://github.com/BC-SECURITY/Empire-Launcher/tree/dev
