### ISSUE TITLE
[BUG] Module search over API not working

### ISSUE THREAD

**Issue by WhyNotPal** [BC-SECURITY/Empire#540]
## Empire Version
- Empire 4.3.3 BC Security Fork 

## OS Information (Linux flavor, Python version)
- OS: kali 2021.1
- Python: 3.9.1

## Describe the bug
A API request to search module fails - it returns the error 
{"error":"AttributeError(\"'PydanticModule' object has no attribute 'info'\")"}

## To Reproduce
1. Launch powershell-empire on Kali (here with IP 192.168.3.4)
2. From remote machine, aquire authentication token and store in environment variable $TOKEN
3. Request a module search according to https://bc-security.gitbook.io/empire-wiki/restful-api/modules
4. curl --insecure -i -H "Content-Type: application/json"  https://192.168.3.4:1337/api/modules/search?token=$TOKEN -d '{"term":"keylogger"}'

## Expected behavior
A list of modules matching a specific string is expected (here keylogger)

## Screenshots
![image](https://user-images.githubusercontent.com/66071761/153844928-6e3bb37c-6f39-4576-9cbc-0f09755b6882.png)

## Additional context
Nope

**Comment by lavafroth** [comment]
It looks like the code at https://github.com/BC-SECURITY/Empire/blob/master/empire/server/server.py#L596 looks for the info attribute of the module but it isn't defined in https://github.com/BC-SECURITY/Empire/blob/master/empire/server/common/module_models.py#L33
