### ISSUE TITLE
[BUG] Launching a module over the API - all the options MUST be defined

### ISSUE THREAD

**Issue by WhyNotPal** [BC-SECURITY/Empire#541]
__Note:__ Please fill out all sections (if applicable) and do not delete the below section headers, otherwise the bot will close the issue.

## Empire Version
- Empire 4.3.3 BC Security Fork

## OS Information (Linux flavor, Python version)
- OS: Kali 2021.1
- Python: 3.9.1

## Describe the bug
When launching a Module over the API, all the options must be sent, or an error message is returned, even for the options with a default value. 

## To Reproduce
1. Launch powershell-empire server, launch listener, create appropriate stager and launch stager on target machine
2. Acquire authentication token and store into environment variable $TOKEN
3. Request module launch over API according to https://bc-security.gitbook.io/empire-wiki/restful-api/modules, while not sending all options values, for instance: 
![image](https://user-images.githubusercontent.com/66071761/153846808-9d78ed2c-5053-4828-9ecc-d762768d5c4d.png)
The mandatory options 'Agent' and 'Listener' are defined in the data dictionary - the option 'ObfuscateCommand' (which has a default value) is not. 
The module is launched correctly if ALL the options are defined in the data dictionary of the API request.

## Expected behavior
The module should use the default value where none are sent over the API request - and be launched. These default values are set and known, as can be checked by getting the module by name. 

## Screenshots
See above

## Additional context
None

**Comment by vinnybod** [comment]
This isn't quite a bug, more just how the API is designed.

For listeners and stagers, those default values are not static because each request modifies the same underlying object instance. That used to be the case with modules until of 4.0, but we kept the API the same.

In the v2 API that is being developed, the default values will be static across the board, so we can make what you are suggesting the norm for that.

**Comment by vinnybod** [comment]
This is the case for the new API: https://bc-security.gitbook.io/empire-wiki/restful-api
