### ISSUE TITLE
[BUG] 'remove stale agent' API does not actually remove the stale agents

### ISSUE THREAD

**Issue by WhyNotPal** [BC-SECURITY/Empire#542]
__Note:__ Please fill out all sections (if applicable) and do not delete the below section headers, otherwise the bot will close the issue.

## Empire Version
- Empire 4.3.3 BC Security Fork 

## OS Information (Linux flavor, Python version)
- OS: kali 2021.1
- Python: 3.9.1

## Describe the bug
The 'remove stale agents' API does not work. Calling 
(according to https://github.com/EmpireProject/Empire/wiki/RESTful-API#get-stale-agents )
   ` curl --insecure -i https://192.168.3.4:1337/api/agents/stale?token=$TOKEN -X DELETE`
returns 
   `{"success":true}`
However, after deleting all the stale agents, requesting the stale agents returns the full list of stale agents, where they should have been removed from the DB.

## To Reproduce
1. launch server - deploy Listener, create stager, deploy stager  to create agent
2. Kill agent
3. request list of stale agents -> returns the one stale agent
4. request removal of all agents -> returns success
5. request list of stale agents -> still returns the one stale agent

## Expected behavior
I would expect the step 5. to return an empty list. 

## Screenshots
Nope

## Additional context
Nope

**Comment by vinnybod** [comment]
Looks like we need a filter for `models.Agent.killed == False` on that end point. At some point we switched to soft-deletes on agents, which is probably when this started happening.
https://github.com/BC-SECURITY/Empire/blob/master/empire/server/server.py#L884

**Comment by lavafroth** [comment]
@vinnybod, this issue looks safe to be closed.
