### ISSUE TITLE
[BUG] Nim installation fails on Ubuntu due to package dependency failure

### ISSUE THREAD

**Issue by havocsh** [BC-SECURITY/Empire#546]
__Note:__ Please fill out all sections (if applicable) and do not delete the below section headers, otherwise the bot will close the issue.

## Empire Version
- Empire 4.3.3

## OS Information (Linux flavor, Python version)
- OS: Ubuntu 20.04 LTS 
- Python: 3.8

## Describe the bug
Installer fails when building nim and mingw for nim stagers. The nim package is installed using apt, which installs nim 1.0.6-1 but zippy is installed by pulling the latest from github, which has a nim requirement >= 1.0.10. This leads to a unsatisfied dependency error.

Configuring...
--
984 | --------------
985 | A command is running to populate your local package cache to improve restore speed and enable offline access. This command takes up to one minute to complete and only runs once.
986 | [>] Do you want to install Nim and MinGW? It is only needed to generate a Nim stager (y/N)?
987 | WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
988 |  
989 | Reading package lists...
990 | Building dependency tree...
991 | Reading state information...
992 | Suggested packages:
993 | nim-doc
994 | The following NEW packages will be installed:
995 | nim
996 | 0 upgraded, 1 newly installed, 0 to remove and 1 not upgraded.
997 | Need to get 2991 kB of archives.
998 | After this operation, 12.2 MB of additional disk space will be used.
999 | Get:1 http://archive.ubuntu.com/ubuntu focal/universe amd64 nim amd64 1.0.6-1 [2991 kB]
1000 | debconf: unable to initialize frontend: Dialog
1001 | debconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)
1002 | debconf: falling back to frontend: Readline
1003 | debconf: unable to initialize frontend: Readline
1004 | debconf: (This frontend requires a controlling tty.)
1005 | debconf: falling back to frontend: Teletype
1006 | dpkg-preconfigure: unable to re-open stdin:
1007 | Fetched 2991 kB in 1s (3317 kB/s)
1008 | Selecting previously unselected package nim.
1009 | (Reading database ...
1010 | (Reading database ... 5%
1011 | (Reading database ... 10%
1012 | (Reading database ... 15%
1013 | (Reading database ... 20%
1014 | (Reading database ... 25%
1015 | (Reading database ... 30%
1016 | (Reading database ... 35%
1017 | (Reading database ... 40%
1018 | (Reading database ... 45%
1019 | (Reading database ... 50%
1020 | (Reading database ... 55%
1021 | (Reading database ... 60%
1022 | (Reading database ... 65%
1023 | (Reading database ... 70%
1024 | (Reading database ... 75%
1025 | (Reading database ... 80%
1026 | (Reading database ... 85%
1027 | (Reading database ... 90%
1028 | (Reading database ... 95%
1029 | (Reading database ... 100%
1030 | (Reading database ... 27570 files and directories currently installed.)
1031 | Preparing to unpack .../archives/nim_1.0.6-1_amd64.deb ...
1032 | Unpacking nim (1.0.6-1) ...
1033 | Setting up nim (1.0.6-1) ...
1034 | Prompt: No local packages.json found, download it from internet? -> [forced yes]
1035 | Downloading Official package list
1036 | Success Package list downloaded.
1037 | Downloading https://github.com/khchen/winim using git
1038 | Verifying dependencies for winim@3.8.0
1039 | Installing winim@3.8.0
1040 | Success: winim installed successfully.
1041 | Downloading https://github.com/guzba/zippy using git
1042 | Verifying dependencies for zippy@0.9.3
1043 | Tip: 89 messages have been suppressed, use --verbose to show them.
1044 | Error: Unsatisfied dependency: nim (>= 1.0.10)
1045 | The command '/bin/sh -c printf "y\ny\ny\ny\n" \| ./setup/install.sh' returned a non-zero code: 1

## To Reproduce
1. Run the installer script on Ubuntu 20.04.
2. Enter 'y' when prompted [>] Do you want to install Nim and MinGW? It is only needed to generate a Nim stager (y/N)?

## Expected behavior
The installer should successfully install the nim and mingw packages and associated dependencies.

**Comment by vinnybod** [comment]
Fixed in 4.6.0
