### ISSUE TITLE
Upload command - binary file type issue

### ISSUE THREAD

**Issue by Z6543** [BC-SECURITY/Empire#55]
## Empire Version
3.0.1 

## OS Information (Linux flavor, Python version)
Kali, Python 3.7.5

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

Uploading binary files should result in the same file being uploaded. Text file uploading works perfectly. Binary file upload removes some bytes from the file, thus rendering the file unusable.

**Comment by Hubbl3** [comment]
I just pushed a fixed to the upload_fix branch. The fix will be merged into master at the next release. Closing the issue for now
