### ISSUE TITLE
[BUG] Error: Unsatisfied dependency: nim (>= 1.0.10) ubunut 20.04

### ISSUE THREAD

**Issue by tehseensagar** [BC-SECURITY/Empire#553]
__Note:__ Please fill out all sections (if applicable) and do not delete the below section headers, otherwise the bot will close the issue.

## Empire Version
- Empire 4.4.x

## OS Information (Linux flavor, Python version)
- OS:  Ubunut 20.04
- Python:  3.8.10

## Describe the bug
Error occurred using installation 

`[>] Do you want to install Nim and MinGW? It is only needed to generate a Nim stager (y/N)? y
Reading package lists... Done
Building dependency tree       
Reading state information... Done
nim is already the newest version (1.0.6-1).
0 upgraded, 0 newly installed, 0 to remove and 223 not upgraded.
Downloading https://github.com/khchen/winim using git
  Verifying dependencies for winim@3.8.0
 Installing winim@3.8.0
    Prompt: winim@3.8.0 already exists. Overwrite? -> [forced yes]
   Success: winim installed successfully.
Downloading https://github.com/guzba/zippy using git
  Verifying dependencies for zippy@0.9.7
       Tip: 87 messages have been suppressed, use --verbose to show them.
     Error: Unsatisfied dependency: nim (>= 1.0.10)
`

## To Reproduce

    git clone --recursive https://github.com/BC-SECURITY/Empire.git
    cd Empire
    ./setup/install.sh
    See error above

**Comment by Cx01N** [comment]
Closing due to duplicate of https://github.com/BC-SECURITY/Empire/issues/546
