### ISSUE TITLE
[BUG] Error bypassuac

### ISSUE THREAD

**Issue by ho-ri-2** [BC-SECURITY/Empire#554]
__Note:__ Please fill out all sections (if applicable) and do not delete the below section headers, otherwise the bot will close the issue.

## Empire Version
- Empire 4.4.1

## OS Information (Linux flavor, Python version)
- OS: Ubuntu 20.04.3 LTS
- Python: 3.9.10

## Describe the bug
Error occurred using powershell/privesc/bypassuac
(Empire: usemodule/powershell/privesc/bypassuac) > execute
[!] Error: NameError("name 'proxyCreds' is not defined")

## To Reproduce
(Empire) > listeners
(Empire: listeners) > uselistener http
(Empire: uselistener/http) > set Port 8080
(Empire: uselistener/http) > execute
(Empire: uselistener/http) > listeners
(Empire: listeners) > usestager windows/launcher_bat
(Empire: usestager/windows/launcher_bat) > set Listener http
(Empire: usestager/windows/launcher_bat) > execute
(Empire: usestager/windows/launcher_bat) > agents
(Empire: agents) > interact K8RS4M97
(Empire: K8RS4M97) > usemodule powershell/privesc/bypassuac
(Empire: usemodule/powershell/privesc/bypassuac) > set Listener http
(Empire: usemodule/powershell/privesc/bypassuac) > execute
[!] Error: NameError("name 'proxyCreds' is not defined")

## Expected behavior
Successful execution

**Comment by Cx01N** [comment]
@ho-ri-2 Thanks! I was able to push a fix for the next release. Just FYI, I was able to get the module to run on Windows 10, but not Windows 11.

**Comment by ho-ri-2** [comment]
@Cx01N Thank you for your reply.My environment is below.
Host OS:Windows10 , Hypervisor:VirtualBOX6.1.22
