### ISSUE TITLE
[BUG] - <urllib3.connection.HTTPSConnection object at 0x7faafc6218b0

### ISSUE THREAD

**Issue by hamzanadeem44** [BC-SECURITY/Empire#562]
__Note:__ Please fill out all sections (if applicable) and do not delete the below section headers, otherwise the bot will close the issue.

## Empire Version
- Empire 4.4.1

## OS Information (Linux flavor, Python version)
- OS: kali-rolling 2021.4
- Python: 3.9.9

## Describe the bug
After installing the powershell-empire using 
```
 apt install powershell-empire starkiller
```

## To Reproduce
1. Go to ``cd /usr/share/powershell-empire``
2. Execute ``python3 empire.py client``

```
Use the 'connect' command to connect to your Empire server.
'connect -c localhost' will connect to a local empire instance with all the defaults
including the default username and password.
[*] Attempting to connect to server: localhost
[!] Error: <urllib3.connection.HTTPSConnection object at 0x7faafdf39bb0>: Failed to establish a new connection: [Errno 111] Connection refused
(Empire) > connect -c localhost
[!] Error: <urllib3.connection.HTTPSConnection object at 0x7faafce51f70>: Failed to establish a new connection: [Errno 111] Connection refused
(Empire) > connect -c localhost --username empireadmin --password password123
[!] Error: <urllib3.connection.HTTPSConnection object at 0x7faafc6218b0>: Failed to establish a new connection: [Errno 111] Connection refused
(Empire) > quit
(Empire) > exit
[>] Exit? [y/N] y
```
## Expected behavior
It should be automatically connect to the powershell-empire server.

## Additional Note
Please guide how to fix this error. Thanks in advance.

**Comment by yash882004** [comment]
same error

**Comment by c0d3x27** [comment]
same error

**Comment by c0d3x27** [comment]
same error
