### ISSUE TITLE
[BUG] Error starting listeners: 'ProfileSerialized'

### ISSUE THREAD

**Issue by y2kade** [BC-SECURITY/Empire#571]
__Note:__ Please fill out all sections (if applicable) and do not delete the below section headers, otherwise the bot will close the issue.

## Empire Version
- Empire 4.1.3

## OS Information (Linux flavor, Python version)
- OS:  Ubuntu 21.10 (5.13.0-21)
- Python:  3.9.7

## Describe the bug
When I start up the Empire server using the './ps-empire server' command.  My listeners fail to start with the following error: 
[!] Error starting listener: 'Profile Serialized'

I also cannot remove and recreate the 3 listeners via the Starkiller interface or via curl through the API. 

## To Reproduce
1.  Launch Empire using the following command: ./ps-empire server

## Expected behavior
The listeners were functional and would load correctly prior to a reboot of the system hosting Empire.

## Screenshots
![empire_error](https://user-images.githubusercontent.com/42455082/163461717-cf0ada33-a09e-481b-9dcd-3f7dc701b799.png)

**Comment by Cx01N** [comment]
You didn't mention which listeners but it looks like you are trying to restart the malleable listener. 

Unfortunately, this listener does some special configurations that are stored in memory so a server restart will kill the listener and require the server to be reset. Also, it's important to note that admire has a similar limitation that cobalt strike does and is limited to 1 malleable listener.

**Comment by Cx01N** [comment]
Here is a link to the docs on the Mallealable listeners, I don't see a mention of the reset limitation so I'll see if I can get it added so .
https://bc-security.gitbook.io/empire-wiki/listeners/malleable-c2

**Comment by y2kade** [comment]
> Here is a link to the docs on the Mallealable listeners, I don't see a mention of the reset limitation so I'll see if I can get it added so . https://bc-security.gitbook.io/empire-wiki/listeners/malleable-c2

Yeah... these are malleable listeners.  I'll check out the link and try resetting the server to remove each of the listeners.  I appreciate the support!   Cheers.

**Comment by Cx01N** [comment]
No problem. Feel free to hit us up on our discord if you need any help. The community is really knowledgable and friendly. Good luck!
