### ISSUE TITLE
[BUG] Download task on csharp agent not working

### ISSUE THREAD

**Issue by fdelnin** [BC-SECURITY/Empire#572]
## Empire Version
- Empire 4.4.1

## OS Information (Linux flavor, Python version)
- OS: Kali
- Python: 3.9

## Describe the bug

The download task does not work on csharp agents.

## To Reproduce

1. Open an agent using a windows/csharp_exe stager
2. Task a download from starkiller GUI, empire API or empire client
3. The task fails without messages on the agent (there is a fail message on the server)

## Expected behavior

Download of a file/folder, or error message if file is not found.

## Screenshots

Server output:

![server_output](https://user-images.githubusercontent.com/23015874/164042663-eb77fe5d-c92a-4605-9635-732cef4dde0c.jpg)

Starkiller output:

![starkiller_output](https://user-images.githubusercontent.com/23015874/164042980-7d66c3a3-48cf-49f6-8c8b-777405e6e605.jpg)

## Additional context

The issue is in Sharpire Empire.Agent.Coms.cs and Empire.Agent.cs files.

The proposed fix is [here](https://github.com/BC-SECURITY/Sharpire/pull/1)

**Comment by Cx01N** [comment]
Thanks, I'll take a look and see if we can get this into the next release.
