### ISSUE TITLE
[FEATURE REQUEST] Unattended setup

### ISSUE THREAD

**Issue by tbennett6421** [BC-SECURITY/Empire#581]
__Note:__ Please fill out all sections (if applicable) and do not delete the below section headers, otherwise the bot will close the issue.

## Is your feature request related to a problem? Please describe.
I'd like to implement Empire into my automated build scripts

## Describe the solution you'd like
I'd love a way to run the setup with an answer file or with flags in such a way that it can be an unattended installation

## Describe alternatives you've considered
N/A

## Additional context
N/A

**Comment by tbennett6421** [comment]
As I have time I will look into a PR possibly

**Comment by vinnybod** [comment]
https://github.com/BC-SECURITY/Empire/pull/639/files
