### ISSUE TITLE
no module tkinter

### ISSUE THREAD

**Issue by alainlankers** [BC-SECURITY/Empire#583]
__Note:__ Please fill out all sections (if applicable) and do not delete the below section headers, otherwise the bot will close the issue.

## Empire Version
- Empire 3.x

Empire4

## OS Information (Linux flavor, Python version)
- OS: 
- Python: 

Debian 10
python 3.7.3

## Describe the bug

When running ./ps-empire client then error appears: 

[*] Loading default config
Traceback (most recent call last):
  File "empire.py", line 16, in <module>
    import empire.client.client as client
  File "/opt/Empire/empire/client/client.py", line 17, in <module>
    from empire.client.src.EmpireCliState import state
  File "/opt/Empire/empire/client/src/EmpireCliState.py", line 2, in <module>
    from tkinter import *
  File "/usr/local/lib/python3.8/tkinter/__init__.py", line 36, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'

## To Reproduce
1. Go to 'Empire'
2. run ./ps-empire client
3. See error

## Expected behavior
running of empire

## Screenshots
no screenshots

## Additional context
./ps-empire server is running fine

I checked and tkinter is already installed on my system. But the error is still there.

**Comment by Cx01N** [comment]
What version of empire are you running? Have you tried to run the install script?

**Comment by vinnybod** [comment]
`tkinter` is now optional starting in 4.7.0. Also added instructions to the wiki on how to deal with this problem: https://bc-security.gitbook.io/empire-wiki/quickstart/installation#modulenotfounderror-no-module-named-_tkinter
