### ISSUE TITLE
[BUG] unexpected char '$' at 3108 while generating dropbox listener

### ISSUE THREAD

**Issue by eaglefn** [BC-SECURITY/Empire#598]
__Note:__ Please fill out all sections (if applicable) and do not delete the below section headers, otherwise the bot will close the issue.

## Empire Version
- Empire 4.7.1

## OS Information (Linux flavor, Python version)
- OS: Kali Linux 2022.1
- Python: 3.10.5

## To Reproduce
1. Go to empire client
2. Click on  uslistener dbx
3. set APIToken <Token received from Dropbox>
4. execute  and see error in the server console

## Expected behavior
Listener starts and can be used

## Screenshots
<img width="1167" alt="error" src="https://user-images.githubusercontent.com/64377595/183291831-7d4b0e96-a3fe-4e96-bcdc-6626e4172970.png">

## Additional context
Same error with docker image on Ubuntu 20.4 and Python 3.8

**Comment by Cx01N** [comment]
The dropbox listener should work with the most recent patch in 4.7.3. Please let me know if you run into any additional issues.
