### ISSUE TITLE
'Exception': a bytes-like object is required

### ISSUE THREAD

**Issue by 0xskywalker** [BC-SECURITY/Empire#60]
## Empire Version
3.0 BC-Security Fork

## OS Information (Linux flavor, Python version)

OS: Ubuntu 18.04 bionic
Python 3.6.9

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

when trying to generate a multi/macro, the following failure is encountered

(Empire: stager/multi/macro) > execute
[!] Exception: a bytes-like object is required, not 'str'

**Comment by Sa1riil** [comment]
Hello, i confirm this for windows/dll; windows/shell; 

OS Information: Linux parrot 5.4.0-1parrot1-amd64 #1 SMP Parrot 5.4.6-1parrot1 (2019-12-30) x86_64 GNU/Linux
Python 3.7.5

**Comment by Hubbl3** [comment]
@0xskywalker I just pushed a commit to the 3.0.1-bug-fixes branch that corrects the problem. 

@Sa1riil I tried those stagers with the update as well and I didn't see any errors

**Comment by 0xskywalker** [comment]
@Hubbl3 i just confirmed your fix, it worked. Thanks!

**Comment by vinnybod** [comment]
This was also released yesterday as part of 3.0.2
