### ISSUE TITLE
[BUG] windows/launcher_bat stager won't connect to listener, multiple parameters missing

### ISSUE THREAD

**Issue by havocsh** [BC-SECURITY/Empire#600]
## Empire Version
- Empire 4.7.1

## OS Information (Linux flavor, Python version)
- OS: Any
- Python: Any

## Describe the bug
When using a windows/launcher_bat stager, it fails to connect to an http_malleable listener (I didn't test other listener types). Using the multi/launcher stager connects to the same listener without issue.

Also, when generating the windows/launcher_bat stager, the following parameters are missing:
- StagerRetries
- UserAgent
- Proxy
- ProxyCreds

Maybe it was intentional and unrelated to the stager not connecting to the listener but the above parameters are missing from self.options in launcher_bat.py, while other Windows launchers still have the parameters: https://github.com/BC-SECURITY/Empire/blob/master/empire/server/stagers/windows/launcher_bat.py

## To Reproduce
See bug description above.

## Expected behavior
Was expecting the windows/launcher_bat stager payload to successfully connect to the listener. Was also expecting to have configurable options for StagerRetries, UserAgent, Proxy, and ProxyCreds.

## Screenshots
N/A

## Additional context
N/A

**Comment by havocsh** [comment]
The "UserAgent," "Proxy," and "ProxyCreds" parameters are also missing for this stager.

**Comment by Cx01N** [comment]
Unfortunately, there were some issues trying to get some of the additional functionality working with the bat stager and the malleable listener so this warning was added https://github.com/BC-SECURITY/Empire/blob/6c10bfcf849b603b0bb3afbfdc12091546bd67e6/empire/server/stagers/windows/launcher_bat.py#L15. I recommend generating a multi/launcher and creating the file manually for now.

**Comment by havocsh** [comment]
Thanks for pointing that out, @Cx01N. I'll close out the issue.
