### ISSUE TITLE
[BUG] multi/bash stager successful initial connection but immediately dies

### ISSUE THREAD

**Issue by Jackrin** [BC-SECURITY/Empire#614]
__Note:__ Please fill out all sections (if applicable) and do not delete the below section headers, otherwise the bot will close the issue.

## Empire Version
- Empire 4.8.0

## OS Information (Linux flavor, Python version)
- OS: Linux kali 5.18.0-kali7-amd64
- Python: 3.10.6

## Describe the bug
When using the **multi/bash** stager the stager successfully connects to the server, but then it immediately dies and I'm not able to send any command.
After a while the client throws this error: `main() exception: module 'urllib' has no attribute 'quote`', which is weird because **quote** is never used, also the syntax of other libraries look correct.
To run the stager I use `bash stager.sh`

Edit: Don't remember the profile I used today, but I've used two different profiles in two different days and got the same error.

## To Reproduce
1. Create listener, in my case it was **http_malleable** on port **80**
2. Select **multi/bash** as the stager **without** encryption, bypasses.
3. Run the stager on the client.
4. Connection not established, client only reaches the server for the initial connection and information share about the system.

## Expected behavior
The stager should open a connection between the client and the server.

## Screenshots
None are necessary.

## Additional context
No additional context is necessary

**Comment by Cx01N** [comment]
Which malleable profile were you using for the comms and does that error occur when using another malleable profile?

**Comment by Cx01N** [comment]
Unfortunately, without more info, we are not going to be able to fix the issue. I tested things based on the info provided and did not find an issue.
<img width="560" alt="image" src="https://user-images.githubusercontent.com/20302208/190170748-625e7f2f-6ec7-413e-a0de-e942d68e10f9.png">

**Comment by Jackrin** [comment]
> Unfortunately, without more info, we are not going to be able to fix the issue. I tested things based on the info provided and did not find an issue. <img alt="image" width="560" src="https://user-images.githubusercontent.com/20302208/190170748-625e7f2f-6ec7-413e-a0de-e942d68e10f9.png">

I did more tests, used **meterpreter** profile, used multi/bash, with safe check off and with mattifestation bypass.
I ran the script, it called back and the server sent stage 2, after that, the terminal where the script was run started throwing this error again: `main() exception: module 'urllib' has no attribute 'quote'`.
After this I was not able to interact with the client.
I don't really know what other information I could give you, maybe you could give me some suggestion on what data would help you to understand my problem.
![Immagine 2022-09-14 215338](https://user-images.githubusercontent.com/15637352/190250451-959d546f-e706-411e-8303-7819e917fd30.png)

**Comment by Cx01N** [comment]
Actually, that is perfect. I know exactly where the issue is now and can get started on a patch. Thank you.

**Comment by Jackrin** [comment]
> Actually, that is perfect. I know exactly where the issue is now and can get started on a patch. Thank you.

Just asking, is there a reason why you could run it? Is there a specific configuration that would work even without the patch?

**Comment by Cx01N** [comment]
My standard script to test things is using the amazon and apt10 profiles. Each profile is different, so they may not touch the same functions. So it's a good chance I never updated those functions with a python agent since those are not used as often as the PowerShell agents.

**Comment by Cx01N** [comment]
Empire 5.5 has a revamp of the malleable profiles and should resolve all the Python agent issues.

**Comment by Jackrin** [comment]
Closing, if ever needed a new issue will be better.
