### ISSUE TITLE
[BUG] The python/persistence/multi/crontab module fails to add the cron job.

### ISSUE THREAD

**Issue by Jackrin** [BC-SECURITY/Empire#615]
__Note:__ Please fill out all sections (if applicable) and do not delete the below section headers, otherwise the bot will close the issue.

## Empire Version
- Empire 4.8.0

## OS Information (Linux flavor, Python version)
- OS: Linux kali 5.18.0-kali7-amd64
- Python: 3.10.6

## Describe the bug
The **python/persistence/multi/crontab** module fails to add the cron job.

Attached the starkiller console output.
No output from server and client.

## To Reproduce
Used malleable **amazon** profile.
Used **multi/bash** as stager.
Sent **python/persistence/multi/crontab** module, with **hour** set to a value.
Cron job is not added, checked by **crontab -l**

## Expected behavior
The crontab should be executed and you should be able to check the presence of the job by  **crontab -l**

## Screenshots
![Immagine 2022-09-19 213836](https://user-images.githubusercontent.com/15637352/191102018-40e68df6-79a5-455d-b9f0-8108b7798de7.png)

## Additional context
No additional context is necessary

**Comment by Cx01N** [comment]
I pushed a fix out in 4.8.3, let me know if that resolves your problem.

**Comment by Jackrin** [comment]
I updated and I'm facing another error when executing the crontab.

Error: **[!] Error: module requires PS version 3.8 but agent running PS version 3.1**

I've looked at he code to see what was causing this and it is caused the lines from **312** to **318** of **/empire/server/common/modules.py**

Not really sure how the code works in relation to other components but it looks like it's comparing the version of PowerShell even when it shouldn't (at least that's what the comment says), because the module works with python and the agent is a Linux machine.

**Comment by Jackrin** [comment]
Isseue resolved by this PR: https://github.com/BC-SECURITY/Empire/pull/629
