### ISSUE TITLE
[BUG] ImcompleteRead on large scripts

### ISSUE THREAD

**Issue by man715** [BC-SECURITY/Empire#624]
__Note:__ Please fill out all sections (if applicable) and do not delete the below section headers, otherwise the bot will close the issue.

## Empire Version
- Empire 4.8.1

## OS Information (Linux flavor, Python version)
- OS: Kali
- Python: 3.10.8

## Describe the bug
When running the module 'python/privesc/linux/linux_priv_checker', the target system displays the following error:
`main() exception: IncompleteRead(11925 bytes read, 13881 more expected)`

I also attempted the same thing with a module I created to run linpeas and get a similar error: `main() exception: IncompleteRead(65536 bytes read, 762350 more expected)`

The target system is DISTRIB_DESCRIPTION="Ubuntu 20.04.4 LTS" running python 3.8.10

I also tried the same thing on the Kali host and got the same errors.

## To Reproduce
1. Go to the target agent
2. Click on 'Execute Module'
3. Scroll down to 'python/privesc/linux/linux_priv_checker'
4. Click 'Submit'
5. See error

## Expected behavior
I would expect to see the output from the given script.

## Screenshots
Output in starkiller:
![image](https://user-images.githubusercontent.com/23712890/199974339-c60dff8e-a730-4a6b-976a-a68952713fcb.png)
Output on target:
![image](https://user-images.githubusercontent.com/23712890/199974741-a1813228-9b9e-4fa9-b811-33f0fa3508ca.png)

## Additional context
The test target is 'Faculty' on HTB.

**Comment by Cx01N** [comment]
I pushed a fix out in 4.8.3, let me know if that resolves your problem.

**Comment by man715** [comment]
@Cx01N That took care of it. Thank you.
