### ISSUE TITLE
[BUG] HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /BC-SECURITY/donut.git/info/refs?service=git-upload-pack (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])"))) 

### ISSUE THREAD

**Issue by IsaiahStanke** [BC-SECURITY/Empire#632]
__Note:__ Please fill out all sections (if applicable) and do not delete the below section headers, otherwise the bot will close the issue.

## Empire Version
- Empire 4.8.3

## OS Information (Linux flavor, Python version)
- OS: Ubuntu 20.04
- Python: 3.8.10

## Describe the bug
The bug says exactly as follows "**HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /BC-SECURITY/donut.git/info/refs?service=git-upload-pack (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))"**

## To Reproduce
1. cd /opt
2. sudo git clone https://github.com/BC-SECURITY/Empire.git
3. cd Empire
4. sudo ./setup/install.sh
5. See error

## Expected behavior
A clean and simple install

## Screenshots
![empireerror](https://user-images.githubusercontent.com/83856624/203020531-f75f7dbc-0844-4feb-95a7-52684cb3399b.png)

## Additional context
It happens halfway through the installation. I choose "Y" on every question about installing a tool to do something.

**Comment by Jackrin** [comment]
It looks like your "requests" library is outdated.

`pip3 install requests`
or
`pip3 install --upgrade requests`
