### ISSUE TITLE
[BUG] "Error: <urllib3.connection.HTTPSConnection object at 0x7efdc6ef91c0>: Failed to establish a new connection: [Errno 111] Connection refused"

### ISSUE THREAD

**Issue by IsaiahStanke** [BC-SECURITY/Empire#633]
__Note:__ Please fill out all sections (if applicable) and do not delete the below section headers, otherwise the bot will close the issue.

## Empire Version
- Empire 4.8.3

## OS Information (Linux flavor, Python version)
- OS: Ubuntu 20.04
- Python: 3.8.10

## Describe the bug
I come up with tan errorafter loading into the shell, it says "Error: <urllib3.connection.HTTPSConnection object at 0x7efdc6ef91c0>: Failed to establish a new connection: [Errno 111] Connection refused".

## To Reproduce
1. Run the command, "./ps-empire client"
2. Load into shell
3. See second error

## Expected behavior
A clean load into the shell

## Screenshots
Error 1:

![empireerror3](https://user-images.githubusercontent.com/83856624/203122429-261d66ba-311a-46f4-a69f-34b9cc27da2a.png)

## Additional context
Previously had an error saying "HTTPSConnectionPool(host='github.com', port=443": Max retires exceeded with url: /BC-Security/donut.git/info/refs?service......." while trying to install Empire so I opened an issue and got it fixed by upgrading my requests package with "pip3 install --upgrade requests". I have made sure urllib3 is up to date, it is v1.26.12

Edit: This post previously contained two errors, one of them being Empire did not see or recognize the module Tkinter - after reading further documentation, I was able to fix it. I am still having the error about "urllib3".

**Comment by Jackrin** [comment]
Have you started the server with `./ps-empire server` first?

That error means that there is something wrong with the destination address `localhost`, which would be the case if the server was not started.
