### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by slayerhacker** [BC-SECURITY/Empire#641]
i installed empire in my kali machine ,it is installed successfully but when i try to run empire this type error occurs
![Screenshot from 2023-01-19 13-39-20](https://user-images.githubusercontent.com/122613947/213618219-e2c5262f-403a-4390-b2bf-c0d03fcc2e76.png)
THANK YOU..!

**Comment by Cx01N** [comment]
Please fill out the bug template and provide some additional information with a title.
https://github.com/BC-SECURITY/Empire/issues/new?assignees=&labels=bug&template=bug_report.md&title=%5BBUG%5D
