### ISSUE TITLE
creds command produces exception

### ISSUE THREAD

**Issue by Davewarrington** [BC-SECURITY/Empire#65]
## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

Issuing Creds Command produces "[!] Exception: 'str' object has no attribute 'decode'" 

## Any additional information
Could be my build.. not really sure.

**Comment by Hubbl3** [comment]
@Davewarrington  can you give me some more context? were you interacting with an agent or was it from a specific menu? had you run a module such as invoke-mimikatz prior to the error? 

I have been able to reproduce this

**Comment by Davewarrington** [comment]
hey @Hubbl3 .

If i load empire, from scratch, nothing configured, and run creds . I receive the error.
If i try to add creds it's the same issue.
creds display seems to work ok. however, as expected it's blank. 

Attached SS.

![image](https://user-images.githubusercontent.com/16097102/72203955-60986800-346a-11ea-9859-fe81fcb25f7f.png)

![image](https://user-images.githubusercontent.com/16097102/72203964-8f164300-346a-11ea-8350-6df39aca32cb.png)

**Comment by vinnybod** [comment]
@Hubbl3 I can verify after attempting to add a credential, I get an error on the `creds` command in both python2 and python3

**Comment by Hubbl3** [comment]
@Davewarrington I pushed a commit to 3.0.2-bug-fixes that addresses the problem let me know if that doesn't fix it for you

**Comment by Davewarrington** [comment]
Did a clean pull on the 3.02 and install .. first run .. 

Traceback (most recent call last):
  File "empire", line 1426, in <module>
    main = empire.MainMenu(args=args)
  File "/opt/Empire/lib/common/empire.py", line 114, in __init__
    self.listeners = listeners.Listeners(self, args=args)
  File "/opt/Empire/lib/common/listeners.py", line 43, in __init__
    self.load_listeners()
  File "/opt/Empire/lib/common/listeners.py", line 68, in load_listeners
    self.loadedListeners[listenerName] = imp.load_source(listenerName, filePath).Listener(self.mainMenu, [])
  File "/opt/Empire//lib/listeners/http.py", line 450
    <<<<<<< HEAD
     ^
SyntaxError: invalid syntax

**Comment by Hubbl3** [comment]
@Davewarrington it looks like something went wrong when we did a merge earlier today. I am trying to figure out what happened

**Comment by Hubbl3** [comment]
@Davewarrington we missed a conflict clean up when merging. If you re-pull Empire it should be working now
