### ISSUE TITLE
[BUG] PSRansom Broken

### ISSUE THREAD

**Issue by TrentonTait** [BC-SECURITY/Empire#652]
## Empire Version
- Latest Version

## OS Information (Linux flavor, Python version)
- OS:  kali
- Python: 3.10

## Describe the bug
PSRansom fails to generate script. 

## To Reproduce
Create a new task on an agent using powershell_exfiltration_psransom and fill out required options.

## Expected behavior
PSRansom task is generated and executed on the agent.

## Additional context
INFO]: 127.0.0.1:45864 - "POST /api/v2/agents/YEV42R5D/tasks/module/ HTTP/1.1" 400 
[ERROR]: Error generating script: 'MainMenu' object has no attribute 'modules' 
Traceback (most recent call last):
  File "/home/kali/Empire/empire/server/core/module_service.py", line 257, in _generate_script
    return module.advanced.generate_class.generate(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Empire/empire/server/modules/powershell/exfiltration/PSRansom.py", line 20, in generate
    script, err = main_menu.modules.get_module_source(
                  ^^^^^^^^^^^^^^^^^
AttributeError: 'MainMenu' object has no attribute 'modules'

**Comment by Cx01N** [comment]
Should work again in 5.0.4. Let us know if you are still having an issue.
