### ISSUE TITLE
Not able to extract latest Docker image

### ISSUE THREAD

**Issue by eaglefn** [BC-SECURITY/Empire#654]
## Empire Version
- Empire 5.04

## OS Information (Linux flavor, Python version)
- OS:  Ubuntu 22.04
- Python: Python 3.10

## Describe the bug
Not able to extract latest Docker image

## To Reproduce
1. Pull docker image:

docker pull bcsecurity/empire:latest
latest: Pulling from bcsecurity/empire
b2404786f3fe: Pull complete 
e97ef50ee5a8: Pull complete 
dfb1477a1a0e: Pull complete 
838447eff6a7: Pull complete 
61f659024e30: Pull complete 
0a27566d127a: Pull complete 
58459a6d66cd: Pull complete 
c861cbca92b2: Pull complete 
eb2cfa2506ba: Pull complete 
4f22ecc88f66: Pull complete 
6e53d632fc18: Pull complete 
0d12f558c9d1: Pull complete 
63d7e54687b3: Extracting [==================================================>]  268.3MB/268.3MB
9b5462987f2a: Download complete 
2f91ed51a33b: Download complete 
9dc2198654df: Download complete 
failed to register layer: ApplyLayer exit status 1 stdout:  stderr: unlinkat /usr/local/lib/python3.11/site-packages/pkg_resources/_vendor/pyparsing/diagram: invalid argument

2. See error

## Expected behavior
Pull and extract docker image without problems.

**Comment by vinnybod** [comment]
This doesn't appear to still be an issue, can you confirm?

**Comment by eaglefn** [comment]
Yes, no issue anymore.
