### ISSUE TITLE
[BUG] - API doesnt provide a token

### ISSUE THREAD

**Issue by webhead404** [BC-SECURITY/Empire#656]
Hello, using Kali rolling and Empire 5.0.4 I see that behaviors have changed slightly but I think I have accounted for it and found a bug. I'm using curl for the below example.

## Empire Version
- Empire 5.x

## OS Information (Linux flavor, Python version)
- OS: Kali Rolling
- Python: 3.11

## Describe the bug

When running a POST to `/token` with JSON formatted data it displays a message from uvicorn stating that the username and password fields are required.

## To Reproduce
1. install powershell-empire via the docs for Kali
2. Run `powershell-empire server`
3. Run `curl localhost:1337/token -X POST -H "Content-Type: application/json -d '{"username":"empireadmin","password":"password123"}`

## Expected behavior
Should display a JWT token for future requests.

## Additional context
This cropped up via an automated script that stages Empire, however with this bug that failed.

**Comment by vinnybod** [comment]
This isn't quite a bug. The login `POST` request should be sent as a form.

You can see an example of the request by using the devtools network tab in your browser while logging in with Starkiller or when logging in via Swagger UI (http://localhost:1337/docs#/)

```
curl 'http://localhost:1337/token' -X POST -H 'Accept: application/json, text/plain, */*' -H 'Content-Type: application/x-www-form-urlencoded' --data-raw 'grant_type=password&username=empireadmin&password=password123'
```
