### ISSUE TITLE
ModuleNotFoundError: No module named 'Crypto' HELP me please

### ISSUE THREAD

**Issue by vlados31999** [BC-SECURITY/Empire#658]
Traceback (most recent call last):
  File "/home/user/opt/Empire/empire.py", line 11, in <module>
    import empire.server.server as server
  File "/home/user/opt/Empire/empire/server/server.py", line 17, in <module>
    from empire.server.common import empire
  File "/home/user/opt/Empire/empire/server/common/empire.py", line 38, in <module>
    from . import agents, credentials, listeners, stagers
  File "/home/user/opt/Empire/empire/server/common/agents.py", line 62, in <module>
    from . import encryption, helpers, packets
  File "/home/user/opt/Empire/empire/server/common/encryption.py", line 32, in <module>
    from Crypto.Cipher import PKCS1_v1_5
ModuleNotFoundError: No module named 'Crypto'

**Comment by ytza** [comment]
I had a similar issue when the program was loading. It seems there is crypto and cryptodome, pycryptodome, pycryptodomex. My issue was that it said no module named 'Cryptodome'. I edited the code and changed it to "From Crypto.Cipher" instead of "From Cryptodome.Cipher". Perhaps if you change the entry to Cryptodome, or one of the other options, it will work.

**Comment by vlados31999** [comment]
Friend, can you write in which file you need to change? 
Thanks

**Comment by ytza** [comment]
It depends on your error output. Looking at yours it's the encryption.py and it will have a line with "from Crypto.Cipher".

**Comment by vlados31999** [comment]
Friend, thank you 
I see this entry from 

Crypto.Cipher import PKCS1_v1_5

What should I rename it to??Thanks

**Comment by vlados31999** [comment]
Now here is the error 

ModuleNotFoundError: No module named 'Cryptodome'

**Comment by lavafroth** [comment]
Try running the following:

```
pip3 uninstall crypto 
pip3 uninstall pycrypto 
pip3 install pycryptodome
```

**Comment by vlados31999** [comment]
Friends 
Thank you all for your help
Empire launched, there were a lot of errors
Now the client freezes after the uselisteners command and any others

![empire](https://user-images.githubusercontent.com/104201717/227742976-5f04dde4-a101-4ee3-bd4a-f67c5fb55a37.JPG)

**Comment by vlados31999** [comment]
It works via the web

**Comment by Cx01N** [comment]
Glad it's working, I'm going to close this topic out and you can open a new issue if the client is having some issues.
