### ISSUE TITLE
Starkiller not found in Kali 

### ISSUE THREAD

**Issue by hastalamuerte** [BC-SECURITY/Empire#660]
https://github.com/BC-SECURITY/Starkiller/issues/80

**Comment by vinnybod** [comment]
>As of Empire 5.0 and Starkiller 2.0, you no longer need to install Starkiller or build it from source. It is prepackaged in Empire as a submodule and served via Empire's API.

**Comment by hastalamuerte** [comment]
> >As of Empire 5.0 and Starkiller 2.0, you no longer need to install Starkiller or build it from source. It is prepackaged in Empire as a submodule and served via Empire's API.

Perfect , can you plz tell how to reach strakiller from Kali . I provide methods I use to try. Can't found anything in manuals or instructions, video guides
