### ISSUE TITLE
[BUG] Missing Submodule for Malleable Profiles

### ISSUE THREAD

**Issue by muraii** [BC-SECURITY/Empire#664]
__Note:__ Please fill out all sections (if applicable) and do not delete the below section headers, otherwise the bot will close the issue.

## Empire Version
- Empire 5.1.2

## OS Information (Linux flavor, Python version)
- OS: Kali kali-rolling
- Python: 3.11.2

## Describe the bug
- Malleable profiles directory missing after install.
- 0 modules currently loaded after install.

## To Reproduce
Followed instructions here to install: https://bc-security.gitbook.io/empire-wiki/quickstart/installation#github

Run `./ps-empire server` and on the step "Loading malleable profiles from: /usr/share/powershell-empire/empire/server/data/profiles/" get a `FileNotFoundError` raised because `/usr/share/powershell-empire/empire/server/data/profiles/` doesn't exist.

I created the missing directory and launched both server and client. Have "0 modules currently loaded" according to the client. Terminated both, then ran `./ps-empire client --reset` and spun both server and client back up. 0 modules. Repeated but instead reset the server, and spun both back up. 412 modules currently loaded.

## Expected behavior
Empire installed and fully configured.

## Additional context
I had previously installed Empire v4.x via `apt` on Kali, then `apt remove`d it, then installed following the "Github" directions.

**Comment by Cx01N** [comment]
Did you clone the project down recursively?

**Comment by muraii** [comment]
> Did you clone the project down recursively?

It's been so long but I _think_ I had. I've since rectified it, so we can close this issue.

**Comment by muraii** [comment]
No longer an issue.
