### ISSUE TITLE
[BUG] Keyword Obfuscation Not Working on windows_generate_agent

### ISSUE THREAD

**Issue by Arszilla** [BC-SECURITY/Empire#671]
## Empire Version
- Empire 5.4.2

## OS Information (Linux flavor, Python version)
- OS: Kali Linux
- Python: 3.11

## Describe the bug
Despite having `Keyword Obfuscation` configured on Empire (via Starkiller Web UI), the obfuscation does not apply to `windows_generate_agent` file.

## To Reproduce
1. Create any listener. I used `http`.
2. Create a `windows_generate_agent` stager.
3. Generate stager
4. Observe that the stager does not have `Invoke-Empire` substituted with whatever was placed for `Invoke-Empire` in `Keyword Obfuscation`

## Expected behavior
`windows_generate_agent` to obfuscate keywords declared in `Keyword Obfuscation`

## Screenshots
N/A

## Additional context
N/A

**Comment by Cx01N** [comment]
Should be resolved with this fix: https://github.com/BC-SECURITY/Empire-Sponsors/pull/645
