### ISSUE TITLE
[BUG]--restip parameter has no effect

### ISSUE THREAD

**Issue by SeeNanshaneisurely** [BC-SECURITY/Empire#672]
__Note:__ Please fill out all sections (if applicable) and do not delete the below section headers, otherwise the bot will close the issue.

## Empire Version
kali.2023.1 Bring your own

## OS Information (Linux flavor, Python version)
- OS: kali.2023.1
- Python: Python 3.11.2 

## Describe the bug
--restip parameter has no effect

## To Reproduce
powershell-empire server --restip 10.10.0.27

## Expected behavior
How to make empire start on the internal network

## Screenshots
![image](https://github.com/BC-SECURITY/Empire/assets/57738442/ee3cb133-0d5e-4e17-90c7-169a0a322f28)

**Comment by vinnybod** [comment]
https://github.com/BC-SECURITY/Empire/commit/e46e61ae407006f81a96029489b53d8a1ecbea5f
