### ISSUE TITLE
fresh install, cannot run ./empire or ./setup/reset.sh

### ISSUE THREAD

**Issue by rossiV1** [BC-SECURITY/Empire#69]
## Empire Version
3.0 (yet to run cause of error)

## OS Information (Linux flavor, Python version)
Ubuntu 18.04, python 3.6.9

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

upon running ./empire empire server cannot start due to error.
error is as 
> sqlite3.OperationalError: no such table: config

when trying to reset using ./setup/reset.sh did not find builtins module

## Screenshot of error, embedded text output, or Pastebin link to the error

![Screenshot from 2020-01-13 17-43-57](https://user-images.githubusercontent.com/37831634/72246127-0d224780-362d-11ea-9b37-604179620ae1.png)
![Screenshot from 2020-01-13 17-44-58](https://user-images.githubusercontent.com/37831634/72246134-0f84a180-362d-11ea-9ec9-3a4c54b6df21.png)
![Screenshot from 2020-01-13 17-45-36](https://user-images.githubusercontent.com/37831634/72246144-127f9200-362d-11ea-832d-eeaa492f7907.png)

**Comment by Hubbl3** [comment]
@rossiV1  are you using the docker install or just a git clone? and was this a new install of Ubuntu or an old one?

I just tried doing a new install on a Kali box and it worked fine. I will test ubuntu later today

**Comment by rossiV1** [comment]
i am just using the git clone. and it is a fresh install of Ubuntu 18.04.

**Comment by vinnybod** [comment]
I just attempted reproducing on `ubuntu:18.04` docker image. After running `apt-get update && apt-get install sudo lsb-release wget`, I ran `install.sh` and was able to run empire using `./empire` I also ran the reset script with no issue.

It seems like your machine might just be missing the future module. I common fix for `No module named builtins` is to run a `pip install future`.

I also recommend running empire with `python empire` or `python3 empire` so you are explicit with which version you are trying to use.

**Comment by rossiV1** [comment]
actually i have encounter this problem twice. both fresh install of ubuntu 18.04.
and the first time it happened, i manage to resolve it, i think it was related to future module. but i still cannot start ./empire at the first time. but manage to run reset.sh.

after i read @vinnybod post above, i tried running pip install future, pip3 install future, apt-get install python3-future. then i reran ./empire still failed. then i tried reset.sh. it manage to reset by asking for new key. and currently ./empire can be run.

Not sure what happened.

**Comment by vinnybod** [comment]
`future` isn't currently in the `requirements.txt`, somehow it hasn't been needed for our tested use cases. We should see about getting that added then.

**Comment by rossiV1** [comment]
on the other hand, in include other requirements that i need to install before successfully running ./empire

    ./empire 
    pip3 install flask
    ./empire 
    pip3 install iptools
    ./empire 
    pip3 install simplejson
    pip3 install setuptools
    pip3 install simplejson
    ./empire 
    pip3 install pydispatch
    ./empire 
    apt-get -y install python3-pydispatch
    ./empire 
    pip3 install zlib_wrapper
    ./empire 
    pip3 install M2Crypto
    apt-get install python3 python-dev python3-dev      build-essential libssl-dev libffi-dev      libxml2-dev libxslt1-dev zlib1g-dev      python3-pip
    pip3 install M2Crypto
    ./empire 
    pip3 install macholib
    ./empire 
    pip3 install pefile
    ./empire 
    ./setup/reset.sh 
    ./setup/install.sh 
    ./setup/reset.sh 
    ./empire 

This is what i encounter for ubuntu 18.04.

**Comment by vinnybod** [comment]
Sorry, I'm trying to understand the codeblock you posted. you manually ran that apt-get and all those pip install commands? 

Those python libraries are all in the requirements.txt and should be installed by the install script [here](https://github.com/BC-SECURITY/Empire/blob/master/setup/install.sh#L167)

**Comment by rossiV1** [comment]
yeah, i manually ran those codeblock as when i run ./empire it shows no module of above

**Comment by vinnybod** [comment]
Okay, I only tried this out in an ubuntu docker container, so when I have a chance I'll get a proper VM spun up and test it out.

In the meantime, if you have the output of your initial install.sh and post it at a gist here on github, that might be useful to investigate. It sounds to me like your initial install may have failed and quit short of running pip and apt-get.

**Comment by rossiV1** [comment]
sorry i did not save the output of the initial install.sh. if i work on a fresh install again i will post it.
