### ISSUE TITLE
Error while executing the Server for the first time and not running[BUG] <title>

### ISSUE THREAD

**Issue by wajeh98** [BC-SECURITY/Empire#692]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Empire Version

5.5.4

### Python Version

3.10.7

### Operating System

kali linux 

### Database

MySQL

### Current Behavior

Error while executing the Server for the first time and not running and show error message bad requset , code 400
![Screenshot from 2023-08-25 07-16-04](https://github.com/BC-SECURITY/Empire/assets/37579322/2bf7af3a-f948-4c1b-ace3-3a9570abac0d)
![Screenshot from 2023-08-25 07-16-04](https://github.com/BC-SECURITY/Empire/assets/37579322/d3a1c6f9-47b3-4dbd-96ac-51dc0f55204d)

### Expected Behavior

when i run powershell- empire server should work fine and show no bug or error message

### Steps To Reproduce

first run powershell-empire
1-cd empire 
2-./ps-empire server
3- then this bugs show with error message 
![Screenshot from 2023-08-24 18-09-29](https://github.com/BC-SECURITY/Empire/assets/37579322/eb519744-5055-4411-ba86-3e6b89bf9cb2)

**Comment by Cx01N** [comment]
Is your server accessible from the internet? It looks like it is being scanned, but these messages shouldn't cause any issues with how Starkiller performs.
