### ISSUE TITLE
[BUG] Error in powershell-empire tool

### ISSUE THREAD

**Issue by Choukair** [BC-SECURITY/Empire#697]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Empire Version

6.0.400

### Python Version

3.11.4

### Operating System

kali linux

### Database

MySQL

### Current Behavior

I am trying to run a server on Powershell Empire. When I run this command "sudo powershell-epire server" it takes approximately more than 3 minutes, and in the end it tells me "Uvicorn running on http://0.0.0.0:1337 (Press CTRL+C to quit) "I don't know the reason. I want a quick solution to open a server because I have a lot of urgent work and I need a solution as soon as possible.

### Expected Behavior

I expect to open a server, to know very important data, including the number of targets who opened the files I create, and also the listening sessions...

### Steps To Reproduce

open kali terminal
sudo powershell-empire server
[WARNING]: Plugin csharpserver does not support db session or user_id, falling back to old method 
Uvicorn running on http://0.0.0.0:1337 (Press CTRL+C to quit)

### Anything else?

![powershell-empire error](https://github.com/BC-SECURITY/Empire/assets/106698677/fd70a264-778d-496b-888e-6243ba73ed94)

**Comment by Cx01N** [comment]
Actually, there isn't an error, you just need to use one of the clients. Here are the docs for you to check out.
https://bc-security.gitbook.io/empire-wiki/
