### ISSUE TITLE
[BUG] Install issue (module 'six' has no attribute 'ensure_str')

### ISSUE THREAD

**Issue by ne0YT** [BC-SECURITY/Empire#701]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Empire Version

checkout-latest-tag.sh

### Python Version

Python 3.10.12

### Operating System

ubuntu 22.04

### Database

SQLite

### Current Behavior

while installing

equirement already satisfied: more-itertools in /usr/lib/python3/dist-packages (from jaraco.classes->keyring<25.0.0,>=24.0.0->poetry) (8.10.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[*] Installing Packages
Installing dependencies from lock file

Package operations: 116 installs, 1 update, 0 removals

  • Installing pycparser (2.21): Pending...
  • Installing webencodings (0.5.1): Failed

  AttributeError

  module 'six' has no attribute 'ensure_str'

  at /usr/lib/python3/dist-packages/urllib3/util/url.py:296 in _normalize_host
      292│                     return host[:start].lower() + zone_id + host[end:]
      293│                 else:
      294│                     return host.lower()
      295│             elif not IPV4_RE.match(host):
    → 296│                 return six.ensure_str(
      297│                     b".".join([_idna_encode(label) for label in host.split(".")])
      298│                 )
      299│     return host
      300│ 
  • Installing webencodings (0.5.1): Failed

  AttributeError

  module 'six' has no attribute 'ensure_str'

  at /usr/lib/python3/dist-packages/urllib3/util/url.py:296 in _normalize_host
      292│                     return host[:start].lower() + zone_id + host[end:]
      293│                 else:
      294│                     return host.lower()
      295│             elif not IPV4_RE.match(host):
    → 296│                 return six.ensure_str(
      297│                     b".".join([_idna_encode(label) for label in host.split(".")])
      298│                 )
      299│     return host
      300│ 
  • Installing pycparser (2.21): Failed
  • Installing webencodings (0.5.1): Failed

  AttributeError

  module 'six' has no attribute 'ensure_str'

  at /usr/lib/python3/dist-packages/urllib3/util/url.py:296 in _normalize_host
      292│                     return host[:start].lower() + zone_id + host[end:]
      293│                 else:
      294│                     return host.lower()
      295│             elif not IPV4_RE.match(host):
    → 296│                 return six.ensure_str(
      297│                     b".".join([_idna_encode(label) for label in host.split(".")])
      298│                 )
      299│     return host
      300│ 

  • Installing webencodings (0.5.1): Failed

  AttributeError

  module 'six' has no attribute 'ensure_str'

  at /usr/lib/python3/dist-packages/urllib3/util/url.py:296 in _normalize_host
      292│                     return host[:start].lower() + zone_id + host[end:]
      293│                 else:
      294│                     return host.lower()
      295│             elif not IPV4_RE.match(host):
    → 296│                 return six.ensure_str(
      297│                     b".".join([_idna_encode(label) for label in host.split(".")])
      298│                 )
      299│     return host
      300│ 
  AttributeError
  • Installing webencodings (0.5.1): Failed

  AttributeError

  module 'six' has no attribute 'ensure_str'

  at /usr/lib/python3/dist-packages/urllib3/util/url.py:296 in _normalize_host
      292│                     return host[:start].lower() + zone_id + host[end:]
      293│                 else:
      294│                     return host.lower()
      295│             elif not IPV4_RE.match(host):
    → 296│                 return six.ensure_str(
      297│                     b".".join([_idna_encode(label) for label in host.split(".")])
      298│                 )
      299│     return host
      300│ 

  • Installing webencodings (0.5.1): Failed

  AttributeError

  module 'six' has no attribute 'ensure_str'

  at /usr/lib/python3/dist-packages/urllib3/util/url.py:296 in _normalize_host
      292│                     return host[:start].lower() + zone_id + host[end:]
      293│                 else:
      294│                     return host.lower()
      295│             elif not IPV4_RE.match(host):
    → 296│                 return six.ensure_str(
      297│                     b".".join([_idna_encode(label) for label in host.split(".")])
      298│                 )
      299│     return host
      300│ 
  module 'six' has no attribute 'ensure_str'
  • Installing webencodings (0.5.1): Failed

  AttributeError

  module 'six' has no attribute 'ensure_str'

  at /usr/lib/python3/dist-packages/urllib3/util/url.py:296 in _normalize_host
      292│                     return host[:start].lower() + zone_id + host[end:]
      293│                 else:
      294│                     return host.lower()
      295│             elif not IPV4_RE.match(host):
    → 296│                 return six.ensure_str(
      297│                     b".".join([_idna_encode(label) for label in host.split(".")])
      298│                 )
      299│     return host
      300│ 

  • Installing webencodings (0.5.1): Failed

  AttributeError

  module 'six' has no attribute 'ensure_str'

  at /usr/lib/python3/dist-packages/urllib3/util/url.py:296 in _normalize_host
      292│                     return host[:start].lower() + zone_id + host[end:]
      293│                 else:
      294│                     return host.lower()
      295│             elif not IPV4_RE.match(host):
    → 296│                 return six.ensure_str(
      297│                     b".".join([_idna_encode(label) for label in host.split(".")])
      298│                 )
      299│     return host
      300│ 
  at /usr/lib/python3/dist-packages/urllib3/util/url.py:296 in _normalize_host
  • Installing webencodings (0.5.1): Failed

  AttributeError

  module 'six' has no attribute 'ensure_str'

  at /usr/lib/python3/dist-packages/urllib3/util/url.py:296 in _normalize_host
      292│                     return host[:start].lower() + zone_id + host[end:]
      293│                 else:
      294│                     return host.lower()
      295│             elif not IPV4_RE.match(host):
    → 296│                 return six.ensure_str(
      297│                     b".".join([_idna_encode(label) for label in host.split(".")])
      298│                 )
      299│     return host
      300│ 
      292│                     return host[:start].lower() + zone_id + host[end:]
  • Installing webencodings (0.5.1): Failed

  AttributeError

  module 'six' has no attribute 'ensure_str'

  at /usr/lib/python3/dist-packages/urllib3/util/url.py:296 in _normalize_host
      292│                     return host[:start].lower() + zone_id + host[end:]
      293│                 else:
      294│                     return host.lower()
      295│             elif not IPV4_RE.match(host):
    → 296│                 return six.ensure_str(
      297│                     b".".join([_idna_encode(label) for label in host.split(".")])
      298│                 )
      299│     return host
      300│ 
      293│                 else:
  • Installing webencodings (0.5.1): Failed

  AttributeError

  module 'six' has no attribute 'ensure_str'

  at /usr/lib/python3/dist-packages/urllib3/util/url.py:296 in _normalize_host
      292│                     return host[:start].lower() + zone_id + host[end:]
      293│                 else:
      294│                     return host.lower()
      295│             elif not IPV4_RE.match(host):
    → 296│                 return six.ensure_str(
      297│                     b".".join([_idna_encode(label) for label in host.split(".")])
      298│                 )
      299│     return host
      300│ 
      294│                     return host.lower()
  • Installing webencodings (0.5.1): Failed

  AttributeError

  module 'six' has no attribute 'ensure_str'

  at /usr/lib/python3/dist-packages/urllib3/util/url.py:296 in _normalize_host
      292│                     return host[:start].lower() + zone_id + host[end:]
      293│                 else:
      294│                     return host.lower()
      295│             elif not IPV4_RE.match(host):
    → 296│                 return six.ensure_str(
      297│                     b".".join([_idna_encode(label) for label in host.split(".")])
      298│                 )
      299│     return host
      300│ 
      295│             elif not IPV4_RE.match(host):
  • Installing webencodings (0.5.1): Failed

  AttributeError

  module 'six' has no attribute 'ensure_str'

  at /usr/lib/python3/dist-packages/urllib3/util/url.py:296 in _normalize_host
      292│                     return host[:start].lower() + zone_id + host[end:]
      293│                 else:
      294│                     return host.lower()
      295│             elif not IPV4_RE.match(host):
    → 296│                 return six.ensure_str(
      297│                     b".".join([_idna_encode(label) for label in host.split(".")])
      298│                 )
      299│     return host
      300│ 
    → 296│                 return six.ensure_str(
  • Installing webencodings (0.5.1): Failed

  AttributeError

  module 'six' has no attribute 'ensure_str'

  at /usr/lib/python3/dist-packages/urllib3/util/url.py:296 in _normalize_host
      292│                     return host[:start].lower() + zone_id + host[end:]
      293│                 else:
      294│                     return host.lower()
      295│             elif not IPV4_RE.match(host):
    → 296│                 return six.ensure_str(
      297│                     b".".join([_idna_encode(label) for label in host.split(".")])
      298│                 )
      299│     return host
      300│ 
      297│                     b".".join([_idna_encode(label) for label in host.split(".")])
  • Installing webencodings (0.5.1): Failed

  AttributeError

  module 'six' has no attribute 'ensure_str'

  at /usr/lib/python3/dist-packages/urllib3/util/url.py:296 in _normalize_host
      292│                     return host[:start].lower() + zone_id + host[end:]
      293│                 else:
      294│                     return host.lower()
      295│             elif not IPV4_RE.match(host):
    → 296│                 return six.ensure_str(
      297│                     b".".join([_idna_encode(label) for label in host.split(".")])
      298│                 )
      299│     return host
      300│ 
      298│                 )
  • Installing webencodings (0.5.1): Failed

  AttributeError

  module 'six' has no attribute 'ensure_str'

  at /usr/lib/python3/dist-packages/urllib3/util/url.py:296 in _normalize_host
      292│                     return host[:start].lower() + zone_id + host[end:]
      293│                 else:
      294│                     return host.lower()
      295│             elif not IPV4_RE.match(host):
    → 296│                 return six.ensure_str(
      297│                     b".".join([_idna_encode(label) for label in host.split(".")])
      298│                 )
      299│     return host
      300│ 
      299│     return host
  • Installing webencodings (0.5.1): Failed

  AttributeError

  module 'six' has no attribute 'ensure_str'

  at /usr/lib/python3/dist-packages/urllib3/util/url.py:296 in _normalize_host
      292│                     return host[:start].lower() + zone_id + host[end:]
      293│                 else:
      294│                     return host.lower()
      295│             elif not IPV4_RE.match(host):
    → 296│                 return six.ensure_str(
      297│                     b".".join([_idna_encode(label) for label in host.split(".")])
      298│                 )
      299│     return host
      300│ 
      300│ 
  • Installing webencodings (0.5.1): Failed

  AttributeError

  module 'six' has no attribute 'ensure_str'

  at /usr/lib/python3/dist-packages/urllib3/util/url.py:296 in _normalize_host
      292│                     return host[:start].lower() + zone_id + host[end:]
      293│                 else:
      294│                     return host.lower()
      295│             elif not IPV4_RE.match(host):
    → 296│                 return six.ensure_str(
      297│                     b".".join([_idna_encode(label) for label in host.split(".")])
      298│                 )
      299│     return host
      300│ 

  • Installing webencodings (0.5.1): Failed

  AttributeError

  module 'six' has no attribute 'ensure_str'

  at /usr/lib/python3/dist-packages/urllib3/util/url.py:296 in _normalize_host
      292│                     return host[:start].lower() + zone_id + host[end:]
      293│                 else:
      294│                     return host.lower()
      295│             elif not IPV4_RE.match(host):
    → 296│                 return six.ensure_str(
      297│                     b".".join([_idna_encode(label) for label in host.split(".")])
      298│                 )
      299│     return host
      300│ 
The following error occurred when trying to handle this error:
  • Installing webencodings (0.5.1): Failed

  AttributeError

  module 'six' has no attribute 'ensure_str'

  at /usr/lib/python3/dist-packages/urllib3/util/url.py:296 in _normalize_host
      292│                     return host[:start].lower() + zone_id + host[end:]
      293│                 else:
      294│                     return host.lower()
      295│             elif not IPV4_RE.match(host):
    → 296│                 return six.ensure_str(
      297│                     b".".join([_idna_encode(label) for label in host.split(".")])
      298│                 )
      299│     return host
      300│ 

  • Installing webencodings (0.5.1): Failed

  AttributeError

  module 'six' has no attribute 'ensure_str'

  at /usr/lib/python3/dist-packages/urllib3/util/url.py:296 in _normalize_host
      292│                     return host[:start].lower() + zone_id + host[end:]
      293│                 else:
      294│                     return host.lower()
      295│             elif not IPV4_RE.match(host):
    → 296│                 return six.ensure_str(
      297│                     b".".join([_idna_encode(label) for label in host.split(".")])
      298│                 )
      299│     return host
      300│ 

  • Installing webencodings (0.5.1): Failed

  AttributeError

  module 'six' has no attribute 'ensure_str'

  at /usr/lib/python3/dist-packages/urllib3/util/url.py:296 in _normalize_host
      292│                     return host[:start].lower() + zone_id + host[end:]
      293│                 else:
      294│                     return host.lower()
      295│             elif not IPV4_RE.match(host):
    → 296│                 return six.ensure_str(
      297│                     b".".join([_idna_encode(label) for label in host.split(".")])
      298│                 )
      299│     return host
      300│ 
  LocationParseError
  • Installing webencodings (0.5.1): Failed

  AttributeError

  module 'six' has no attribute 'ensure_str'

  at /usr/lib/python3/dist-packages/urllib3/util/url.py:296 in _normalize_host
      292│                     return host[:start].lower() + zone_id + host[end:]
      293│                 else:
      294│                     return host.lower()
      295│             elif not IPV4_RE.match(host):
    → 296│                 return six.ensure_str(
      297│                     b".".join([_idna_encode(label) for label in host.split(".")])
      298│                 )
      299│     return host
      300│ 

  • Installing webencodings (0.5.1): Failed

  AttributeError

  module 'six' has no attribute 'ensure_str'

  at /usr/lib/python3/dist-packages/urllib3/util/url.py:296 in _normalize_host
      292│                     return host[:start].lower() + zone_id + host[end:]
      293│                 else:
      294│                     return host.lower()
      295│             elif not IPV4_RE.match(host):
    → 296│                 return six.ensure_str(
      297│                     b".".join([_idna_encode(label) for label in host.split(".")])
      298│                 )
      299│     return host
      300│ 
  Failed to parse: https://pypi.org/pypi/pycparser/2.21/json
  • Installing webencodings (0.5.1): Failed

  AttributeError

  module 'six' has no attribute 'ensure_str'

  at /usr/lib/python3/dist-packages/urllib3/util/url.py:296 in _normalize_host
      292│                     return host[:start].lower() + zone_id + host[end:]
      293│                 else:
      294│                     return host.lower()
      295│             elif not IPV4_RE.match(host):
    → 296│                 return six.ensure_str(
      297│                     b".".join([_idna_encode(label) for label in host.split(".")])
      298│                 )
      299│     return host
      300│ 

  • Installing webencodings (0.5.1): Failed

  AttributeError

  module 'six' has no attribute 'ensure_str'

  at /usr/lib/python3/dist-packages/urllib3/util/url.py:296 in _normalize_host
      292│                     return host[:start].lower() + zone_id + host[end:]
      293│                 else:
      294│                     return host.lower()
      295│             elif not IPV4_RE.match(host):
    → 296│                 return six.ensure_str(
      297│                     b".".join([_idna_encode(label) for label in host.split(".")])
      298│                 )
      299│     return host
      300│ 
  at <string>:2 in raise_from
  • Installing webencodings (0.5.1): Failed

  AttributeError

  module 'six' has no attribute 'ensure_str'

  at /usr/lib/python3/dist-packages/urllib3/util/url.py:296 in _normalize_host
      292│                     return host[:start].lower() + zone_id + host[end:]
      293│                 else:
      294│                     return host.lower()
      295│             elif not IPV4_RE.match(host):
    → 296│                 return six.ensure_str(
      297│                     b".".join([_idna_encode(label) for label in host.split(".")])
      298│                 )
      299│     return host
      300│ 
        1│ 
  • Installing webencodings (0.5.1): Failed

  AttributeError

  module 'six' has no attribute 'ensure_str'

  at /usr/lib/python3/dist-packages/urllib3/util/url.py:296 in _normalize_host
      292│                     return host[:start].lower() + zone_id + host[end:]
      293│                 else:
      294│                     return host.lower()
      295│             elif not IPV4_RE.match(host):
    → 296│                 return six.ensure_str(
      297│                     b".".join([_idna_encode(label) for label in host.split(".")])
      298│                 )
      299│     return host
      300│ 

  • Installing webencodings (0.5.1): Failed

  AttributeError

  module 'six' has no attribute 'ensure_str'

  at /usr/lib/python3/dist-packages/urllib3/util/url.py:296 in _normalize_host
      292│                     return host[:start].lower() + zone_id + host[end:]
      293│                 else:
      294│                     return host.lower()
      295│             elif not IPV4_RE.match(host):
    → 296│                 return six.ensure_str(
      297│                     b".".join([_idna_encode(label) for label in host.split(".")])
      298│                 )
      299│     return host
      300│ 
The following error occurred when trying to handle this error:
  • Installing webencodings (0.5.1): Failed

  AttributeError

  module 'six' has no attribute 'ensure_str'

  at /usr/lib/python3/dist-packages/urllib3/util/url.py:296 in _normalize_host
      292│                     return host[:start].lower() + zone_id + host[end:]
      293│                 else:
      294│                     return host.lower()
      295│             elif not IPV4_RE.match(host):
    → 296│                 return six.ensure_str(
      297│                     b".".join([_idna_encode(label) for label in host.split(".")])
      298│                 )
      299│     return host
      300│ 

  • Installing webencodings (0.5.1): Failed

  AttributeError

  module 'six' has no attribute 'ensure_str'

  at /usr/lib/python3/dist-packages/urllib3/util/url.py:296 in _normalize_host
      292│                     return host[:start].lower() + zone_id + host[end:]
      293│                 else:
      294│                     return host.lower()
      295│             elif not IPV4_RE.match(host):
    → 296│                 return six.ensure_str(
      297│                     b".".join([_idna_encode(label) for label in host.split(".")])
      298│                 )
      299│     return host
      300│ 

  • Installing webencodings (0.5.1): Failed

  AttributeError

  module 'six' has no attribute 'ensure_str'

  at /usr/lib/python3/dist-packages/urllib3/util/url.py:296 in _normalize_host
      292│                     return host[:start].lower() + zone_id + host[end:]
      293│                 else:
      294│                     return host.lower()
      295│             elif not IPV4_RE.match(host):
    → 296│                 return six.ensure_str(
      297│                     b".".join([_idna_encode(label) for label in host.split(".")])
      298│                 )
      299│     return host
      300│ 
  InvalidURL
  • Installing webencodings (0.5.1): Failed

  AttributeError

  module 'six' has no attribute 'ensure_str'

  at /usr/lib/python3/dist-packages/urllib3/util/url.py:296 in _normalize_host
      292│                     return host[:start].lower() + zone_id + host[end:]
      293│                 else:
      294│                     return host.lower()
      295│             elif not IPV4_RE.match(host):
    → 296│                 return six.ensure_str(
      297│                     b".".join([_idna_encode(label) for label in host.split(".")])
      298│                 )
      299│     return host
      300│ 

  • Installing webencodings (0.5.1): Failed

  AttributeError

  module 'six' has no attribute 'ensure_str'

  at /usr/lib/python3/dist-packages/urllib3/util/url.py:296 in _normalize_host
      292│                     return host[:start].lower() + zone_id + host[end:]
      293│                 else:
      294│                     return host.lower()
      295│             elif not IPV4_RE.match(host):
    → 296│                 return six.ensure_str(
      297│                     b".".join([_idna_encode(label) for label in host.split(".")])
      298│                 )
      299│     return host
      300│ 
  Failed to parse: https://pypi.org/pypi/pycparser/2.21/json
  • Installing webencodings (0.5.1): Failed

  AttributeError

  module 'six' has no attribute 'ensure_str'

  at /usr/lib/python3/dist-packages/urllib3/util/url.py:296 in _normalize_host
      292│                     return host[:start].lower() + zone_id + host[end:]
      293│                 else:
      294│                     return host.lower()
      295│             elif not IPV4_RE.match(host):
    → 296│                 return six.ensure_str(
      297│                     b".".join([_idna_encode(label) for label in host.split(".")])
      298│                 )
      299│     return host
      300│ 

  • Installing webencodings (0.5.1): Failed

  AttributeError

  module 'six' has no attribute 'ensure_str'

  at /usr/lib/python3/dist-packages/urllib3/util/url.py:296 in _normalize_host
      292│                     return host[:start].lower() + zone_id + host[end:]
      293│                 else:
      294│                     return host.lower()
      295│             elif not IPV4_RE.match(host):
    → 296│                 return six.ensure_str(
      297│                     b".".join([_idna_encode(label) for label in host.split(".")])
      298│                 )
      299│     return host
      300│ 
  at /usr/local/lib/python3.10/dist-packages/requests/models.py:436 in prepare_url
  • Installing webencodings (0.5.1): Failed

  AttributeError

  module 'six' has no attribute 'ensure_str'

  at /usr/lib/python3/dist-packages/urllib3/util/url.py:296 in _normalize_host
      292│                     return host[:start].lower() + zone_id + host[end:]
      293│                 else:
      294│                     return host.lower()
      295│             elif not IPV4_RE.match(host):
    → 296│                 return six.ensure_str(
      297│                     b".".join([_idna_encode(label) for label in host.split(".")])
      298│                 )
      299│     return host
      300│ 
       432│         # Support for unicode domain names and paths.
  • Installing webencodings (0.5.1): Failed

  AttributeError

  module 'six' has no attribute 'ensure_str'

  at /usr/lib/python3/dist-packages/urllib3/util/url.py:296 in _normalize_host
      292│                     return host[:start].lower() + zone_id + host[end:]
      293│                 else:
      294│                     return host.lower()
      295│             elif not IPV4_RE.match(host):
    → 296│                 return six.ensure_str(
      297│                     b".".join([_idna_encode(label) for label in host.split(".")])
      298│                 )
      299│     return host
      300│ 
       433│         try:
  • Installing webencodings (0.5.1): Failed

  AttributeError

  module 'six' has no attribute 'ensure_str'

  at /usr/lib/python3/dist-packages/urllib3/util/url.py:296 in _normalize_host
      292│                     return host[:start].lower() + zone_id + host[end:]
      293│                 else:
      294│                     return host.lower()
      295│             elif not IPV4_RE.match(host):
    → 296│                 return six.ensure_str(
      297│                     b".".join([_idna_encode(label) for label in host.split(".")])
      298│                 )
      299│     return host
      300│ 
       434│             scheme, auth, host, port, path, query, fragment = parse_url(url)
  • Installing webencodings (0.5.1): Failed

  AttributeError

  module 'six' has no attribute 'ensure_str'

  at /usr/lib/python3/dist-packages/urllib3/util/url.py:296 in _normalize_host
      292│                     return host[:start].lower() + zone_id + host[end:]
      293│                 else:
      294│                     return host.lower()
      295│             elif not IPV4_RE.match(host):
    → 296│                 return six.ensure_str(
      297│                     b".".join([_idna_encode(label) for label in host.split(".")])
      298│                 )
      299│     return host
      300│ 
       435│         except LocationParseError as e:
  • Installing webencodings (0.5.1): Failed

  AttributeError

  module 'six' has no attribute 'ensure_str'

  at /usr/lib/python3/dist-packages/urllib3/util/url.py:296 in _normalize_host
      292│                     return host[:start].lower() + zone_id + host[end:]
      293│                 else:
      294│                     return host.lower()
      295│             elif not IPV4_RE.match(host):
    → 296│                 return six.ensure_str(
      297│                     b".".join([_idna_encode(label) for label in host.split(".")])
      298│                 )
      299│     return host
      300│ 
    →  436│             raise InvalidURL(*e.args)
  • Installing webencodings (0.5.1): Failed

  AttributeError

  module 'six' has no attribute 'ensure_str'

  at /usr/lib/python3/dist-packages/urllib3/util/url.py:296 in _normalize_host
      292│                     return host[:start].lower() + zone_id + host[end:]
      293│                 else:
      294│                     return host.lower()
      295│             elif not IPV4_RE.match(host):
    → 296│                 return six.ensure_str(
      297│                     b".".join([_idna_encode(label) for label in host.split(".")])
      298│                 )
      299│     return host
      300│ 
       437│ 
  • Installing webencodings (0.5.1): Failed

  AttributeError

  module 'six' has no attribute 'ensure_str'

  at /usr/lib/python3/dist-packages/urllib3/util/url.py:296 in _normalize_host
      292│                     return host[:start].lower() + zone_id + host[end:]
      293│                 else:
      294│                     return host.lower()
      295│             elif not IPV4_RE.match(host):
    → 296│                 return six.ensure_str(
      297│                     b".".join([_idna_encode(label) for label in host.split(".")])
      298│                 )
      299│     return host
      300│ 
       438│         if not scheme:
  • Installing webencodings (0.5.1): Failed

  AttributeError

  module 'six' has no attribute 'ensure_str'

  at /usr/lib/python3/dist-packages/urllib3/util/url.py:296 in _normalize_host
      292│                     return host[:start].lower() + zone_id + host[end:]
      293│                 else:
      294│                     return host.lower()
      295│             elif not IPV4_RE.match(host):
    → 296│                 return six.ensure_str(
      297│                     b".".join([_idna_encode(label) for label in host.split(".")])
      298│                 )
      299│     return host
      300│ 
       439│             raise MissingSchema(
  • Installing webencodings (0.5.1): Failed

  AttributeError

  module 'six' has no attribute 'ensure_str'

  at /usr/lib/python3/dist-packages/urllib3/util/url.py:296 in _normalize_host
      292│                     return host[:start].lower() + zone_id + host[end:]
      293│                 else:
      294│                     return host.lower()
      295│             elif not IPV4_RE.match(host):
    → 296│                 return six.ensure_str(
      297│                     b".".join([_idna_encode(label) for label in host.split(".")])
      298│                 )
      299│     return host
      300│ 
       440│                 f"Invalid URL {url!r}: No scheme supplied. "
  • Installing webencodings (0.5.1): Failed

  AttributeError

  module 'six' has no attribute 'ensure_str'

  at /usr/lib/python3/dist-packages/urllib3/util/url.py:296 in _normalize_host
      292│                     return host[:start].lower() + zone_id + host[end:]
      293│                 else:
      294│                     return host.lower()
      295│             elif not IPV4_RE.match(host):
    → 296│                 return six.ensure_str(
      297│                     b".".join([_idna_encode(label) for label in host.split(".")])
      298│                 )
      299│     return host
      300│ 

  • Installing webencodings (0.5.1): Failed

  AttributeError

  module 'six' has no attribute 'ensure_str'

  at /usr/lib/python3/dist-packages/urllib3/util/url.py:296 in _normalize_host
      292│                     return host[:start].lower() + zone_id + host[end:]
      293│                 else:
      294│                     return host.lower()
      295│             elif not IPV4_RE.match(host):
    → 296│                 return six.ensure_str(
      297│                     b".".join([_idna_encode(label) for label in host.split(".")])
      298│                 )
      299│     return host
      300│ 

The following error occurred when trying to handle this error:

  LocationParseError

  Failed to parse: https://pypi.org/pypi/webencodings/0.5.1/json

  at <string>:2 in raise_from
        1│ 

The following error occurred when trying to handle this error:

  InvalidURL

  Failed to parse: https://pypi.org/pypi/webencodings/0.5.1/json

  at /usr/local/lib/python3.10/dist-packages/requests/models.py:436 in prepare_url
       432│         # Support for unicode domain names and paths.
       433│         try:
       434│             scheme, auth, host, port, path, query, fragment = parse_url(url)
       435│         except LocationParseError as e:
    →  436│             raise InvalidURL(*e.args)
       437│ 
       438│         if not scheme:
       439│             raise MissingSchema(
       440│                 f"Invalid URL {url!r}: No scheme supplied. "

### Expected Behavior

install works

### Steps To Reproduce

git clone --recursive https://github.com/BC-SECURITY/Empire.git
cd Empire
./setup/checkout-latest-tag.sh
sudo ./setup/install.sh

**Comment by Cx01N** [comment]
Have you tried running an update or your box? I am unable to recreate this unfortunately.
