### ISSUE TITLE
Which version of Python 3?

### ISSUE THREAD

**Issue by complana** [BC-SECURITY/Empire#71]
Would be great to know what version of Python3 was used by the dev to test the latest release? Getting different errors on different python version when creating stagers.

Thanks!

**Comment by Hubbl3** [comment]
@complana can you provide some more details. Which stager module are you having issues with and what errors are you getting. 

We test with 3.7 mostly but it should be broadly compatible across 3.x

**Comment by complana** [comment]
Many thanks.

For example: I tested initially with 3.8.1. But the staging process threw some error (HMAC Verification failed). Apparently for 3.8, the digestmod parameter for hmac.new() function is **required** (previously optional). Changing all occurrences of hmac.new() to include the digestmod parameter fixed it.

**Comment by complana** [comment]
I can create a PR if that helps

**Comment by Hubbl3** [comment]
@complana 

It would be great if you could submit a PR. However, we are striving to maintain 2.7 backwards compatibility so if that hmac.new() change isn't supported by the futures module we may just have to note that Empire is not 3.8 compatible.

**Comment by complana** [comment]
Hi @Hubbl3 I have created a PR in dev. And tested this with 3.8.1 and 2.7.17. Seems to be working fine
