### ISSUE TITLE
TypeError: cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by rtaylor777** [BC-SECURITY/Empire#74]
## Empire Version
Just installed
git clone https://github.com/BC-SECURITY/Empire.git

## OS Information (Linux flavor, Python version)
root@kali:/opt/Empire# cat /etc/os-release 
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
ID=kali
VERSION="2019.4"
VERSION_ID="2019.4"
VERSION_CODENAME="kali-rolling"
ID_LIKE=debian
ANSI_COLOR="1;31"
HOME_URL="https://www.kali.org/"
SUPPORT_URL="https://forums.kali.org/"
BUG_REPORT_URL="https://bugs.kali.org/"

root@kali:/opt/Empire# uname -a
Linux kali 5.3.0-kali3-686-pae #1 SMP Debian 5.3.15-1kali1 (2019-12-09) i686 GNU/Linux

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
I would like it to start.
I ran the setup as indicated:
./setup/install.sh

I saw this error during the install:
dpkg: error: cannot access archive 'libicu57_57.1-6+deb9u2_amd64.deb': No such file or directory

Then ran:
apt-get install libicu57

Text of error is below...
## Screenshot of error, embedded text output, or Pastebin link to the error
root@kali:/opt/Empire# ./empire
Traceback (most recent call last):
  File "./empire", line 1426, in <module>
    main = empire.MainMenu(args=args)
  File "/opt/Empire/lib/common/empire.py", line 98, in __init__
    (self.isroot, self.installPath, self.ipWhiteList, self.ipBlackList, self.obfuscate, self.obfuscateCommand) = helpers.get_config('rootuser, install_path,ip_whitelist,ip_blacklist,obfuscate,obfuscate_command')
TypeError: cannot unpack non-iterable NoneType object

**Comment by pbssubhash** [comment]
Same issue, Just installed. 

Here are the details.

#### OS Information:
```
PRETTY_NAME="Parrot GNU/Linux 4.7"
NAME="Parrot GNU/Linux"
ID=parrot
ID_LIKE=debian
VERSION="4.7"
VERSION_ID="4.7"
HOME_URL="https://www.parrotsec.org/"
SUPPORT_URL="https://community.parrotsec.org/"
BUG_REPORT_URL="https://nest.parrotsec.org/"
```

Python Version: 
```
Python 3.7.5 (default, Oct 27 2019, 15:43:29)
```
Uname: 
```
Linux parrot 5.2.0-2parrot1-amd64 #1 SMP Debian 5.2.9-2parrot1 (2019-08-25) x86_64 GNU/Linux
```

Full Error: 
```
Traceback (most recent call last):
  File "./empire", line 1426, in <module>
    main = empire.MainMenu(args=args)
  File "/opt/tools/Empire/lib/common/empire.py", line 98, in __init__
    (self.isroot, self.installPath, self.ipWhiteList, self.ipBlackList, self.obfuscate, self.obfuscateCommand) = helpers.get_config('rootuser, install_path,ip_whitelist,ip_blacklist,obfuscate,obfuscate_command')
TypeError: cannot unpack non-iterable NoneType object
```

Will be more than happy to provide any additional details.

**Comment by Hubbl3** [comment]
@pbssubhash and @rtaylor777. Sometimes the database gets messed up during the initial install just run reset.sh and it should work fine.

**Comment by pbssubhash** [comment]
Thanks. Worked like a charm.

**Comment by secfb** [comment]
```bash
apt install powersell-empire 
```
Execute
```bash
powersell-empire
```

**Comment by meetgyn** [comment]
> 
> 
> @pbssubhash and @rtaylor777. Sometimes the database gets messed up during the initial install just run reset.sh and it should work fine.

Thank you so much men, I had the same problem and it was solved
