### ISSUE TITLE
[BUG] empire/starkiller - agent not found

### ISSUE THREAD

**Issue by jfmaes** [BC-SECURITY/Empire#743]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Empire Version

5.11.2

### Python Version

3.12.2

### Operating System

linux

### Database

SQLite

### Current Behavior

on occassions when running modules the agent identifier can not be found. this is particularly frequent when the agent got renamed, but also happens when the agent is not renamed either. 

It's hard to pinpoint the cause of the bug, as the starkiller ui just gives you a very generic error message, the ps-empire terminal also does not give a proper stack trace even with logging set to debug.

the most verbose messaging I had was when using the client version of ps-empire. 

### Expected Behavior

expect modules to run and identify the correct agent

### Steps To Reproduce

1. run ps-empire server
2. connect to starkiller or the ps-empire client
3. select for example `usemodule/bof_situational_awareness_get_password_policy`
4. fill out the needed options for the module you selected
5. press submit or execute

### Anything else?

![Snag_a5746b2](https://github.com/user-attachments/assets/c0df4b89-d80f-48a8-8e99-1847d7251c59)
![Snag_a578523](https://github.com/user-attachments/assets/46a64403-1934-4626-aab0-f0460cb7d364)

**Comment by Cx01N** [comment]
I can confirm this is an issue in the terminal. However, the module does work if you use the form in Starkiller, in case you need to use it while I work on a fix.

On a side note, just a heads up that we are moving to Starkiller as the primary platform, with the client being deprecated in 6.0 since the terminal can replace that functionality.

**Comment by Cx01N** [comment]
Have a fix in place: https://github.com/BC-SECURITY/Starkiller-Sponsors/pull/206
