### ISSUE TITLE
Listener not found! [ISSUE]

### ISSUE THREAD

**Issue by Halcon0303** [BC-SECURITY/Empire#747]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Empire Version

v5.11.4

### Python Version

python 3.11.9

### Operating System

kali

### Database

MariaDB

### Current Behavior

When "uselistener http", error occur "listener not found"

### Expected Behavior

When "uselistener http", error occur "listener not found"

### Steps To Reproduce

![Screenshot 2024-09-13 012310](https://github.com/user-attachments/assets/f70fd061-01e1-4875-8b09-25353ef160b9)

**Comment by Cx01N** [comment]
Do you mind trying in Starkiller and seeing if you get the same issue? We haven't been maintaining the client since we have a terminal in Starkiller that now has similar functionality, and it will be removed in 6.0.

**Comment by Halcon0303** [comment]
I have same issue with starkiller.
And I don't see the my old listeners too.

**Comment by Cx01N** [comment]
Can you walk me through in detail what you are doing or jump on our discord? That way, I can see if it's a bug or just a misconfiguration.

**Comment by Halcon0303** [comment]
After update and upgrade, the empire don't run correctly.
The server and client run, and then I am going to create listener http.
But Listener don't found. And other commands such as "usemoudle", "useplugin", "usestager" don't found value.
How to fix?

**Comment by Cx01N** [comment]
There definitely seems to be something wrong with your install. Can you join our Discord, and we can try to work it out with you?
https://discord.com/invite/P8PZPyf
