### ISSUE TITLE
Invoke_ReverseDNSlookup error

### ISSUE THREAD

**Issue by Cx01N** [BC-SECURITY/Empire#8]
## Empire Version
python3-hubble-1

## OS Information (Linux flavor, Python version)
Kali 2019.3, Python 2.7

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
The following error occurs when running reverse dns.
`/lib/modules/powershell/situational_awareness/network/reverse_dns.py`

> Invoke-ReverseDNSLookup : Parameter set cannot be resolved using the specified named parameters.
> At line:145 char:1
> Invoke-ReverseDNSLookup | % {try{$entry=$_; $ipObj = [System.Net.IPAd ...
>   CategoryInfo          : InvalidArgument: (:) [Invoke-ReverseDNSLookup], ParameterBindingException
>   FullyQualifiedErrorId : AmbiguousParameterSet,Invoke-ReverseDNSLookup
> 
## Any additional information
The error appears to originate in Powershell and not python.

**Comment by roseaj** [comment]
Powershell error has been fixed. However, the task does not return a result and crashes the listener.

**Comment by Cx01N** [comment]
![image](https://user-images.githubusercontent.com/20302208/70409401-814f4700-1a00-11ea-8dd3-3173c69b16d3.png)

Error fixed, closing issue.
