### ISSUE TITLE
Exception: unsupported format string passed to NoneType.__format__ in Agents

### ISSUE THREAD

**Issue by pawp81** [BC-SECURITY/Empire#82]
## Empire Version
3.0.1

## OS Information (Linux flavor, Python version)
Kali Linux

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
After opening "agents" incomplete list of agents is presented and the end of the list there is following error:
[!] Exception: unsupported format string passed to NoneType.__format__
After couple of seconds agents list closes automatically and Empire comes back to main screen. After re-opening agents, the same error below incomplete list of agent is shown but agent list doesn't close. However Empire becomes not responsive: non of the commands is accepted.

## Screenshot of error, embedded text output, or Pastebin link to the error
https://pastebin.com/8dTn3bhU

**Comment by Cx01N** [comment]
@pawp81 It seems that you are running an older version of Empire. Can you update to version 3.0.5 and see if the problem still persists?

**Comment by pawp81** [comment]
@Cx01N thank you. Would you share steps how to update Empire? I don't see it documented.

**Comment by Hubbl3** [comment]
@pawp81 you just have to do a git pull from the Empire folder and then restart Empire
