### ISSUE TITLE
way to update from old version??

### ISSUE THREAD

**Issue by rossiV1** [BC-SECURITY/Empire#83]
## Empire Version
currently 3.0.3 BC-Security Fork

## OS Information (Linux flavor, Python version)
Ubuntu 18.04, python 3.6.9

## Any additional information
Just a question, is there any ways to upgrade the maintain version of empire to latest version without going through a new install?

**Comment by vinnybod** [comment]
you should be able to `git pull origin master` and run the updated code. However, occasionally there are changes that require you to run the reset script.

**Comment by rossiV1** [comment]
> you should be able to `git pull origin master` and run the updated code. However, occasionally there are changes that require you to run the reset script.

the changelog will tell if we need to run the reset script or not right? 

and can the `git pull origin master` or the update script be put on the main page? as some other tools has `--upgrade` such as sqlmap. this will help other users to upgrade their empire version as well

**Comment by Cx01N** [comment]
@rossiV1 At the moment we do not have an upgrade script since we are relying on the built-in functionality of git.
