### ISSUE TITLE
set StagingKey requires 32 characters - unicode-objects must be encoded before hashing

### ISSUE THREAD

**Issue by jorgeorchilles** [BC-SECURITY/Empire#85]
## Empire Version
3.0.5

## OS Information (Linux flavor, Python version)
Linux slingshot 4.15.0-72-generic #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
use listener http
set StagingKey thisisatest
[!] Error in setting listener option: Unicode-objects must be encoded before hashing

## Screenshot of error, embedded text output, or Pastebin link to the error
![image](https://user-images.githubusercontent.com/52384511/73065669-1fdd1d80-3e72-11ea-8f25-b4df9806c20a.png)

## Any additional information
Must set to exactly 32 characters. On 2.5 it automatically calculates it for you.
![image](https://user-images.githubusercontent.com/52384511/73065739-4b600800-3e72-11ea-87ee-15432d307f6c.png)

**Comment by Cx01N** [comment]
Added fix to v3.0.6. Please feel free to reopen if the issue persists.
