### ISSUE TITLE
Listeners occasionally get hung up and stop working

### ISSUE THREAD

**Issue by Invoke-Mimikatz** [BC-SECURITY/Empire#87]
## Empire Version
BC-Security Empire 3.0.5 --branch=dev

## OS Information (Linux flavor, Python version)
Kali GNU/Linux Rolling VERSION 2019.2
Python 3.7.5

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.
Http listeners occasionally stop working. I am not sure the exact cause, but suspect some infinite loop or never ending task in the listener logic that prevents the listener from processing future data.

## Screenshot of error, embedded text output, or Pastebin link to the error
Attempting to exit Empire and shut down listeners:
<img width="783" alt="image" src="https://user-images.githubusercontent.com/57604669/73127059-746ebe80-3f80-11ea-9b04-8195147d113e.png">

Attempting to view the http listener site in a browser:
<img width="855" alt="image" src="https://user-images.githubusercontent.com/57604669/73140311-32578280-403d-11ea-84f7-222c98b84adc.png">

Nmap with service detection on the http listener while it is non-responsive:
<img width="249" alt="image" src="https://user-images.githubusercontent.com/57604669/73127098-01197c80-3f81-11ea-9524-9d48be5268fb.png">

Nmap with service detection on the http listener after listener is responsive again via restart:
<img width="463" alt="image" src="https://user-images.githubusercontent.com/57604669/73127113-2e662a80-3f81-11ea-8459-14ebed69e2fb.png">

**Comment by Cx01N** [comment]
@Invoke-Mimikatz Can you provide the listeners/stagers and the conditions for us to try to recreate it?

**Comment by Invoke-Mimikatz** [comment]
I have been trying to replicate this again and it's proving harder than I thought it would be.  I can tell you that often times when I leave Empire agents alive for long periods of time (days or weeks), I sometimes come back to find all agents are dead. Trying to create new agents also fails. When this happens, I exit Empire and have to `^C^C^C^C^C^C` to kill the listener, which has become unresponsive. 

Here are my listener and launcher configurations:

```(Empire: listeners) > info https

https Options:

  Name              Required    Value                            Description
  ----              --------    -------                          -----------
  Name              True        https                            Name for the listener.
  Host              True        https://XXXXXXXXXX.XXX:443    Hostname/IP for staging.
  BindIP            True        0.0.0.0                          The IP to bind to on the control server.
  Port              True        443                              Port for the listener.
  Launcher          True        powershell -noP -sta -w 1 -enc   Launcher string.
  StagingKey        True        t0XXXXXXXXXXXXXXXXX<M Staging key for initial agent negotiation.
  DefaultDelay      True        2                                Agent delay/reach back interval (in seconds).
  DefaultJitter     True        1                                Jitter in agent reachback interval (0.0-1.0).
  DefaultLostLimit  True        60                               Number of missed checkins before exiting
  DefaultProfile    True        /search?q=news&go=Search&qs=bs&f Default communication profile for the agent.
                                orm=QBRE,/search?q=weather&go=Se
                                arch&qs=bs&form=QBRE,/search?q=m
                                ovie%20tickets&go=Search&qs=bs&f
                                orm=QBRE,/search?q=unit%20conver
                                sion&go=Search&qs=bs&form=QBRE|M
                                ozilla/5.0 (compatible, MSIE 11,
                                Windows NT 6.3; Trident/7.0;
                                rv:11.0) like Gecko|Server:
                                Apache/2.4.38 (Debian)
  CertPath          False       data/                            Certificate path for https listeners.
  KillDate          False                                        Date for the listener to exit (MM/dd/yyyy).
  WorkingHours      False                                        Hours for the agent to operate (09:00-17:00).
  Headers           True        Server:Microsoft-IIS/7.5         Headers for the control server.
  Cookie            False       dqXXXXXFm                         Custom Cookie Name
  StagerURI         False       /download/favicon.ico            URI for the stager. Must use /download/. Example: /download/stager.php
  UserAgent         False       default                          User-agent string to use for the staging request (default, none, or other).
  Proxy             False       default                          Proxy to use for request (default, none, or other).
  ProxyCreds        False       default                          Proxy credentials ([domain\]username:password) to use for request (default, none, or other).
  SlackToken        False                                        Your SlackBot API token to communicate with your Slack instance.
  SlackChannel      False       #general                         The Slack channel or DM that notifications will be sent to.```

```(Empire: stager/multi/launcher) > info

Name: Launcher

Description:
  Generates a one-liner stage0 launcher for Empire.

Options:

  Name             Required    Value             Description
  ----             --------    -------           -----------
  Listener         True        https             Listener to generate stager for.
  Language         True        powershell        Language of the stager to generate.
  StagerRetries    False       0                 Times for the stager to retry
                                                 connecting.
  OutFile          False                         File to output launcher to, otherwise
                                                 displayed on the screen.
  Base64           True        True              Switch. Base64 encode the output.
  Obfuscate        False       False             Switch. Obfuscate the launcher
                                                 powershell code, uses the
                                                 ObfuscateCommand for obfuscation types.
                                                 For powershell only.
  ObfuscateCommand False       Token\All\1       The Invoke-Obfuscation command to use.
                                                 Only used if Obfuscate switch is True.
                                                 For powershell only.
  SafeChecks       True        False             Switch. Checks for LittleSnitch or a
                                                 SandBox, exit the staging process if
                                                 true. Defaults to True.
  UserAgent        False       default           User-agent string to use for the staging
                                                 request (default, none, or other).
  Proxy            False       default           Proxy to use for request (default, none,
                                                 or other).
  ProxyCreds       False       default           Proxy credentials
                                                 ([domain\]username:password) to use for
                                                 request (default, none, or other).
  ScriptLogBypass  False       False             Include cobbr's Script Block Log Bypass
                                                 in the stager code.
  AMSIBypass       False       False             Include mattifestation's AMSI Bypass in
                                                 the stager code.
  AMSIBypass2      False       False             Include Tal Liberman's AMSI Bypass in
                                                 the stager code.```

I'm not certain, but I suspect this could be caused by Flask, not any code within Empire.

**Comment by Hubbl3** [comment]
@Invoke-Mimikatz I have had some times were agents show up stale/dead but are in fact alive and will respond when sent commands but I haven't seen any issues with the listeners hanging

**Comment by Cx01N** [comment]
@Invoke-Mimikatz  Closing the issue for now. Please feel free to reopen if the problem continues.

**Comment by Invoke-Mimikatz** [comment]
I had an engagement today and had this issue pop up again.  I watched as all agents (on different computers) turned from green to yellow, and then yellow to red all at the exact same time. Pretty weird, right? Not usually what I see during engagements. I realized that most likely my listener had crashed and restarted Empire quickly to hopefully recover the agents before the lost limit expired.  After restarting Empire all of my agents were green again and I could once again interact with them.

It always happens semi-randomly, and I have a feeling it might be caused by internet scanners or bots sending weird or malformed data to the Empire http/https listeners.

I left my Empire running tonight and came back to this screenshot. My listeners are hung up here and will only shut down after Ctrl+C.

<img width="939" alt="image" src="https://user-images.githubusercontent.com/57604669/74402558-367bf200-4dea-11ea-9bc8-60117658a167.png">

**Comment by Invoke-Mimikatz** [comment]
pls reopen this issue

**Comment by Cx01N** [comment]
@Invoke-Mimikatz Are you running the rest API when you see the issue?

**Comment by Invoke-Mimikatz** [comment]
> @Invoke-Mimikatz Are you running the rest API when you see the issue?

No, I'm not. Just standard Empire.

**Comment by Cx01N** [comment]
@Invoke-Mimikatz Unfortunately, we are still not experiencing this issue and cannot reproduce it. If you are able to come up with some reproducible steps or conditions then please open a new issue.
