### ISSUE TITLE
Autorun has an exception that makes the stager fail

### ISSUE THREAD

**Issue by xylon-hub** [BC-SECURITY/Empire#95]
## Empire Version
3.6

## OS Information (Linux flavor, Python version)
Linux Debian 10 - Python 3.7

## Expected behavior and description of the error, including any actions taken immediately prior to the error. The more detail the better.

Any module in autorun with a powershell stager causes the stager to fail due to an exception in the code. This means autorun cannot be used in current form

**Comment by Cx01N** [comment]
I pushed a fix to a branch that should fix the issue. Let us know if this doesn't resolve the problem.
Thanks.

**Comment by xylon-hub** [comment]
It works for me, thanks!
